### ISSUE TITLE
Pre-commit hooky

### ISSUE THREAD

**Issue by junekpavel** [cesko-digital/web#100]
Nápad na vylepšení.

Nebylo by od věci nainstalovat [Huskyho](https://typicode.github.io/husky/#/) a nastavit pre-commit hook pro scripty `format` (a případně i `lint:fix`).

Stává se, že člověk zapomene před commitem spustit příkazy ručně a CI pak zbytečně failuje. 

Ušetřilo by to zbytečnou práci a v kombinaci s [lint-staged](https://www.npmjs.com/package/lint-staged) by to ani tolik neprotahovalo dobu commitění.

**Comment by HormCodes** [comment]
Ahoj, Husky znám a kdysi jsme to řešili i na Slacku, že bychom rádi nechali kontrolu na úrovni CI, abychom umožnili push jakéhokoliv kódu, např. typicky rozpracované změny se zakázanými věci typu `console.log`, `let` atd. 

Ale díky moc za nápad! Rozhodně není špatný. Shodou okolností jsem řešil obdobné issue v práci.
