### ISSUE TITLE
Implementace HTTP API endpointu pro přihlášení do Newsletteru

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#107]
**Technologie:** Express, TypeScript, Gatsby, Vercel

V rámci vytvoření stránky projektů (#64)

Při implementaci patičky jsme narazili (#75), že potřebujeme volat [API ecomailu](https://intercom.help/ecomail/cs/articles/66536-api-pro-praci-s-ecomailem) pro přidávání emailů do newsletteru. Pro zakrytí API klíče je nutné vytvořit jednoduchý endpoint, který bude volán po submitování formuláře na klientské straně. 

**Navrhované rozhraní:** 

```
{
   name: "Jan Novák", // Optional
   email: "jan@novak.cz"
}
```

**Inspirace:** Lze se inspirovat [zde](https://www.joshwcomeau.com/gatsby/using-netlify-functions-with-gatsby/), jen nasazení bude provedeno přes Vercel. 

V případě nejasností nebojte se na mne obrátit. 🙂

**Comment by mzadrazi** [comment]
Mrkla bych se na to ;)

**Comment by HormCodes** [comment]
Super, s vánočním zpožděním tě přiřazuji.

**Comment by HormCodes** [comment]
David Rychlý upozornil, že Ecomail potřebuje jméno a příjmení rozdělené. Struktura tedy se může lišit a měla by fungovat stylem _všechno (jméno a příjmení) nebo nic_.

**Comment by mzadrazi** [comment]
> David Rychlý na Slacku upozornil, že Ecomail potřebuje jméno a příjmení rozdělené. Struktura tedy se může lišit a měla by fungovat stylem _všechno (jméno a příjmení) nebo nic_.

Díky za upřesnění. Ještě k tomu mám doplňující dotaz. Můžu tedy předpokládat, že jméno bude ve formátu jméno mezera příjmení? Přemýšlela jsem o tom a napadlo mě, že se i u nás občas vyskytují jména, která se trochu vymykají - například kamarád je příjmením "Ten Hagen". Nevím, jestli se může vyskytnout i případ, že by se někdo registroval např. jako "Anna Marie Nováková". Tím by byl parsing jména a příjmení trošku tricky. Ve většině případů to asi bude jedno jméno a jedno příjmení, ale čert ví.

Teoreticky by se to dalo vyřešit rozdělením formuláře na jméno a příjmení, takže by si to uživatel rozdělil, jak by uznal za vhodné. Případně je otázkou, jak se tyto údaje budou používat v newsletterech?

**Comment by tuanphungcz** [comment]
Bavili jsme se o tom s @HormCodes a stačí když tam bude jen email, tím pádem není třeba řešit parsing jména :)
