### ISSUE TITLE
Vylepšení UX mobilní verze hlavičky

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#108]
**Technologie:** React, TypeScript, Styled Components, Gatsby

Upravit mobilní menu, aby mělo mít tlačítka s výškou a šířkou definovanou ve Figmě (odkaz bude klikatelný přes celou šířku displeje). 

**Figma:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=423%3A11372)

![image](https://user-images.githubusercontent.com/10332399/102380315-10098300-3fc8-11eb-9906-720175f4f8ab.png)

**Comment by poooow** [comment]
Toto bych si vzal.

**Comment by HormCodes** [comment]
Super, přiřadil jsem tě.
