### ISSUE TITLE
Přidání sekce Newsletter do patičky

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#110]
**Technologie:** React, Gatsby, TypeScript, Formik

V rámci implementace stránky projektů (#64) jsme měli issue na implementaci patičky (#75). Nicméně task narostl a dokonce začal být závislý na implementaci API endpointu pro Newsletter (#107), takže jsme zamergovali část bez newsletter sekce a tento task má cíl dokončit tuto sekci. 

Zdrojové kódy se styly pro patičku, které lze a není potřeba využít, jsou k dispozici v [`backup/rework/newsletter_footer`](https://github.com/cesko-digital/web/tree/backup/rework/newsletter_footer). 

**Pár požadavků na výsledné řešení:**

- Využít [Formik](https://formik.org/docs/overview). 
- Logika formu by měla být oddělená do jednotného rozhraní pro komponentu, viz příklad v následujícím komentáři. 

**Figma:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=247%3A6111)

V případě nejasností se nebojte na mne obrátit na Slacku. 🙂 

<img width="480" alt="Screenshot 2020-12-18 at 12 03 18" src="https://user-images.githubusercontent.com/10332399/102607793-3266e200-4129-11eb-9040-329a80da59a2.png">

**Comment by HormCodes** [comment]
Příklad pro oddělení logiky formuláře:

```typescript
// Covered by unit tests
function validateNewsletterForm(values) {
  return {
    // ... email errors
  }
}

function useNewsletterForm({ onSubmit }) {
  const form = useFormik({
    initialValues: { email: '' },
    onSubmit,
    validate: validateNewsletterForm,
  })

  return {
    values: form.values,
    errors: form.errors,
    handlers: {
      emailChange: (event: React.ChangeEvent<HTMLInputElement>) => {
        form.setFieldValue('email', event.target.value)
        // ... validations, etc.
      },
      handleSubmit: form.handleSubmit,
      // ...
    },
  }
}
```

Jedná se o příklad. Je zde několik částí, které by se dali udělat jinak. Výsledné řešení může využívat jinou knihovnu nebo dokonce žádnou. Nebo třeba rozhraní nemusí obsahovat vstup `onSubmit`, ale bude vracet `submitCount`, který bude využitý v renderu. Cíl je částečně oddělit logiku (a stavy) od view a redukovat množství míst s logikou, např: 

```typescript jsx
const form = useNewsletterForm({
    onSubmit: () => {
      console.log('Hello World')
    },
  })

  return (
    <form>
      <input value={form.values} onChange={form.handlers.emailChange} />
    </form>
  )

  // vs...

  const formik = useFormik({
    onSubmit: () => {
      console.log('Hello World')
    },
  })

  return (
    <form>
      <input
        value={formik.values}
        onChange={(event) => {
          formik.setFieldValue('email', event.target.value)
          // ...
        }}
      />
    </form>
  )
 ```
 
 Jak jsem zmínil na začátku, doporučuji postup nejdříve prototyp - vzájemný souhlas - implementace.

**Comment by maral** [comment]
Vezmu si to. Docela mě to chytlo, i když jedu hrozně pomalu, jak ty technologie neznám.

A asi bych to připravil bez samotného volání API, protože to ještě není hotové.
