### ISSUE TITLE
Přidání cookie note na stávájící web

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#119]
- Vizuálně i obsahově stejně jako na [blogu](https://blog.cesko.digital). 
- Pro verzi v `master` (ne `rework`)

**Comment by poooow** [comment]
Toto si vezmu

**Comment by HormCodes** [comment]
Super, přiřazuji tě. 👍

**Comment by poooow** [comment]
Co anglická verze? Nemáme někde přeloženej ten string? Blog má jen českou verzi.

**Comment by HormCodes** [comment]
@zoul, seženeš nám prosím překlad?

**Comment by zoul** [comment]
Tohle je podle mě solidní první verze:

> This website uses cookies to work better and to analyze how people use it. If you are not happy about that, you can turn off cookies in your browser or stop using the site.

**Comment by HormCodes** [comment]
T
