### ISSUE TITLE
Kompletace sekce Zapojte se

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#120]
## Základní info

**Technologie:** React, TypeScript, Gatsby, Storybook

**Požadavky na výsledné řešení:**

- Komponent by neměla obsahovat žádný stav
- Rovnou použít na stránce s projekty
- Fotka bude vložena jako URL (např. https://via.placeholder.com/768x287)
- Ilustrace na pozadí bude jako React komponenta (viz existující ikony a ilustrace)

## Náhled komponenty
<img width="1111" alt="Screenshot 2021-01-21 at 19 50 15" src="https://user-images.githubusercontent.com/10332399/105397901-f0e2be80-5c21-11eb-87b0-aca1797556a9.png">

## Aktuální verze
Aktuální verze se nachází ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)

_V případě nejasností se nebojte zeptat zde pod issue nebo na Slacku jednoho z techleadů. Jeden z nich vám bude k dispozici po celou dobu vývoje._ 🙂

**Comment by MartinaHytychova** [comment]
Ahoj, budu vytvářet obalovou komponentu pro dvě samostatné komponenty "dobrovolnictví" a "nový project" plus implementaci na HP a stránce s projekty

**Comment by MartinaHytychova** [comment]
Ahoj @HormCodes nemohu pushnout do Gitlabu své změny v mé větvi, hází mi to "permission denied: https://github.com/cesko-digital/web.git/" Mohu poprosit o pomoc?

**Comment by HormCodes** [comment]
Ahoj @MartinaHytychova, je potřeba vytvořit fork (tlačítko je na [hlavní stránce repozitáře](https://github.com/cesko-digital/web)) a v rámci něho vytvořit branch, commit a push. Poté by mělo být možné na tomto repozitáři vytvořit pull request. Kdyby nebylo něco jasné, doporučuji kouknout na [tento český návod](https://blog.tomasfejfar.cz/jak-udelat-pullrequest/). Je to tam pěkně popsané.

**Comment by MartinaHytychova** [comment]
Ahoj, děkuji. Teď už se mi to povedlo.
