### ISSUE TITLE
Implementace názvu projektu a projektové fotografie

### ISSUE THREAD

**Issue by tjerabek** [cesko-digital/web#125]
**Technologie:** React, Gatsby, TypeScript, Styled-components

Vytvořit komponentu která je bere `img` a zobrazuje fotografii projektu a zakomponovat na stránku _Detail projektu_ včetně nadpisu a tagline. 

**Specifikace implementace:**

- Komponent by měla být responzivní na základě designu.
- Nastylovat na základě designu v [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)
- Obrázek by měl být lazy loaded (použít nativní atribut)
- Nezapomenout na mobilní verzi (cover přes celou šířku - viz Figma)
- Data (odkaz na cover, jméno a tagline projektu) by měly pocházet z GQL query

## Náhled komponenty

<img width="634" alt="Screenshot 2021-03-07 at 20 19 49" src="https://user-images.githubusercontent.com/10332399/110251803-893ec380-7f82-11eb-8646-56a0d975c34a.png">

## Aktuální verze

Aktuální verze se nachází ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)

---

V případě nejasností se nebojte zeptat zde pod issue nebo na Slacku jednoho z techleadů (@tuanphungcz nebo @HormCodes ). Jeden z nich vám bude k dispozici po celou dobu vývoje. 🙂

**Comment by rostaklein** [comment]
Rad si to vemu 😉

**Comment by HormCodes** [comment]
@rostaklein, mohu poprosit o časový odhad, kdy bude možné očekávat pull request? Popř. myslíš, že by to bylo reálné třeba do soboty, abychom v neděli/pondělí mohli stránku _Detail projektu_ uzavřít? 🙂

**Comment by rostaklein** [comment]
Zrovna jsem se do toho chtel pustit :) Jeste dnes bude PR hotovy.
