### ISSUE TITLE
Implementace sekce o projektu

### ISSUE THREAD

**Issue by tjerabek** [cesko-digital/web#126]
**Technologie:** React, Gatsby, TypeScript, Styled-components

Vytvořit komponentu která zobrazuje sekci o projektu. Data lze mít pouze jako mock a napojení na AirTable vyřešíme odděleně.

**Jak by komponenta měla fungovat:**
- Vytvořit lokalizovaný text header a text description pro 'O projektu' a '8 zapálených dobrovolníku'. 
- Vytvořit grid s `Avatarama` dobrovolníků

**Jak by měla komponta Avatar vypadat:**
- Kompontat by měla brát `img`. V případě že není, komponenta by měla zobrazit šedý background
- Měla by brát `name` a `position` dobrovolníka, které se na základě propu pozicuje vedla nebo pod `Avatarem`

## Náhled komponenty
![Detaily](https://user-images.githubusercontent.com/1576931/104895105-c2d95200-5975-11eb-8e53-00970b0aff4a.png)

## Aktuální verze
Aktuální verze se nachází ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)

V případě nejasností se nebojte zeptat zde pod issue nebo na Slacku jednoho z techleadů (@tuanphungcz nebo @HormCodes ). Jeden z nich vám bude k dispozici po celou dobu vývoje. 🙂

**Comment by MartinaHytychova** [comment]
Ahoj @tuanphungcz ty fotky dobrovolníků budou pak uložené v projektu ve složce `images`? Pak mám ještě dotaz k této části " které se na základě propu pozicuje vedla nebo pod Avatarem", jak je to myšleno? Bude tam volitelná `prop` např.: `direction` a do toho pak třeba hodnota `row` nebo `column`?

**Comment by tuanphungcz** [comment]
cc @HormCodes

**Comment by HormCodes** [comment]
Ahoj @MartinaHytychova, super dotazy. 

**Fotky:** Data pro tuto komponentu budou pocházet z AirTable (viz data pro stránku Přehled projektů) a můžeš očekávat list objektů `{ name, role, profilePictureUrl }`, takže by neměla vzniknout potřeba ukládat obrázek přímo do repozitáře (to platí na projektu obecně). 

**Avatar a pozice:** Je to přesně jak říkáš. 👍 ... Jedná se o návaznost na #127

**Comment by MartinaHytychova** [comment]
@HormCodes děkuji za odpověď, budu se snažit to o víkendu dokončit, v týdnu bylo málo času. :)
