### ISSUE TITLE
Implementace stavu projektu

### ISSUE THREAD

**Issue by tjerabek** [cesko-digital/web#127]
Technologie: React, Gatsby, TypeScript, Styled-components

Vytvořit komponentu která zobrazuje stav projektu.

Komponenta se bude zkládat z několika menších komponent:
- Progress line u právě probíhá - Komponenta bude brát jako prop procento dokocení projektu například `percent={50}`
- Použít nebo vyrobit `Avatar` komponetu 👉 https://github.com/cesko-digital/web/issues/126
- U odkazů vyrobit komponentu pro social media. Komponenta by měla brát jako props `logo`, `url` a `name`
- Button je už vytvořený zde 👉 https://github.com/cesko-digital/web/issues/65

_V případě nejasností se nebojte zeptat zde pod issue nebo na Slacku jednoho z techleadů (@HormCodes nebo @tuanphungcz). Jeden z nich vám bude k dispozici po celou dobu vývoje. :slightly_smiling_face:_

## Náhled komponenty
![Sidebar](https://user-images.githubusercontent.com/1576931/104894985-a0473900-5975-11eb-9723-01406ec9f89e.png)

## Aktuální verze
Aktuální verze se nachází ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)

**Comment by MartinaHytychova** [comment]
Pokud zatím nikdo jiný nemá, mohu o víkendu začít. @tuanphungcz mi již psal, že bych mohla toto issue řešit. :)

**Comment by tuanphungcz** [comment]
@MartinaHytychova ano, je to tvoje 😊 Díky

Cc @HormCodes

**Comment by MartinaHytychova** [comment]
Ahoj @HormCodes , ta ikonka s otazníkem má při najetí zobrazit nějaký text?

**Comment by HormCodes** [comment]
@MartinaHytychova tak dle všeho tam mají být možné stavy projektu, tedy: _Možné stavy: Inkubátor, probíhá, dokončeno_
