### ISSUE TITLE
Implementace galerie projektů

### ISSUE THREAD

**Issue by tjerabek** [cesko-digital/web#128]
Technologie: React, TypeScript, Gatsby, Styled-components

V rámci #128

Vytvořit komponentu dle designu. Komponenta bude brát pole projektů s informacemi, která bude rendrovat karticky komponent (#69).

Komponenta by měla využít komponentu karta projektu  z #69.

V případě nejasností nebojte se na mne obrátit. 🙂

## Náhled komponenty
![Nase projekty](https://user-images.githubusercontent.com/1576931/104894863-7ee64d00-5975-11eb-8081-9653c7b279b8.png)

## Aktuální verze
Aktuální verze se nachází ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)

**Comment by HormCodes** [comment]
Po domluvě s @maral v rámci #129 přiřazuji jemu. 🙂

**Comment by maral** [comment]
Komentář.
