### ISSUE TITLE
Implementace hero bloku

### ISSUE THREAD

**Issue by tjerabek** [cesko-digital/web#129]
## Náhled komponenty
![hero](https://user-images.githubusercontent.com/1576931/104894757-60805180-5975-11eb-9caa-1bd5d1aedc45.png)

## Aktuální verze
Aktuální verze se nachází ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)

_Popis bude rozšířen_

**Comment by maral** [comment]
Můžu si to vzít?

**Comment by HormCodes** [comment]
@maral, určitě, jen tam ještě chybí detailní specifikace, např. kam vedou linky. 

Překladové klíče by měly být: `pages.homepage.sections.hero.{title,descriptions,whatWeDo,contribute}` a obrázky formou url.

**Comment by tuanphungcz** [comment]
Ahojte, omlouvam se moje chyba, zapomnel jsem to sem napsat, ale zrovna tento task uz spolu resime @jirizikes.

**Comment by HormCodes** [comment]
@maral, nechtěl bys tedy namísto toho #128?

**Comment by jirizikes** [comment]
@tuanphungcz  ok, beru si na stararost.

**Comment by maral** [comment]
@HormCodes ok, hoď mi to na hrb.
