### ISSUE TITLE
Implementace bloku hodnot

### ISSUE THREAD

**Issue by tjerabek** [cesko-digital/web#131]
Na hlavní stránce bychom měli mít sekci hodnotách Česko.Digital. Aktuální web sice něco obdobného obsahuje, ale rádi bychom to rozšířili. 

## Základní info

**Technologie:** React, TypeScript, Gatsby, Storybook

**Požadavky na výsledné řešení:**

- Komponenty by neměly obsahovat žádný stav
- Ikony budou vkládány jako React komponenta
- Komponentu rovnou využít na hlavní stránce (`pages/index.ts`)
- Komponenta by měla mít datový vstup (seznam hodnot)

## Náhled komponenty
![Hondoty-2](https://user-images.githubusercontent.com/1576931/104319089-aa35eb80-54e0-11eb-924f-0cf5382009f7.png)

## Aktuální verze
Aktuální verze se nachází ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)

_V případě nejasností se nebojte zeptat zde pod issue nebo na Slacku jednoho z techleadů. Jeden z nich vám bude k dispozici po celou dobu vývoje._ 🙂

**Comment by fidelman** [comment]
muzu to vzit

**Comment by fidelman** [comment]
ahoj
1) vidim ve Figme ze tady existuje jeste blok s fotkami
![Screen Shot 2021-01-29 at 8 31 40 PM](https://user-images.githubusercontent.com/15198653/106319077-2cf4cf80-6271-11eb-927c-7393d671d9a3.png)
je i tato část zadání?
2) mobilni versia je taky cast zadani?

**Comment by HormCodes** [comment]
Ahoj @fidelman, 

1. Na galerii máme samostatné issue:  #132 
2. Ano, omlouvám se, že to chybí v zadání, ale prosím včetně mobilní verze.
