### ISSUE TITLE
Implementace bloku spolupráce

### ISSUE THREAD

**Issue by tjerabek** [cesko-digital/web#133]
**Technologie:** React, Gatsby, TypeScript, Styled-components

Vytvořit komponentu která zobrazuje seznam log partnerů.

**Jak by komponenta měla fungovat:**
- Komponent bere pole obrázků a použitím `map` je vyzobrazí
- Komponent by měla být responzivní na základě [designu](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2).
- Lokalizovaný header s nadpisem

_V případě nejasností se nebojte zeptat zde pod issue nebo na Slacku jednoho z techleadů. Jeden z nich vám bude k dispozici po celou dobu vývoje. :slightly_smiling_face:_

## Náhled komponenty
![Spolupracujeme s](https://user-images.githubusercontent.com/1576931/104894187-a8eb3f80-5974-11eb-9f56-152ef4b2e600.png)

## Aktuální verze
Aktuální verze se nachází ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)

**Comment by fidelman** [comment]
muzu to vzit

**Comment by tuanphungcz** [comment]
@fidelman Je to tvoje 😉

**Comment by HormCodes** [comment]
Update ze Slack komunikace: Tady jsme se všichni dohodli, že přiřadíme někomu jinému a Andrei si vezme jen #131 prozatím. Proto odebírám.

**Comment by halouzkovap** [comment]
Ahoj, těším se na spolupráci. Petra

**Comment by HormCodes** [comment]
Slibované detaily pro implementaci z dnešního callu: 

- Překladový klíč `pages.homepage.sections.partners.title`
- Partneři jako mock (smyšlená jména, odkazy)
- Loga jako odkaz (využít https://via.placeholder.com/400x200)
- Neřešit historii commitů, vyčistíme na závěr
- Vytvořit komponentu v `src/components/sections/partners` (umístění doladíme později)

... snad jsem na nic nezapomněl. 🙂
