### ISSUE TITLE
Dynamické generování ikonky Česko.Digital

### ISSUE THREAD

**Issue by zzen** [cesko-digital/web#15]
Součástí našeho vizuálního stylu je stylizovaná ikonka. Měla by odrážet počet lidí v Česko.Digitál, kteří už přispěli kusem svého času a práce.

Kvůli tomu bychom chtěli dynamicky generovat číslo v přiloženém SVG (a rozšiřovat tu červenou bublinku notifikace v závislosti na počtu číslic).

Zadání: pro API call (ve formátu GET http://api.cesko.digital/icon?input=123 vygeneruj ikonku s číslem 123. 

[Cesko-Digital_ikona.svg.zip](https://github.com/cesko-digital/web/files/3212466/Cesko-Digital_ikona.svg.zip)

**Comment by zzen** [comment]
Updatování jednotlivých umístění ikonky (Slack/Twitter/Facebook/GitHub/LinkedIn) bude separátní práce, tak se tím teď netřeba obtěžovat. Hlavní je ten SVG generátor.

**Comment by tomasfejfar** [comment]
A to samotné API ještě neexistuje? Takže to může být v čemkoli (PHP/JS/Java/C#)?

**Comment by tdtran** [comment]
Odkud se bere cislo `123`? Nemuze nekdo jen tak pro srandu nechat generovat a umistit nekam ikonku s `?input=123456789`?

**Comment by zoul** [comment]
https://zoul.github.io/cd-icons/i/{num}.svg, pesimisticky pouze do 999 😞  Su první?

**Comment by KamilZm** [comment]
Nevím, jak se to číslo bude počítat (počet lidí na Slacku?), ale pokud to bude stylem, že je to počet přihlášených a ne aktivních za posledních X měsíců (třeba 6?), tak to k ničemu není a je to spíše negativní.

**Comment by FilipJirsak** [comment]
Jdu na to…

**Comment by FilipJirsak** [comment]
Mám XSLT šablonu, která umí vygenerovat SVG pro čísla od 0–9999 v základní, šedé, černobílé a negativní variantě:
![2019-05-23 21 21 43  9d4414b86285](https://user-images.githubusercontent.com/2570553/58280399-caabb200-7da0-11e9-8ea2-c712dd56a473.png)
(Ještě to bude chtít doladit s autorem ikony, ty ostatní varianty jsem vzal od oka a ta kulatá se s většími čísly nevejde.) 
Jdu z toho vyrobit API…

**Comment by FilipJirsak** [comment]
Zatím jsem to nasadil k sobě: https://www.jirsak.org/cesko.digital/api/icon?input=9999

**Comment by FilipJirsak** [comment]
Ještě seznam parametrů, které je možné použít:
* `input` – číslo v rozsahu 0–9999, které se zobrazí na odznaku
* `theme` – téma ikony – `standard`, `bw`, `grey`, `negative`
* `background` – barva pozadí (pro SVG), např. `black`nebo `#FF0000` 
* `type` – typ pozadí – `full` nebo `circle`
* `size` – velikost obrázku v SVG jednotkách, např. `50` nebo `200px`
Neznámé hodnoty parametrů se ignorují.

**Comment by woodarius** [comment]
> Nevím, jak se to číslo bude počítat (počet lidí na Slacku?), ale pokud to bude stylem, že je to počet přihlášených a ne aktivních za posledních X měsíců (třeba 6?), tak to k ničemu není a je to (pro mě) spíše negativní. Připomínalo by to např. statistiky herních firem "Naši hru hraje 5 miliónů hráčů", ale z toho si ji 3 miliony stáhly o před 2 roky free víkendu, jednou zapnuly a pak už na to nesáhly.

Mechanika se dnes představovala na setkání, půjde o přispěvatele (pull-requesty, wireframy, grafika, organizace...). Dalším krokem by mohlo být vyvoření databáze jednotlivých členů a přidělení jejich pořadového číslo, které by se mohlo stát sběratelskou trofejí (čím menší číslo tím lépe).

**Comment by woodarius** [comment]
Pokud mohu poprosit, pojďme debatu, kreativní nápady a realizační dotazy zkusit držet na jednom místě (slack kanál projektu) aby informace neunikaly ostatním. Je nepravděpodobné, že by kolegové co nejsou programátory sledovali github a byla by škoda je do toho nezapojit.

Diskuzi zde bych směřoval výhradně k technickým věcem, řešením problémů a ladění kódu.

**Comment by FilipJirsak** [comment]
Repo s kódem a buildem, který jde nasadit do AWS Lambda, je zde: https://github.com/FilipJirsak/cesko-digital-api-icon
Nedaří se mi ale deploy přes `now.sh` (`now.json` je součástí repository), deploy skončí chybou a v logu je jen tohle:
```
└─ @now/lambda@0.5.3
info All dependencies
└─ @now/lambda@0.5.3
Done in 0.70s.
running builder.exports.build...
```

**Comment by chemix** [comment]
Ahoj @FilipJirsak ptal jsem se kamarada ,kde by mohl byt problem s tim nasazenim do now.sh a ten me odkazal na posledni koment zde : https://github.com/zeit/now-builders/issues/16  

copy paste koment "typas pouziva neco co se nebude podporovat dale. Tak myslim ze by mel zvolit neco jineho." 

Sam tomu nerozumim tak jen aspon takhle zprostredkovane, snad pomuze

**Comment by HormCodes** [comment]
Po domluvě s Albertem Zikmundem, který má na starosti novou vizuální identitu >Č.D, jsme se rozhodli issue uzavřít. 

Díky všem za nabízené implementace, toto issue je svým způsobem výrazná součást historie >Č.D. 🙏 🙂
