### ISSUE TITLE
Napojení API newsletteru na formulář v patičce

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#156]
**Technologie:** React, TypeScript, Cypress

Napojení API newsletteru na formulář v patičce 

Na co nezapomenout:
- udělat test v cypressu

## Náhled komponenty
![image](https://user-images.githubusercontent.com/16448321/108183607-892d6f80-710a-11eb-9eb3-452777810bf2.png)

V případě nejasností se nebojte zeptat zde pod issue nebo na Slacku jednoho z techleadů (@tuanphungcz  nebo @HormCodes ). Jeden z nich vám bude k dispozici po celou dobu vývoje. 🙂

**Comment by tuanphungcz** [comment]
@mzadrazi Přiřazuji tady tento task na tebe jak jsme se domlouvali na slacku a díky 😊

**Comment by mzadrazi** [comment]
@tuanphungcz Začala jsem na tom pracovat a mám dotaz ohledně `success` a `error` hlášek. Dívala jsem se do Figmy, jestli je někde nedohledám a nic jsem nenašla. Asi by bylo dobré z hlediska UX dát uživateli vědět, jestli se odběr podařil, nebo ne. Asi tenhle dotaz rovnou hodím do Slacku...

Mělo by se jednat o 3 možné situace:
- odběr se podařil
- chyba uživatele (chybějící email) - tohle by nemělo nastat díky validaci formuláře
- chyba na straně serveru, network issue apod.

**Comment by tuanphungcz** [comment]
@mzadrazi ahoj, souhlasim, ze bychom meli dat vedet uzivateli vedet, ze se uspesne subscribenul. Ohledne tech hlasek bych smeroval na @tjerabek.
