### ISSUE TITLE
Implementace sekce Zapoj se

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#173]
**Technologie:** React, Gatsby, TypeScript, Styled-components

Vytvořit komponentu Zapoj se stránce _Detail projektu_.

**Specifikace implementace:**

- Komponent by měla využít existující komponentu typografie a tlačítka (možnost vytvoření komponenty pro Slack tlačítko a extrakci z karty Zapojte se z homepage).
- Nastylovat na základě designu v [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)
- Text sekce by měl pocházet z GQL query
- Odkaz tlačítka by měl směřovat na https://join.cesko.digital
- Odkaz _jak fungujeme_  by měl směřovat na homepage
- Nezapomenout na překlady, tvar klíče by měl být `pages.project.about.contribute.{title,buttonText,note}`

## Náhled komponenty

<img width="446" alt="Screenshot 2021-03-07 at 20 25 41" src="https://user-images.githubusercontent.com/10332399/110251951-606afe00-7f83-11eb-999f-7c4e0734214b.png">

## Aktuální verze

Aktuální verze se nachází ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2)

---

V případě nejasností se nebojte zeptat zde pod issue nebo na Slacku jednoho z techleadů (@tuanphungcz nebo @HormCodes ). Jeden z nich vám bude k dispozici po celou dobu vývoje. 🙂

**Comment by MartinaHytychova** [comment]
Ahoj @HormCodes mohu si to vzít? Jediné, co budu potřebovat vysvětlit se týká `GQL query`.

**Comment by HormCodes** [comment]
@MartinaHytychova, určitě. 👍  ... Rovnou tě přiřazuji. 🙂 

Pokud jde o GQL query, tak se jedná o návaznost na #171 (rád bych toto zamergoval zítra nebo v úterý), kde je ukázka jakým způsobem se pracuji s daty pro projekt. V podstatě se [query na tomto místě](https://github.com/cesko-digital/web/pull/171/files#diff-4fe80918791a59d2e699cce4f18cd4734536cedd3a75a948e16ea5223c9ed916R97) rozšíří o `contributionText`, získá ze props a pak použije. 

Dá se začít i bez #171 a text přidat jako obdobným způsobem jako je nyní v komponentě projektu, jen je potřeba pamatovat, že budoucí změny budou vypadat přibližně jako #171 a rebase bude nutný.

**Comment by MartinaHytychova** [comment]
@HormCodes super, děkuji. Zítra po práci dám PR.

**Comment by MartinaHytychova** [comment]
Ahoj @HormCodes mám to vpodstatě hotové jen mi tam po přidání `contributionText` qeury hází tuto chybu: 
`Cannot query field "contributionText" on type "Project".

If you don't expect "contributionText" to exist on the type "Project" it is most likely a typo.` Jsem rebasnutá na poslední změny, takže #171 tam již mám.

**Comment by HormCodes** [comment]
Ahoj @MartinaHytychova, díky moc za dotazy. Omlouvám se, tady jsem se spletl a namísto `contributionText` bys měla použít `contributeText`, který už tam je. 

V případě překladového klíče, tak to je dobrý point. Pro jednoduchost to opravdu můžeme rozdělit. Napadá mne na `note` a `noteLink`, ale nebráním se i nějakým jiným (lepším variantám).

**Comment by MartinaHytychova** [comment]
Ahoj @HormCodes v pohodě, děkuju za odpověď. Upravila jsem. Ještě squashnu commity a bude to na kontrolu.
