### ISSUE TITLE
Aktualizace obsahu

### ISSUE THREAD

**Issue by sigy** [cesko-digital/web#20]
Je potřeba:
– přidat sekci Hodnoty a Projekty,
– aktualizovat informace o dalším meetupu,
– skrýt sekci pro média (?),
– aktualizovat navigaci v hlavičce a patičce (odstranit Kdo jsme a Média, přidat Hodnoty a Projekty),
– aktualizovat počet členů,
– odrazit c2a odkazy na nové řádky v sekci "Co je Česko.Digital".

**Comment by zzen** [comment]
- Projekty přidány
- info o meetupu aktualizováno
- média sekci nechám
- počet členů aktualizován

chybí:
- sekce projektů v angličtině
- aktualizovaná navigace
- aktualizované řádky "co je česko.digital"
- sekce Hodnoty

**Comment by woodarius** [comment]
- Hodnoty přidány
- rozšířen FAQ
- přidány odkazy na form s náborem projektů
- upraveno pořadí sekcí na webu
- počet členů aktualizován
- u Projektů přidány odkazy na Trello
- další drobné úpravy

**Comment by zzen** [comment]
pro teď zavřeno, kromě projektů v angličtině (#31) zbytek hotov
