### ISSUE TITLE
Persistentní scroll při přechodu na detail projektu

### ISSUE THREAD

**Issue by tjerabek** [cesko-digital/web#208]
Problém:
Při přechodu na detail projektu zůstává scroll nastavený ze seznamu projektů.

Jak reprodukovat:
- Jít na seznam projektů
- Kliknout na projekt
- Scroll zůstane uprostřed stránky

**Comment by radkoa** [comment]
Na Chrome 89/Windows se mi to neděje, není to specifikum Safari nebo Mac? Někdo další to může ověřit?

**Comment by tuanphungcz** [comment]
fix je na ceste: https://github.com/cesko-digital/web/pull/214
