### ISSUE TITLE
Velikost/šířka galerie fotografií by měla přesahovat šířku obsahu

### ISSUE THREAD

**Issue by radkoa** [cesko-digital/web#210]
Implementace galerie fotografií neodpovídá záměru v návrhu. Minimálně šířka komponenty by měla přesahovat ostatní obsah.

**Aktuální implementace:**
![image](https://user-images.githubusercontent.com/8057526/112953183-8f692f80-913d-11eb-8f6d-30df95a24cd3.png)

**Návrh ve Figmě:**
![image](https://user-images.githubusercontent.com/8057526/112953319-ad369480-913d-11eb-8003-0e815a24fa98.png)

Viz [Figma](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=5%3A6250).

**Comment by radkoa** [comment]
Původní issue: #132

**Comment by tuanphungcz** [comment]
fix je na ceste: https://github.com/cesko-digital/web/pull/218
