### ISSUE TITLE
Nedostatky mobilní verze webu

### ISSUE THREAD

**Issue by radkoa** [cesko-digital/web#211]
###  # 1.1: Ořez loga č.d
Projevuje se mi pouze na mobilu (latest Chrome mobile):
![image](https://user-images.githubusercontent.com/8057526/112963354-9301b400-9147-11eb-856c-48d6c63a1e69.png)

###  # 1.2: Font v hero sekci
Má být 20px, je 15px, viz [Figma](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=425%3A19).
![image](https://user-images.githubusercontent.com/8057526/112963741-f2f85a80-9147-11eb-8097-46f90a40a6c8.png)

###  # 1.3: Poloha a z-index ilustrace (mapy)
Mapa umístěna přes tlačítko, posunuta dolů.
Viz [Figma](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=425%3A19).
![image](https://user-images.githubusercontent.com/8057526/112963893-1a4f2780-9148-11eb-8d7c-522c95998944.png)

###  # 1.4: Velikost tlačítek
Dle návrhu by měla být tlačítka stejně široká
![image](https://user-images.githubusercontent.com/8057526/112968780-e9252600-914c-11eb-9bc2-f7bd3add9b7e.png)

###  # 2.1: Odsazení sekce join
Velký posun dolů, [viz Figma](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=428%3A100).
![image](https://user-images.githubusercontent.com/8057526/112964407-99446000-9148-11eb-85b8-de5657a0de4a.png)

###  # 2.2: Pouze na mobilu (Chrome mobile)
![image](https://user-images.githubusercontent.com/8057526/112965877-f68ce100-9149-11eb-861c-91c48a24f3e4.png)

###  # 2.3: Tlačítko "Přidat se do Slacku" přetéká, malý bottom margin tlačítka
(+ neodpovídá barva textu /Dark Grey vs. Blue/ )
![image](https://user-images.githubusercontent.com/8057526/112964926-0e179a00-9149-11eb-9e52-0082523c7ae1.png)

###  # 2.4: Karta "Mám nápad na projekt"
Velké odsazení nadpisu + [dle Figmy](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=428%3A100) symbol žárovky žlutý.
![image](https://user-images.githubusercontent.com/8057526/112965368-7cf4f300-9149-11eb-8268-ab2415a855bd.png)

###  # 2.5: Šířka tlačítka neodpovídá návrhu
Dle návrhu by měla být šířka tlačítka dle šířky okolního obsahu (textu), ne textu tlačítka samotného.
![image](https://user-images.githubusercontent.com/8057526/112966840-e6c1cc80-914a-11eb-813a-4f478230ba27.png)

###  # 3.1: Neodpovídá velikost fontu
Má být ([dle návrhu](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=428%3A3003)) 23px, je 20px:
![image](https://user-images.githubusercontent.com/8057526/112967529-a7e04680-914b-11eb-80ce-491b409c7e93.png)

###  # 4.1: Odsazení komponenty + horizontální posun/ořez fotek (minoritní):
Velké horní odsazení. 
![image](https://user-images.githubusercontent.com/8057526/112968193-58e6e100-914c-11eb-8f2d-587a9b428690.png)

###  # 5.1: Font textu
Má být _font-weight: 600; font-size: 28px;_, je _font-weight: **700**; font-size: 28px;_
![image](https://user-images.githubusercontent.com/8057526/112969150-45884580-914d-11eb-8d0f-f445be78a04c.png)

**Comment by tuanphungcz** [comment]
Udelal jsem vetsinu z toho, chybi nam jeste dotahnout 

1.1: Ořez loga č.d
# 1.4: Velikost tlačítek
# 2.2: Pouze na mobilu (Chrome mobile)
# 2.3: Tlačítko "Přidat se do Slacku" přetéká, malý bottom margin tlačítka
# 2.5: Šířka tlačítka neodpovídá návrhu

**Comment by tuanphungcz** [comment]
![image](https://user-images.githubusercontent.com/16448321/113168767-400e2680-9245-11eb-8df7-b2969172fce7.png)

na tabletu chybi margin
