### ISSUE TITLE
Vrácení en verze

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#223]
Ref: #222 (commit: `8f0584a9904e9a6fc9618a373627822c0602e811`) a #224 (commit: `16d2426f7d1dff0cb0bbfb4f2137d1b2272019d2`)

**Comment by zoul** [comment]
Tohle už předpokládám není aktuální, takže to zavřu a kdybysme se k tomu potřebovali vrátit, vylovíme issue z historie.
