### ISSUE TITLE
Špatné zarovnání odkazů na stránce Detail projektu

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#225]
<img width="304" alt="Screenshot 2021-04-09 at 14 04 07" src="https://user-images.githubusercontent.com/10332399/114177287-8269ee80-993c-11eb-86bf-f8799b26c33a.png">

https://cesko.digital/projekty/loono

**Comment by MartinaHytychova** [comment]
Ahoj, zarovnání se má tedy chovat tak, že druhý řádek bude u slacku odsazený? A v buttonu, že bude zarovnaný na třed blíže k ikonce místo doleva?

**Comment by HormCodes** [comment]
Ahoj, super dotaz. Přiznám se, že ideální řešení neznám a klidně uvítám vlastní nápady. Tzv. trochu si s tím pohrát a zvolit ideální řešení. 🙂 

Tím, že máme limitovanou celkovou šířku, tak asi v nějaký moment bude nutné řešení **i** s [ellipsis](https://www.w3schools.com/cssref/css3_pr_text-overflow.asp).
