### ISSUE TITLE
Změna šířky containeru pro text sekce Projekty

### ISSUE THREAD

**Issue by snorbik** [cesko-digital/web#257]
Na stránce projekty (https://cesko.digital/projekty) neodpovídá šířka textů oproti designu. Správně by měly texty být asi jen v nějakých 7/12 sloupců.

Nyní je na celou šířku

![Snímek obrazovky 2021-04-15 104523](https://user-images.githubusercontent.com/9628098/114841035-b4190480-9dd7-11eb-848a-cfe16805a86d.png)

**Comment by MartinaHytychova** [comment]
Beru si na starost
