### ISSUE TITLE
Implementace nového designu přepínání na EN verzi v menu

### ISSUE THREAD

**Issue by jindrich-oukropec** [cesko-digital/web#260]
Odkaz na "english" verzi byl původně navržen jako jeden z dalších odkazů v menu

Na [figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=1%3A2) už máme nový design, prosím o zapracování.

<img width="551" alt="Snímek obrazovky 2021-04-22 v 9 40 31" src="https://user-images.githubusercontent.com/69157075/115675438-df0ed580-a34e-11eb-91ff-501f94fe2e15.png">

**Comment by zoul** [comment]
Ten přepínač jazyků dnes funguje jinak, takže tohle zavírám – kdyby bylo potřeba, ozvi se, Jindro, díky!
