### ISSUE TITLE
Projektové karty přiznávají barvu i když by podle designu měly fotku odbarvit a překrýt barevným filtrem

### ISSUE THREAD

**Issue by jindrich-oukropec** [cesko-digital/web#263]
<img width="844" alt="Snímek obrazovky 2021-04-22 v 9 54 55" src="https://user-images.githubusercontent.com/69157075/115677492-d0292280-a350-11eb-94d4-1b4b1076e402.png">

**Comment by zoul** [comment]
Tohle už se podle mě neděje.

**Comment by jindrich-oukropec** [comment]
@zoul když se dívám na náš web, tak se to pořád děje
všechny cover fotky by se v náhledu měly překrýt tak, že obrázek je vidět z 20% a přes něj je naše modrá #0000FF

**Comment by zoul** [comment]
Aha! Mea culpa, vrátím do hry, špatně jsem pochopil.

**Comment by zoul** [comment]
Tohle nakonec nechceme dělat, podle mě je té modré už takhle dost a ty různobarevné karty mně přijdou dobré. Časem uděláme nějakou obrátku na zlepšení designu, tam si můžeme s nějakým designérem nebo designérkou říct, kdyby to potřebovalo vyřešit jinak.
