### ISSUE TITLE
Markdown podpora pro texty v AirTable

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#269]
- AT umožňuje formátování pro `Long Text`
- Bylo by nápomocné umžožnit podporu pro základní věci jako **bold**, _italic_, [odkaz](url) atd.
- Podpora v překladech a podpora v projektových textech

**Comment by zoul** [comment]
Tohle není těžké (jde to obšlehnout z [formátování textů eventů](https://github.com/cesko-digital/web/blob/63018771621843ec8d0b6fa61e3149872f219000/plugins/gatsby-source-cd-airtable/src/transformers.ts#L130)) a hodně bysme to chtěli, jelikož editoři v popisech projektů už teď používají aspoň jednoduché řádkování, které pak nepřežije převod do HTML (odstavce se slijou do jednoho) a je to smutné :) Píšu to sem hlavně pro sebe, rád bych na to mrknul.
