### ISSUE TITLE
 Implementace vícekrokového formuláře

### ISSUE THREAD

**Issue by jindrich-oukropec** [cesko-digital/web#272]
Pro lepší přehlednost potřebujeme rozdělit stávající formulář na join.cesko.digital do více kroků.

### Základní info

- Stávající formulář rozdělit do tří kroků.
- Souhlas se zpracováním os. údajů (viz #30) hned do kroku č. 1, pod email.
- Poslední (3.) krok bude nyní sloužit k rekapitulaci zvolených dovedností a později vysvětlení a zaškrtnutí "Zpracovatelských podmínek".
- Na 3. kroku dojde k odeslání (musí se deaktivovat přechody a tlačítka) a poté zobrazení potvrzení + přesměrování na registraci do Slacku.

Technologie: React, TypeScript, Gatsby

### Požadavky na výsledné řešení:

- Používáme stejný stack a pravidla jako web cesko.digital.
- Texty/lokalizace pro komponenty jsou v [/content/](https://github.com/cesko-digital/join.cesko.digital/tree/main/content)
- Desktop i mobilní verze, viz níže.

### Náhled komponenty

<img width="692" alt="obrazek" src="https://user-images.githubusercontent.com/69157075/116421028-c9157f00-a83e-11eb-8981-e95245d56f4f.png">

### Aktuální verze

Návrh komponenty je ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=2088%3A256).
Mock celého formuláře [je ve Figmě](https://www.figma.com/proto/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=2088%3A3&viewport=-6491%2C690%2C0.31648677587509155&scaling=scale-down-width) a stejně tak [i verze pro mobily.](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=2601%3A22151)

V případě nejasností se neboj zeptat zde pod issue nebo na Slacku v [#run-ceskodigital_onboarding](https://cesko-digital.slack.com/archives/C019JAJJS02) jednoho z techleadů v [#run-ceskodigital_web](https://cesko-digital.slack.com/archives/CHG9NA23D). Jeden z nich ti bude k dispozici po celou dobu vývoje. 🙂

[samostatná stránka - rekapitulace po odeslání formu #9 ](https://github.com/cesko-digital/join.cesko.digital/issues/9)

**Comment by zoul** [comment]
Tohle nám vyhnilo, aktuální představa je jiná (chceme formulář spíš zjednodušit), takže zavírám.
