### ISSUE TITLE
Implementace komponenty souhlasu

### ISSUE THREAD

**Issue by jindrich-oukropec** [cesko-digital/web#273]
Jako součást formuláře potřebujeme doplnit souhlas se zpracováním osobních údajů a později možná i souhlas se zpracovatelskými podmínkami. Tuto komponentu zatím nemáme.
Jedná se o jednoduché zaškrtávátko s rozbalovacím detailem, viz níže.

### Základní info

Technologie: React, TypeScript, Gatsby

Požadavky na výsledné řešení:

- Používáme stejný stack a pravidla jako [web cesko.digital](https://github.com/cesko-digital/web/blob/rework/CONTRIBUTING.md)
- Texty pro komponenty jsou v [/content/](https://github.com/cesko-digital/join.cesko.digital/tree/main/content)

### Náhled komponenty
<img width="467" alt="obrazek" src="https://user-images.githubusercontent.com/69157075/116422791-6329f700-a840-11eb-9a8b-5ee8b520410e.png">
<img width="457" alt="obrazek" src="https://user-images.githubusercontent.com/69157075/116422828-6c1ac880-a840-11eb-9b0c-05e231c63fe3.png">

### Aktuální verze

Návrh komponenty je ve [Figmě](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=854%3A337) (jako součást jednokrokové verze).
Mock celého formuláře [je ve Figmě](https://www.figma.com/proto/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=2088%3A3&viewport=-6491%2C690%2C0.31648677587509155&scaling=scale-down-width) a stejně tak i [verze pro mobily.
](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/C.D-Web?node-id=2616%3A3711)

Komponenta bude umístěna v prvním kroku formuláře:
<img width="531" alt="obrazek" src="https://user-images.githubusercontent.com/69157075/116423069-a4220b80-a840-11eb-8396-26ac335fcb6b.png">

 případě nejasností se neboj zeptat zde pod issue nebo na Slacku v [#run-ceskodigital_onboarding](https://cesko-digital.slack.com/archives/C019JAJJS02) jednoho z techleadů v [#run-ceskodigital_web](https://cesko-digital.slack.com/archives/CHG9NA23D). Jeden z nich ti bude k dispozici po celou dobu vývoje. 🙂

**Comment by zoul** [comment]
Tohle podle mě vyhnilo, aktuální představa o tom formuláři je jiná – zavřu a kdyby bylo potřeba, vrátíme se k tomu.
