### ISSUE TITLE
Záznam o zaškrtnutí souhlasu v Airtable

### ISSUE THREAD

**Issue by jindrich-oukropec** [cesko-digital/web#274]
V databázi potřebujeme sledovat zaškrtnutí souhlasu (nyní se zpracováním os. údajů, později zpracovatelské podmínky a podobně).

V Airtable bude existovat nová tabulka s vazbou na dobrovolníka a datum/čas udělení souhlasu. Zároveň chceme sledovat verze (a texty) souhlasů. Návrh tabulky diskutovat s @radkoa nebo @zoul.

Pro ukládání souhlasu je třeba rozšířit [API](https://github.com/cesko-digital/join.cesko.digital/tree/main/api) a backend service.

**Comment by zoul** [comment]
Tohle myslím vyhnilo, aktuálně zavřu a v případě potřeby zase oživíme.
