### ISSUE TITLE
Import a sjednocení stacku repozitáře blogu

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#280]
- Využít stejné vizuální komponenty (hlavně pro layout)?
- TypeScript
- ESLint pravidla a GitHub Actions
- Netlify -> Vercel

Debata ohledně monorepo přístupu [zde](https://cesko-digital.slack.com/archives/CHG9NA23D/p1590766339377300). 

@zoul, tady bych rád slyšel tvůj input, co považuješ za nejvíce důležité a prioritní.

**Comment by zoul** [comment]
Ten přechod na Vercel je podle mě hezký quick-win, kde by neměly být žádné zádrhele. Dělal jsem to nedávno na našich novinách a jediný háček byla nastavení hlaviček a přesměrování – ale mám dojem, že nic z toho na blogu nepoužíváme?

**Comment by zoul** [comment]
S @karmi jsme se domluvili, že dál blog necháme v samostatném repu. Znamená to určitou duplikaci úsilí, ale zase díky tomu máme možnost „nedělat všechny změny najednou“, oddělit od sebe ty věci například přes API.
