### ISSUE TITLE
Chybí odkaz na Github

### ISSUE THREAD

**Issue by mormegil-cz** [cesko-digital/web#3]
Velký nápis „147 Commitů“ mě zaujal, chtěl jsem se na ně podívat. Jenže jsem nikde na webu nenašel odkaz na Github (nebo jakékoli jiné repository), který bych tam určitě někde čekal. (OK, OK, našel jsem ho i bez toho… snad.)

**Comment by woodarius** [comment]
@mormegil-cz díky za postřeh, na webu jsou již k dispozici odkazy na sociální sítě i github aktuálně na úvod stránky i v patičce. S dovolením uzavírám.
