### ISSUE TITLE
Lepší zobrazení seznamu rolí na mobilních zařízeních

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#358]
Na úzkých displejích nám název hledané pozice nehezky zajíždí do názvu projektu ([viz tady](https://cesko.digital/opportunities/)).

**Comment by dominikpatera** [comment]
Vytvořil jsem PR #541 s úpravou.

V návaznosti na toto zakládám issue #542.

_Je to můj první PR. :)_
