### ISSUE TITLE
Zobrazovat správné fotky rolí

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#363]
V detailu hledané role je vidět fotka ([viz příklad](https://cesko.digital/roles/recCYY7RdPge3XE4A)). Tahle fotka se „dědí“ z projektu, ke kterému role patří – ale taky je možné v Airtable nastavit vlastní fotku příležitosti. S tímhle web nepočítá, je potřeba to doprogramovat – tedy připsat property `Cover URL` při načítání typu `Event` z Airtable a dopsat zobrazovací logiku, která tenhle obrázek zobrazí v detailu příležitosti a taky přidá do SEO metadat (Open Graph). Property `Cover URL` je nepovinná, pokud hodnota chybí, bere se obrázek z projektu.

Lze vyzkoušet na té odkazované příležitosti, kde by se měla ukazovat [tato fotka](https://data.cesko.digital/img/b3d8565d.jpg), nikoliv fotka z projektu.

**Comment by l-korous** [comment]
Chci se ujistit: v textu píšeš ".. typu Event ..". Nemyslíš ".. typu Opportunity .."?

**Comment by l-korous** [comment]
udělal jsem předpoklad že to tak je a poslal PR :-)
