### ISSUE TITLE
Jako editor chci, aby event automaticky dědil náhledovou fotku svého projektu

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#374]
Pokud jdu založit událost projektu XY, chci, aby se automaticky načetl default obrázek projektu, než mi designéři vytvoří speciální cover photo události.

**Comment by l-korous** [comment]
@zoul - pokud správně rozumím zadání, tak je to tak už naimplementované: https://github.com/cesko-digital/web/blob/master/src/templates/event/index.tsx#L38

**Comment by zoul** [comment]
Máš pravdu! Toto bude nějaký brain fart, díky!
