### ISSUE TITLE
Jako uživatel chci v onboardingu vyplnit jen základní top-level kompetenci

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#378]
Momentálně nutíme uživatele na join.cesko.digital vyplňovat velmi podrobné kompetence, ale ve skutečnosti pak používáme hlavně hlavní top-level kompetence, takže je škoda nutit uživatele vyplňovat tak složitý formulář. Pojďme ho vykostit na ten základ, snížíme práh pro onboarding. [Popis a příklady Top-levelu zde](https://cesko-digital.atlassian.net/l/c/i9Ydj81L).

PS. Jako mezikrok můžeme aspoň v Airtable zavést automatické překládání těch podrobnějších kompetencí na základní sadu, [viz tenhle starší ticket v Jiře](https://cesko-digital.atlassian.net/browse/PD-120).

**Comment by kafkule** [comment]
@zoul můžeme nějak postrčit část 2, tedy ten mezikrok, kdy se podrobné kompetence poskládají pod Top-level a uvedou v tabulce dobrovolníků? Nyní provádíme pravidelně ručně, je tam velký prostor pro chyby, ale filtraci bychom chtěli využívat v rámci DOB pro nabídku relevantních příležitostí k zapojení. Díky 🙏🏻

**Comment by zoul** [comment]
Kačko, přidal jsem do tabulky Volunteers sloupec Obory, kde jsou ty top-level kompetence jako řetězec. Stačí to tak? Alternativně umím udělat, aby to zůstal výčet (barevné pilule), ale pak tam budou ty top-level kompetence duplicitně, za každý skill jednou – tedy například pro `Vývoj / JavaScript, Vývoj / HTML & CSS` tam bude `Dev, Dev`. Co je pro tebe lepší?

**Comment by kafkule** [comment]
Jsi báječnej! Podle mě bude lepší, když to nebude tak hezký, ale funkční, filtrovat se to dá, takže funkci to plní 🤝 Tzn. teď můžu ten ručně doplňovaný sloupec Top-level dát pryč.

**Comment by zoul** [comment]
Supr. Ano, ručně vyplňovaný sloupec s „oborem“ může přijít pryč, akorát tradičně bacha na věci, které na něj můžou být navázané (filtry a podobně).

**Comment by zoul** [comment]
Tohle momentálně řeší jiná část týmu a nejspíš to dopadne jinak, takže zavírám a počkáme, co přijde za nové zadání.
