### ISSUE TITLE
Jako editor chci mít snadnou možnost promítnout změny na web

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#382]
Změny v Airtable se nepromítají na web samy od sebe, je třeba přenasadit web. Jak to děláme aktuálně? Napadá mě jen redeploy ve Vercelu, což není hezké UX. Šel by udělat například Slack bot, že by šlo ve Slacku zadat /kubot deploy a přenasadil se web s aktuálními daty?

_Edit z budoucnosti_, co všechno je potřeba:

* [x] Slack bot pro přenasazení
* [x] Oznámit do týmu nové řešení
* [x] Zneplatnit starý deploy hook
* [x] Přijít na to, jak vyrobit asynchronní odpověď? (Viz níže.)
* [ ] Přehodit deploy službu z `cd-tools` sem
* [ ] Uměli bychom poslat odkaz přímo na dotyčný deploy log?
* [ ] Přidat autentizaci? Viz [signed secrets](https://api.slack.com/authentication/verifying-requests-from-slack).

**Comment by zoul** [comment]
Zkusil jsem udělat jednoduchého Slack bota, který přidá nový slash command `/deploy`, viz [Enabling interactivity with Slash Commands](https://api.slack.com/interactivity/slash-commands). Nastavení bota [tady](https://app.slack.com/app-settings/TG21XF887/A02NYQZK676/general). Když člověk příslušný příkaz zadá do Slacku, dostane zhruba tohle:

```
{"job":{"id":"AyGqx5Z1ERTtSVc5iS0g","state":"PENDING","createdAt":1638203572823}}
```

Tedy odpověď Vercelu na spuštění deploymentu. Kdybychom před to „magické URL“ pro spuštění deploymentu ještě vřadili malinkou službu, můžeme tu odpověď polidštit a ideálně v ní vrátit odkaz na probíhající deployment (je veřejný). Akorát nevím, jak ten odkaz z toho `id` výše odvodit. (CC @karmi)

**Comment by zoul** [comment]
Přihodil jsem jednoduchou službu do cd-tools (viz PR výše) a přehodil bota na ni. Teď už vrací hezčí hlášku:

```
Už to frčí, detaily tady: https://cesko.digital/_logs
```

Akorát by stejně bylo lepší vrátit odkaz přímo na konkrétní deploy, mám dojem, že tohle nefunguje stopro. Plus pokud budeme chtít, jde dodělat nějaká jednoduchá autentizace – viz [signed secrets](https://api.slack.com/authentication/verifying-requests-from-slack).

A až tohle dořešíme a zveřejníme nový proces, je potřeba [tady](https://vercel.com/ceskodigital/web/settings/git) zneplatnit ten předchozí hook a vyhodit ho z dokumentace v Airtable.

**Comment by zoul** [comment]
A ještě to občas hází:

```
/deploy failed with the error "operation_timeout"
```

Je možné, že se to nevejde to třísekundového okna, které nám Slack dává? Přinejhorším bychom nemuseli čekat na odpověď od Vercelu.

**Comment by zoul** [comment]
Ještě si hraju s tím stavem deploymentu – [je na to API](https://vercel.com/docs/rest-api#endpoints/deployments/get-a-deployment-by-id-or-url) a detaily o deploymentu bychom měli po autentizaci dostat z URL zhruba `https://api.vercel.com/v13/deployments/:id`, ale prakticky mně to nefunguje – tvrdí, že deployment s tímhle ID nezná. Navíc pokud nám Slack dá jen tři sekundy, stejně bysme to asi nestihli vyřídit. (Leda poslat víc zpráv, nevím, jak ten limit funguje.)

**Comment by zoul** [comment]
Zkoušel jsem vyřešit ten timeout tím, že bychom okamžitě poslali první odpověď (_Kontaktuji Vercel, moment…_) a finální potvrzení poslali až potom asynchronně (Slack nám skrz to posílá webhook `response_url`), ale nefunguje to – můj tip je, že jakmile Vercel uvidí, že funkce poslala odpověď, tak ju zařízne. Zkrátka to vypadá, že ten kód za první odpovědí už se vůbec neprovedl. Takže revert na původní verzi, pro případné zájemce o pokračování [je ten kód tady](https://github.com/cesko-digital/cd-tools/commit/9cf1ea756256c4040aeee58db07f0cd483d393f3).

**Comment by karmi** [comment]
Souhlas, jakmile se něco pošle v https://github.com/cesko-digital/cd-tools/blob/acdd091c85480c4e262f0f48a503646e4af02134/api/web_deploy.ts#L25, tak už se zbytek zařízne. Jestli dobře rozumím té flow, tak v tomto místě by se musela odpálit nějaká _jiná_ funkce, která by provedla to `await fetch(deploy_hook)`, a poslala pak zase odpověď do Slacku.

**Comment by zoul** [comment]
Karel našel [tuhle dobrou diskuzi](https://github.com/vercel/vercel/discussions/4314) k tomu ukončení provádění serverless funkce po odeslání odpovědi.

**Comment by karmi** [comment]
Věnovali jsme tomu dnes dopoledne se @zoul nějaký čas, a zdá se, že cesta rozdělit tu workflow do více Vercel funkcí je schůdná. Na správnou cestu nás navedl článek [_How to make “Fire-and-forget” HTTP request from Node.js without waiting for response_](https://yurigor.com/how-to-make-http-request-from-node-js-without-waiting-for-response/).

V této chvíli máme dvě funkce: `accept()`, která pouze přijme požadavek ze Slacku, zavolá druhou funkci `trigger()` bez čekání na odpověď, a vrátí odpověď do Slacku.

Nasimulovali jsme dlouhý běh funkce `trigger()` pomocí `sleep(5)` a ověřili, že `accept()` v tomto případě vrátí odpověď ihned, a mezitím běží funkce `trigger()` — viz screenshot:

<img width="1074" alt="accept-trigger" src="https://user-images.githubusercontent.com/4790/144053254-377f1174-db63-44f5-8403-1ae6c163546e.png">

Možno vyzkoušet příkazem:

```
curl -i -d 'response_url=https://en9m76f14989s.x.pipedream.net' https://cd-tools-hi2xaiwny-ceskodigital.vercel.app/api/web_deploy/accept
```

Kód je v branchi [**`feature/async-deploy`**](https://github.com/cesko-digital/cd-tools/tree/feature/async-deploy/api/web_deploy).

**Comment by zoul** [comment]
BTW nevím, proč jsem ten deploy skript dal do `cd-tools`, je logičtější ho mít přímo tady, přidám do seznamu nahoře jeho přestěhování.

**Comment by karmi** [comment]
Pull request s vylepšenou funkcionalitou: https://github.com/cesko-digital/cd-tools/pull/16.

**Comment by karmi** [comment]
Tohle jsme už nasadili, chceme ještě přehodit ty skripty sem do repo, než to zavřeme?

**Comment by zoul** [comment]
Jo, já bych to přestěhoval, případně při té přiležitosti přidám tu autentizaci. Udělám.

**Comment by zoul** [comment]
Dlouhodobě směřujeme k tomu, že se web bude aktualizovat automaticky, viz #623, takže tohle už myslím nebude potřeba a až si lidi zvyknou na automaticky aktualizovaný web, můžeme robota na přenasazování webu uvolnit ze služby.
