### ISSUE TITLE
Na detailu příležitosti odkaz na projekt v pravé bublině pod fotkou nevede na stránku projektu

### ISSUE THREAD

**Issue by l-korous** [cesko-digital/web#408]

**Comment by zoul** [comment]
Ha, máš pravdu, je to 404, díky! O co jde – máme některé projekty v databázi označené jako „interní“, což znamená, že se neukazujou v přehledu projektů ([/projekty](https://cesko.digital/projekty/)). A tím pádem by tyhle projekty ani neměly být klikací, viz třeba jako [tady u eventu](https://next.cesko.digital/events/skvely-scrum-master). Takže je potřeba upravit detail příležitosti, aby u projektů s nastaveným příznakem `.silent` nebyl klikací název projektu. Nechceš si to zkusit?

PS. Výhledově chceme mít všechny projekty veřejné, takže tohle rozlišování časem úplně zmizí.

**Comment by zoul** [comment]
Aha, a teď se chystám přidat štítek `Next.js` a koukám, že hlásíš chybu na produkci, zatímco já jsem vyrobil _jinou_ chybu na stejném místě v přepsané verzi webu 😀 Nechceš si to teda zkusit opravit na `next`?

**Comment by l-korous** [comment]
Mrknu na to, jasně ;-). Na next branchi tedy

**Comment by l-korous** [comment]
@zoul  - mrkni na PR prosím, bylo to tak triviální jak jsi psal.

Ještě jsem během toho udělal další dva PR s drobnostmi. Až mergneme next do masteru, tak zkusím mrknout na nějaké větší, složitější věci.
