### ISSUE TITLE
Dořešit rendering Markdownu

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#419]
Pro rendering textu byla v dřívější verzi webu zavedena komponenta `Body`:

```html
<Heading2>Hello, world!</Heading2>
<Body>Lorem gypsum…</Body>
```

Když jsme přidávali podporu Markdownu, dopadlo to teď nějak takhle:

```html
<Heading2>Hello, world!</Heading2>
<Body><RenderMarkdown source="…"/></Body>
```

Potíž je v tom, že komponenta `Body` je vlastně stylovaný odstavec. A Markdown v principu může vést a často vede na několik odstavců, takže teď generujeme odstavce uvnitř odstavců. Zároveň jsou ale na `Body` navázané nějaké styly, které potřebujeme. Takže bychom chtěli například udělat nějakou kopii `Body`, co dělá `div`?

**Comment by karmi** [comment]
> Takže bychom chtěli například udělat nějakou kopii Body, co dělá div?

Souhlasím, přijde mi to nejmíň invazivní řešení.

Takže ponecháme definici zde,

https://github.com/cesko-digital/web/blob/b81564554ba495de804b1bdca627678113ef4f11/components/typography/body/index.ts#L31

ať nemusíme přejmenovávat a refaktorovat 90% kódu, a přidáme něco jako `MarkdownBody`? (Chápu, že Markdown je tady akcidentální, chceme prostě `<div>` místo `<p>`, ale myslím, že to bude v kódu srozumitelnější a čitelnější než něco jako `DivBody`, `BlockBody`, atd?)

**Comment by zoul** [comment]
Vyřešeno v rámci #930.
