### ISSUE TITLE
Lepší řešení analytických cookies

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#421]
Od roku 2022 platí [přísnější pravidla pro analytické cookies](https://www.uoou.cz/cookies-od-zacatku-roku-2022-pouze-se-souhlasem/d-53646), které nově smí být jen opt-in. Máme v zásadě dvě možnosti – buď přidat nějaké UI pro souhlas s ukládáním cookies, anebo přejít na analytiku, která se obejde bez cookies (například Plausible.io). Preferuju to druhé, ještě to musíme probrat ([vlákno na Slacku](https://cesko-digital.slack.com/archives/CHG9NA23D/p1641195421235400)).

**Comment by zoul** [comment]
Shrnu výhody a nevýhody:

## Plausible Analytics

✅ Nevyžaduje cookie consent
✅ Jednodušší UI
✅ Open source projekt, viz [plausible/analytics](http://github.com/plausible/analytics)
✅ Je možno si hostovat
✅ Větší respekt k soukromí návštěvníků
❌ Hostovaná verze je placená (zhruba $120 do 100 K pageviews měsíčně)

## Google Analytics

✅ Standardní řešení, které všichni znají
✅ Zdarma
❌ Vyžaduje cookie consent
❌ Uzavřené řešení
❌ Menší respekt k soukromí návštěvníků
❌ Horší UI

**Comment by zoul** [comment]
Probíral jsem s @karmi a je tu ještě zajímavé třetí řešení – ořezat Google Analytics tak, aby se daly nasadit i bez souhlasu s cookies. Otázka je, jestli je to právě košer. Plausible k tomu má [podrobnější text](https://plausible.io/blog/google-analytics-cookies).

**Comment by karmi** [comment]
Diskutovali jsme to poměrně obsáhle se @zoul, a já jsem si k tomu dělal nějaké další řešerše. Chtěl bych v rámci tohoto issue shrnout všechny informace a možnosti řešení, abychom o nich mohli dále diskutovat a rozhodnout se.

Důležitá poznámka pro začátek je, že problém se **netýká jen „Google Analytics“**, ale všech sledovacích cookie např. od Facebooku, LinkedIn, vložených videí z YouTube, atd.

Velice dobrý úvod do problematiky obsahuje článek Martina Michálka [_„Cookie lišta, verze 2022“_](https://www.vzhurudolu.cz/prirucka/cookie-lista-2022). (Rozsáhlejší informace např. ve [webináři _„Jak na cookie lištu v roce 2022“_](https://www.youtube.com/watch?v=mvMyEVr_kMg).)

### Stávající stav

Stávající web není v souladu s aktualizovanou úpravou, kterou @zoul odkazuje výše. Ukládáme nejen cookies pro Google Analytics, ale i cookies pro např. Facebook nebo LinkedIn. Podle [analýzy od Cookiebot]((https://github.com/cesko-digital/web/files/7883235/report-ceskodigital-9239801.pdf)) ukládáme též cookies pro Snowplow Analytics, což je pravděpodobně nějaký historický relikt (?).

### Možnosti řešení

Jednou z možností je implementovat plně funkční „cookie lištu”, a souhlas s ukládáním tak řešit zcela technicky. Toto řešení má zjevnou nevýhodu, že je _dost_ implementačně náročné, pokud nepoužijeme nějaké hotové řešení od třetí strany. (Je třeba řešit souhlasy pro různé typy dat, podle toho upravit kód ve stránce, mít odkaz na kompletní podmínky použití, formulář pro odvolání souhlasu, a mnoho dalších věcí). Osobně si myslím, že takové těžkotonážní řešení je pro nás zbytečné, a můžeme se bez něj obejít.

Pokud „cookie lištu” implementovat nebudeme, musíme změnit nastavení jednotlivých služeb (zejména Google Analytics), některé odstranit, případně některé služby vyměnit za alternativní.

#### Google Analytics

Nejdůležitější službou je Google Analytics pro měření návštěvnosti webu. Podle informací, které se v poslední době objevily, je možné pomocí nastavení pro Google Tag Manager vypnout sledování uživatele, a tedy i ukládání sledovacích cookie. Detaily v [přednášce](https://www.youtube.com/watch?v=KW7lNaLfu9c) od Martina Koláře. Tato varianta mi přijde schůdná, a rozhodně krok správným směrem. Důsledkem je méně přesné měření návštěvnosti, a nedostupnost určitých funkcí Google Analytics, ale to je logickým důsledkem odstranění trvalých sledovacích cookies. Za sebe bych začal zde.

Druhou variantou je využití jiného nástroje, jako např. Plausible, zmíněného výše. Zjevnou nevýhodou je nedostupnost historických dat, protože Plausible [zatím neumožňuje jejich import](https://github.com/plausible/analytics/discussions/211#discussioncomment-1923222). Navrhuji podle zpětné vazby marketingového týmu vyzkoušet Plausible (v self-hosted verzi) a vyhodnotit přínos a limitace.

#### Facebook

Využíváme nějak aktivně integraci s Facebookem? Navrhuji odstranit, pokud to není nějaká důležitá součást marketingových aktivit.


#### LinkedIn

Podobně jako v případě Facebooku navrhuji odstranit.

#### Snowplow Analytics

Odhaduji, že v tomto případě se jedná o nějaký historický relikt, který můžeme odstranit?

#### Vložená YouTube videa

Podle [oficiálních instrukcí Google](https://support.google.com/youtube/answer/171780?hl=en#zippy=%2Cturn-on-privacy-enhanced-mode) lze video vložit v tzv. _Privacy Enhanced Mode_, kdy jsou hostována z domény https://www.youtube-nocookie.com a nenastavují cookies. Je třeba buď: a) použít tuto volbu při kopírování „embed code“ na YouTube, b) manuálně přepsat doménu, c) nějakým post-procesorem URL nahrazovat. Jsem za manuální řešení.

#### Vložené příspěvky z Twitteru

Podle [oficiálních instrukcí Twitteru](https://developer.twitter.com/en/docs/twitter-for-websites/privacy) lze zapnout volbu _Do not track_ v HTML stránky, což doporučuji udělat.

### Vložené příspěvky z Facebooku

Nenašel jsem způsob, jak u vložených příspěvků z Facebooku vypnout sledování, proto bych se jim vyhýbal, a na příspěvky pouze odkazoval.


---

Přílohy:

[cookiebot-report-ceskodigital.pdf](https://github.com/cesko-digital/web/files/7883235/report-ceskodigital-9239801.pdf)

**Comment by zoul** [comment]
Hm, po mergi nelogujem do Analytics 💩, revertnu to a vrátím se k tomu po víkendu.

**Comment by karmi** [comment]
Já mám strach, že ten GTM takhle opravdu funguje — bylo to tuším v tom [článku](https://www.vzhurudolu.cz/prirucka/cookieless#ga) od Martina Michálka:

> Pozor, toto řešení je vhodné jen pro verzi Universal Analytics (identifikační řetězec začíná UA-). Novější Google Analytics 4 sice do režimu „neukládej lokálně“ přepnete taky, ale bohužel pak v rozhraní nevidíte žádná data. Prý se ukládají, ale nezobrazují.

Napadá mně: nešlo by mít obojí, tzn. jak "staré" Google Analytics (`UA-xxx`), které budou bez cookies měřit základní věci, tak "nové" (`GTM-xxx`), které jsou potřeba pro Google Ads? (Samozřejmě ponecháme Plausible.)

**Comment by zoul** [comment]
My AFAIK používáme ty starší Analytics. Prase aby se v tom vyznalo. Rozdělím to aspoň na dva PR, ať to zbytečně nestojí – první s Plausible a přechodem na nový GTM účet, druhý pak, až dostuduju, jak vypnout cookies pro GA.

**Comment by zoul** [comment]
Vyřešeno v a41c7858a857ee8d7d82d0593cb43e6554d5c692.
