### ISSUE TITLE
Předfiltrovat data z Airtable

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#422]
Momentálně čteme z Airtable data z hlavních pohledů, kde může být řada nehotových nebo už starých, historických dat. Nebylo by dobré zavést pro API samostatný pohled (například „API“), kam budeme pouštět jen přiměřeně validní a aktuální řádky?

**Comment by zoul** [comment]
Tohle by mimo jiné zmenšilo objem dat posílaných na klienta, momentálně je to skoro 200 KB a Next [nám píše](https://nextjs.org/docs/messages/large-page-data), že už je to hodně. (Tady by ale taky pomohlo agresivněji filtrovat už v `getStaticProps`.)

**Comment by karmi** [comment]
Určitě to stojí za pozornost. Napadá mně k tomu pár věcí:

* Umíme definovat, jak bychom chtěli data profiltrovat a kterých tabulek se to týká?
* Obecně si myslím, že je efektivnější filtrovat data při načítání během sestavování webu? Je to jednodušší na implementaci než vytvářet pohledy v Airtable? Nyní např. odstraňujeme projekty ve stavu `draft`: https://github.com/cesko-digital/web/blob/821883e80eedbf37ed393b72587c1eb3d69ec163/pages/projekty/index.tsx#L55
* Tím, že se data ukládají v JSON a pak "rehydrují" na klientovi, určitě bychom měli co nejvíce snížit jejich objem.

**Comment by zoul** [comment]
My dokážeme ta data dobře filtrovat během načítání webu, jak píšeš. Ale filtrování už v Airtable má dvě výhody:

* Mohli bychom předfiltrovat například staré, nerelevantní entity, například měsíce staré události, aniž bysme je museli mazat nebo všechny cpát do API.
* Filtrování by mohlo dělat jednoduchou předběžnou validaci, která momentálně není moc srozumitelná pro uživatele. Pokud například v řádku chybí hodnota povinného sloupce, dotyčnou entitu zahodíme na klientovi a napíšeme o tom do logu. Kdyby místo toho řádek chyběl v nějakém pohledu, uživatelé budou líp vědět, co se děje. (V ideálním případě Airtable v dohledné době zavede lepší možnost validace a tahle zpětná vazba půjde udělat hezky interaktivně přímo v Airtable Interfaces.)
