### ISSUE TITLE
Zjednodušit modelování stavu projektů

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#428]
Aktuálně modelujeme stav projektu pomocí třech booleanů: `draft`, `silent`, `finished`. Navzájem se trochu překrývají a nepokrývají všechno, co potřebujeme, pojďme místo toho zavést výčet `draft | incubation | running | finished`. Přičemž `draft` se nebude ukazovat veřejně, ale pouze se vygenerují příslušné stránky – a případně můžeme nahodit samostatné URL (třeba draft.cesko.digital), kde budou zobrazené i všechny `draft` položky (nejen projekty).

**Comment by karmi** [comment]
Podle dohody se zbytkem týmu zavedeme tyto možnosti pro stav projektu:

* `finished` — ukončené projekty
* `running` — aktuálně realizované projekty
* `incubating` — projekty v přípravě k realizaci
* `internal` — interní projekty organizace (č.edu, příručka, ...), zatím nezobrazujeme v seznamu projektů
* `draft` — projekty schválené k realizaci a připravované ke zveřejnění, zobrazujeme pouze na náhledové verzi webu

Technicky provedeme tak, že nejprve implementujeme podporu pro tyto možnosti v kódu, posléze aktualizujeme Airtable.
