### ISSUE TITLE
Sjednotit jazyky v routách

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#434]
Máme například `/projekty/foo`, ale `/opportunities` nebo `/events`. Pojďme to sjednotit do češtiny. Bude potřeba nastavit přesměrování z původních URLs, aby nám nepřestala fungovat.

**Comment by zoul** [comment]
Co je potřeba:

* [ ] /partners → /partneri
* [ ] /opportunities → /role + /opportunities/:id → /role/:id
* [ ] /events → /akce + /events/:id → /akce/:id

**Comment by karmi** [comment]
Když o tom přemýšlím, říkám si, jestli by nebylo lepší mít všechny cesty v angličtině místo v češtině? Samozřejmě tím pádem vznikne problém, jak nazvat „Portál dobrovolníka“, pokud nezvolíme ambiciózní `dashboard` :)

**Comment by zoul** [comment]
Lukáši, pardon, tohle jsme si mohli vyjasnit, než ses do toho pustil. Ale aspoň to můžem probrat všichni tři :)

Karle, vidíš v té angličtině nějaké konkrétní výhody, anebo je to pocitovka? (Na té druhé variantě není vůbec nic špatného :)

Moje poznámky:

* Anglické cesty v české verzi by nám případně komplikovaly lokalizaci celého webu, kterou ale v dohledné době určitě nebudeme dělat.
* Nevím, jestli by české cesty neudělaly drobný SEO bonus? Asi to není podstatný efekt.
* Přejmenování cesty pro Portál dobrovolníka za mě určitě možno, rád bych časem upozadil celý ten název. (Vnímám ho spíš jako název projektu uvnitř č.d, ale zvenčí je vlastně portál dobrovolníka tak trochu celé Česko.Digital…) Kdyby to mělo být anglicky, `dashboard` je za mě dobrý, případně se mně líbí výraz `volunteer-hub`.

Nemám na to celkově velké názory. Kdyby to bylo anglicky, musíme akorát ještě přehodit `/projekty` a `/projekty/:id`.

**Comment by l-korous** [comment]
Jasně, to já se do toho pustil vyloženě na vlastní pěst, protože se mi nelíbí když věci nejsou dělané stejně. Zvažoval jsem všechny v angličtině a všechny v češtině.

V angličtině je to poplatné tomu jak je web nakóděný (máme všechno anglicky, tedy dává smysl mít i názvy složek, a tím tedy stránek díky nextu). A samozřejmě tomu že je to profesionálně nakóděný web, a tady souhlasím že v naší branži prostě technická vrstva je a má být anglicky.

V češtině je to poplatné ale podle mě celé ideologii česko.digital, je to práce českých lidí na českých projektech pro česko a v češtině :-).

Klidně řekněte, předělám https://github.com/cesko-digital/web/pull/410 na anglickou verzi, a nebo to klidně zahodíme - jsou určitě podstatnější věci.

**Comment by karmi** [comment]
> Karle, vidíš v té angličtině nějaké konkrétní výhody, anebo je to pocitovka? 

Je to pocitovka, respektive instinkt. Ale především jsem chtěl otevřít diskusi nad oběma možnostmi. Když to zkusím více rozvést, moje preference angličtiny vychází zhruba takto:

* Vnímám URL jako „technickou vrstvu“, slovy @l-korous výše, a tam mi přijde adekvátní použít angličtinu. 

* Jeden z důvodů je jednodušší mapování mezi kódem (názvy komponent, proměnných, atd) na URL. 

* Druhým důvodem je nutnost vymýšlet české alternativy, což někdy bývá dost krkolomné, a někdy z toho vznikají zbytečné nekonzistence. Např. u `opportunities` máme v návrhu nové URL české slovo `role`, web tu stránku ale popisuje jako _Volné pozice_. A tím pádem okamžitě vzniká otázka, jestli máme tedy použít `volne-pozice` místo `role`, apod. Interně, v diskusích o portálu, přitom mluvíme o „příležitostech”, tedy překládáme _opportunity_. Z toho mi vychází, že použít přímo `opportunity` je nejjednodušší.

> V češtině je to poplatné ale podle mě celé ideologii česko.digital, je to práce českých lidí na českých projektech pro česko a v češtině :-)

To je samozřejmě relevantní argument, a asi se všichni shodneme, že se chceme vyhnout používání angličtiny a anglicismům, jak jen je to možné. Ale „instinktivně” u mně převažují ty aspekty, které popisuju výše.

**Comment by zoul** [comment]
Tak jo, dobře, udělejme to anglicky. Shrnu:

* [ ] /projekty → /projects + /projekty/:id → /projects/:id
* [ ] /portal-dobrovolnika na /hub nebo /dashboard, co preferujete?

V obou případech je potřeba přidat přesměrování pro ta stará URLs, aspoň na pár týdnů.

**Comment by zoul** [comment]
Přesměrování není problém nechat, je to pár řádků ve `vercel.json`. Tak do URL zatím dáme `dashboard` jako takovou neutrální variantu a jak se nám to usadí, můžem zase pošoupnout? Přijde mně, že tím nic nezkazíme.

**Comment by karmi** [comment]
> Tak do URL zatím dáme dashboard jako takovou neutrální variantu a jak se nám to usadí, můžem zase pošoupnout?

OK, domluveno! Přinejhorším prostě jen přidáme další přesměrování :)

**Comment by l-korous** [comment]
Tak mrkněte, mělo by to v https://github.com/cesko-digital/web/pull/410 být.

**Comment by karmi** [comment]
Moc díky, @l-korous ! Koukal jsem na kód i proklikal preview, a přijde mi vše v pořádku.
