### ISSUE TITLE
Jako editor chci náhledovou verzi webu, abych mohl ladit data před veřejným vydáním

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#436]
Základní představa je mít něco jako draft.cesko.digital, kde budou i data z databáze označená jako `draft`. Něco podobného jsme už dřív měli a dokonce se to díky hooku z Airtable samo přenasazovalo – což zní rozumně, jinak bychom museli taky řešit přenasazování.

Technicky by bylo ideální, kdybychom mohli `draft` data filtrovat už při načítání dat, tj. aby to nemusela řešit každá komponenta zvlášť. Taky je potřeba pamatovat na „tranzitivní závislosti“, například odfiltrovat veškerá data související s `draft` projekty? Nebo jak s nimi pracovat?

**Comment by karmi** [comment]
Ve Vercelu jsem objevil https://vercel.com/ceskodigital/web-preview — je to ta minulá verze? V rámci vylepšené workflow pro draft/preview bychom měli upravit [dokumentaci ve wiki](https://cesko-digital.atlassian.net/wiki/spaces/CD/pages/87471811/Jak+zad+vat+data+na+web?pageId=87471811)

**Comment by zoul** [comment]
Jo, to je přesně ono. Průběžné TODO:

* [ ] Nahodit zase náhledový deployment (draft.cesko.digital / next.cesko.digital / preview.cesko.digital)
* [ ] Rebuild náhledu přes webhook z Airtable po změnách
* [ ] Předávání nějakého příznaku, přes který se pozná náhledová verze
* [ ] Podmíněné vkládání analytiky, abychom si nešlapali po SEO
* [ ] Načítání odlišných dat v náhledové a produkční verzi

**Comment by zoul** [comment]
Rebuild se spustí z Airtable pomocí jejich automations při změnách v tabulkách Projects, Events, Opportunities. Nevím, jestli se to vztahuje i na nové nebo smazané řádky, uvidíme.

**Comment by zoul** [comment]
Ještě poznámka k odlišení náhledové verze. Vercel rozlišuje tři prostředí: Production, Preview a Development. Production je build z masteru, preview je build z jiných větví (například PRs) a Development je lokální build (například `vercel dev`). My tady ale zároveň mluvíme o trochu jiné „náhledové verzi webu“, z pohledu Vercelu je nový build projektu `web-draft` normální produkční build. Takže bude potřeba tohle nějak rozlišit, ať v tom nemáme guláš.

**Comment by zoul** [comment]
Jajky, teď nám to blbě chodí na produkci, odladím.

**Comment by zoul** [comment]
Zatím mně není jasné, proč to na produkci nefunguje, tak jsem force-pushnul nazpátek na funkční verzi a doladím to odpoledne; teď musím na chvilku pryč.

**Comment by zoul** [comment]
Shrnu to tady, ať si to ujasním:

* Běžné komponenty běží na serveru (první render ze strany Next) i na klientovi. Bylo by ideální je držet co nejvíc v režimu „functional core“, tedy bez čtení nebo zapisování dat nějakými postranními kanály. Zejména je tedy volovina v nich číst nějaké proměnné prostředí, aspoň pokud se to výslovně netýká jen toho běhu na serveru. Ideální číst data pouze přes props.
* Ty dva světy se potkávají v `pages`, kde zejména `getStaticProps` běží výhradně na serveru během prvního renderu.
* „Čisté“ řešení našeho problému by bylo parametrizovat komponentu pro hlavičky pomocí props (`allowAnalytics`, `allowRobots`), což je ale volovina, protože by každá stránka musela tyhle parametry ručně předávat z `getStaticProps`.
* Takže hledáme nějaký elegantní způsob, jak předat build-time parametry. Technicky k tomuhle slouží třeba React Contexts, ale my potřebujeme nastavit výchozí kontext.

Dneska už mně došel čas, zítra se k tomu vrátím.

**Comment by zoul** [comment]
Domluvili jsme se, že tohle dáme dočasně k ledu. Chceme počkat na to, až bude k dispozici přihlašování přes Slack, a pak bude možné implementovat náhledovou verzi webu pomocí přepínače na klientovi – který jednak zařídí zobrazení draft dat, jednak by mohl zařídit i přímý přístup do databáze, aby uživatelé nemuseli čekat, až se jim web přenasadí.

**Comment by zoul** [comment]
Myslím, že tohle nikdo aktuálně nepoptává, nebojím se to zahodit.
