### ISSUE TITLE
Jako uživatel chci u projektu vidět relevantní příspěvky z blogu č.d

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#445]
Viz též #444 (související akce) a #440 (související role). K tomuhle aktuálně myslím nemáme data, ale prozačátek by nám nevadilo to hacknout nějak jednoduše, klidně i statickým seznamem relevantních blogových příspěvků tady v repu. Už takhle řešíme blogové příspěvky pro partnery, viz `partner-posts.json` – tak by to šlo trochu zobecnit a na základě toho pak formulovat nějaký feature request na kód blogu, abysme to propojili automaticky. (Z kódu těch partnerských příspěvků na blogu nejspíš lze obšlehnout komponenty.)

**Comment by zoul** [comment]
(Ale když nad tím přemýšlím, možná by bylo zrovna jednodušší dodat tagy do kódu blogu a vystavit u něj nějaké triviální API podobné tomu souboru `partner-posts.json`, kde budou ty tagy vidět.)

**Comment by karmi** [comment]
Souhlas, tohle by bylo fajn, abychom propojili projekty s ostatními zdroji. Přijde mi lepší ta automatizovaná cesta přes API. Ty tagy bychom dodali do _front matter_ u každého příspěvku (`content/posts/...`)?

**Comment by zoul** [comment]
Přesně tak. Akorát je potřeba zjistit, jak z toho Gatsbyho vyrazit nějaké statické API. Mrknu na to.

**Comment by karmi** [comment]
> Akorát je potřeba zjistit, jak z toho Gatsbyho vyrazit nějaké statické API.

Možná jenom v rámci `build` kroku ty data posbírat, a vyexportovat jako statický JSON? Ten už se pak jen natáhne.

**Comment by zoul** [comment]
Přesně tak. Akorát v tom Gatsbym je to pro mě trochu… bolest, takže možná napíšu tu API funkci bokem (pro nasazení do Vercel Serverless), je to pár řádků kódu a nechci na tom pálit čas přetahováním s Gatsbym.
