### ISSUE TITLE
Udělat jednou denně build na Windows

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#447]
Měli jsme nějaké problémy s buildem na Windows. Přidal jsem do CI buildy pro Windows, abychom měli jistotu, že se to na nich správně sestaví – ale zase je asi volovina to zkoušet u každého pull requestu, zbytečně to zdržuje. Co kdybychom udělali build pro Windows jednou denně v noci? Je to menší procesní zátěž a když se to rozbije, dozvíme se o tom (byť s mírným zpožděním).

**Comment by karmi** [comment]
> Co kdybychom udělali build pro Windows jednou denně v noci?

Já myslím, že je to užitečné a přijatelný kompromis!

**Comment by zoul** [comment]
[Tohle je hotové](https://github.com/cesko-digital/web/runs/4963367623?check_suite_focus=true), build pojede každý den o půlnoci a je možné ho taky spustit ručně.

**Comment by karmi** [comment]
Skvělý, díky moc!!
