### ISSUE TITLE
Rozbitý mobilní layout titulky

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#448]
Vyhřezla nám ta mapka:

![image](https://user-images.githubusercontent.com/95329/149763680-67addc25-cf2c-4b87-9052-4e98c8cae7fb.png)

**Comment by karmi** [comment]
Tohle se děje kvůli chybnému nastavení meta hlavičky `viewport` — musí obsahovat `width=device-width, minimum-scale=1, initial-scale=1, viewport-fit=cover`.

**Comment by zoul** [comment]
Supr, díky. Tak to bude regrese po přechodu na Next.js, viewport upravím ASAP.

**Comment by zoul** [comment]
Tohle ještě zlobí – úvodní pohled je OK, ale vidím vodorovný scrollbar, a to bych neměl.

**Comment by zoul** [comment]
Mrška jedna!

**Comment by karmi** [comment]
Closed via https://github.com/cesko-digital/web/commit/9b599f1cfce30ed0ac496f2146b19bdfa0d4d285 and https://github.com/cesko-digital/web/commit/98d19448575dd7f57f5721d952c709e4a722303a.

**Comment by karmi** [comment]
Stránka _Partneři_ je sice opravena, ale scrollbar máme stále, otvírám issue.

**Comment by karmi** [comment]
Poněkud krkolomně :) opraveno, ale už je na produkci.
