### ISSUE TITLE
Upravit stránku Partneři

### ISSUE THREAD

**Issue by karmi** [cesko-digital/web#449]
V souvislosti s přidáním nového partnera k 24. 1. chceme provést další úpravy na stránce. Podklady připraví @TerezaGagnon001.

**Comment by TerezaGagnon001** [comment]
Partneři > Pomáhejte s námi! 

Děkujeme všem našim dárcům, díky kterým tu můžeme být s Vámi a měnit Česko k lepšímu. Chytrým nasazením digitálních technologií můžeme zjednodušit a zlepšit fungování společnosti. Česká republika má nejlepší předpoklady k tomu, aby byla digitálním premiantem – a zatím není. Pomozte nám to změnit!

Finanční podpora a pomoc přicházejí z mnoha směrů. Od velkých partnerství po jednotlivce. Každá podpora má smysl a dopad na naši práci. 

Hlavní finanční partneři

Sdílíme společnou vizi, kde technologie slouží lidem bez ohledu na čas, místo nebo společenské postavení. Podporujeme inovace v neziskových projektech společně s našimi partnery, pro které je společensky odpovědné chování součástí DNA.

Livesport Bakala Nadace PPF Avast Foundation 

Dárci a sponzoři
Naše úsilí podporují i menší partneři, kteří nás udržují v běhu. Pomáhají a podporují společný směr. Jejich stopy se mohou zdát menší, ale vliv a dopad je velký. Děkujeme za každý společný krok.

Individuální dárci
Různorodá finanční energie, která k nám putuje, například přes platformu Darujme, ukazuje sílu drobného skutku. I malý čin dokáže zázraky. Jsme nezávislá nezisková organizace s transparentním hospodařením (link https://www.rb.cz/povinne-zverejnovane-informace/transparentni-ucty?path=transactions&accountNumber=1113331177). Každý váš dar pomůže efektivněji zapojit dobrovolníky pracující na digitalizaci naší společnosti. Děkujeme, že vidíte smysl v naši práci.

Jména dárců... 

Zobrazit sbírku 

![Avast_Foundation_Stacked](https://user-images.githubusercontent.com/94385954/150763173-01ce188e-3eda-40bc-aa97-4ea858d011ac.jpg)
<img width="619" alt="Individuální darci čd" src="https://user-images.githubusercontent.com/94385954/150763213-2ea33c38-f783-458a-ba28-c42c2ebddb5e.png">

**Comment by karmi** [comment]
@TerezaGagnon001 , přemýšlím, jestli tohle issue:

1. Zavřít a vyrobit si nové na další úpravy
2. Přehodit do dalšího release na únor
3. Zrevidovat v pondělí 31. 1. a uzavřít

Co je nejlepší?
