### ISSUE TITLE
Mezera na konci stránky Partneři

### ISSUE THREAD

**Issue by jindrich-oukropec** [cesko-digital/web#452]
Dle diskuse na [Slacku](https://cesko-digital.slack.com/archives/CSXGU7F0F/p1640281118324900?thread_ts=1640031485.276100&cid=CSXGU7F0F) dávám i sem: za emailem u stránky partneři bych jako poslední informaci před zápatím čekal větší mezeru

Nyní se email partneri@cesko.digital docela dost mačka na zápatí.

**Comment by karmi** [comment]
Díky za report, opraveno!
