### ISSUE TITLE
Rozbité menu ve variantě pro tablety

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#459]
Menu zajíždí pod tlačítka:

![sshot](https://user-images.githubusercontent.com/95329/150346812-f4f43501-bce4-400f-b192-712355732b9a.png)

**Comment by karmi** [comment]
Opraveno v linkovaném PR:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4790/151200559-6ca84653-f457-484d-aa81-48fbca4412d5.png">
