### ISSUE TITLE
U anglické verze jsou české texty ve footeru

### ISSUE THREAD

**Issue by l-korous** [cesko-digital/web#467]
https://cesko.digital/en

**Comment by jejdacz** [comment]
Ahoj,
rád bych přispěl vašemu projektu a tak jsem se mrknul na toto issue.
Provádění úprav ,které se mi pořád nezdály dost dobře vyřešené mě přivedlo k vestavěné funkcionalitě v NEXT.js "Internationalized Routing". https://nextjs.org/docs/advanced-features/i18n-routing
Kde je možnost mít pouze jedny pages pro více jazyků zároveň. Mám rozpracovanou fungující verzi na svém repu branch "enfooter". Pokud by se vám to zdálo jako zajímavá cesta, předělal bych i ty ostatní komponenty v tomto duchu. 
Na závěr bych jen dodal ,že jsem pouze amatér a dělám to jako hobby a  tímto způsobem bych se rád přiučil od zkušenějších. Nešetřete kritikou.
Díky, Marek.

**Comment by zoul** [comment]
Ahoj, Marku! Super, díky, mrknu na to 👍

**Comment by jejdacz** [comment]
Tak nakonec jsem to ještě přehodnotil, podařilo se mi sice zabudovat ten Internationalized Routing ale v tomto případě to nebude až tak vhodný. Přijde mi ,že to akorát navýšilo složitost a vneslo nejasnosti. Takže jsem nakonec pouze pozměnil jen to nejnutnější. Linky ve footeru odkazující na české části jsem v té anglické verzi odstranil, podobně jako nejsou ani v headeru. Branch se jmenuje "footer". Mám teda udělat pull request?
![en-footer](https://user-images.githubusercontent.com/20149581/156130340-f366fdf3-8c05-4bff-aabf-293284d74e26.png)

**Comment by zoul** [comment]
Marku, moc se omlouvám za průtahy 🙏 A souhlasím s tím hodnocením situace, došli jsme kdysi prve k podobnému závěru – to systémové řešení internacionalizace se nevyplatí, pokud máme akorát jednu specializovanou anglickou stránku. Proto jsme zvolili ten současný „hack“, který má dobrý poměr cena/výkon.

To odstranění odkazů v anglické mně dává smysl. Ale myslím, že by se to dalo dotáhnout ještě dál :) a tu patičku vykostit víc. Protože anglická lokalizace toho formuláře vlastně nedává smysl, když by jim následně chodil _český_ newsletter. Pro zajímavost jsem tu patičku vyšmiknul úplně a vlastně mně to nepřijde špatný:

![snap](https://user-images.githubusercontent.com/95329/159642430-a30cfdba-8f4f-444b-ae48-f71eac4a0f6e.png)

Případně, pokud si s tím chceme víc hrát, tam nechat jen nižší tmavý pruh a v něm copyright? (Má na to názory @karmi?)

**Comment by karmi** [comment]
> Případně, pokud si s tím chceme víc hrát, tam nechat jen nižší tmavý pruh a v něm copyright?

To zápatí bych obecně určitě zachoval, a nechal bych v něm ty odkazy "Online" — primárně nám jde o to, aby se z anglické verze šlo jednoduše dostat na Github (ale i ty další služby). Často je to důležité pro ověření důvěryhodnosti, když žádáme o nějakou NGO slevu apod.

**Comment by zoul** [comment]
Díky! Tak jo, Marku, jestlis’ na nás ještě nerezignoval :), pošleš PR s odstraněním těch českých odkazů v prvním sloupci?

**Comment by jejdacz** [comment]
Ahoj,
posílám teda tu verzi co je na tom screenu.

**Comment by karmi** [comment]
Já bych ještě vyhodil ten newsletter, jak navrhoval @zoul — přece jenom, objednávka je v angličtině, a newsletter přijde česky, to není dobré.

Asi by bylo dobré přesunout ty odkazy z _"Online"_ do prvního sloupce, z pohledu designu. A z odkazu "Contact for media" udělat _button_?

**Comment by jejdacz** [comment]
Ok, předělám to a pošlu screen.

**Comment by karmi** [comment]
Screen netřeba, v PR se vyrobí preview :)

**Comment by jejdacz** [comment]
Je to připraveno na preview.
