### ISSUE TITLE
Landing page pro "prispet"

### ISSUE THREAD

**Issue by martinwenisch** [cesko-digital/web#475]
V ramci Google Ads grant kampane s cilem prispivani na >c.d chceme mit Darujme primo na nasi domene (cilit musime vzdy na landing page na nasi domene).

Odkaz na Darujme z menu chceme nahradit landing page s Darujme widgetem (ktery je pripraveny v dashboardu Darujme).

**Comment by karmi** [comment]
Diskutovali jsme dnes @martinwenisch po telefonu, a dohodli jsme následující:

* Nebudeme vytvářet separátní _landing page_, abychom nemuseli řešit layout, textaci, atd
* Pro návštěvy z kampaně zobrazíme v záhlaví stránky speciální „banner“, který bude obsahovat specifický text pro cílení kampaně a darovací widget (viz níže)
* Banner zobrazíme pokud bude URL obsahovat domluvený parametr (např. `campaign`), hodnota parametru je libovolná (může být prázdná), tedy např. `https://cesko.digital/?campaign`

Kód widgetu Darujme.cz, upravený do barev Česko.Digital:

```html
<div data-darujme-widget-token="grgheflwt6oqfufp">&nbsp;</div>
<script type="text/javascript">
	+function(w, d, s, u, a, b) {
		w['DarujmeObject'] = u;
		w[u] = w[u] || function () { (w[u].q = w[u].q || []).push(arguments) };
		a = d.createElement(s); b = d.getElementsByTagName(s)[0];
		a.async = 1; a.src = "https:\/\/www.darujme.cz\/assets\/scripts\/widget.js";
		b.parentNode.insertBefore(a, b);
	}(window, document, 'script', 'Darujme');
	Darujme(1, "grgheflwt6oqfufp", 'render', "https:\/\/www.darujme.cz\/widget?token=grgheflwt6oqfufp", "100%");
</script>
```

Náhled:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/4790/152550300-b8db21b7-0676-4f03-8892-f57181faf63c.png">

**Comment by martinwenisch** [comment]
Dal jsem po trose odstupu dalsi kolo premysleni nad projektem Banner. Bylo by super moci ho umistit vice v kontextu. At uz kontextu ocekavani (copy search termu + Ads na kterou uzivatel reaguje), tak kontextu cilove stranky.

Proto  navrhuju:

- Mit moznost zobrazit ten banner na jakekoli strance a 
- urcit si i ID copy v URL parametru. Napriklad `https://cesko.digital?banner=1` nebo `https://cesko.digital/projects/cityvizor?banner=2`. S daty v Airtable.

Nadhodil jsem to ve Figme: https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=3784%3A35142

**Comment by karmi** [comment]
To není špatný nápad! Jen bych to rozfázoval, a postupoval v menších iteracích — docela se nám to se @zoul vyplácí.

Tedy v prvním kroku bychom implementovali banner se statickým textem a Darujme.cz widgetem, který se zobrazí při URL parametru `banner=t|true`. Design vyřešíme přímo v HTML „po cestě“. Potřebujeme však ten text na banner, přidáš ho prosím zde do issue? (Text ve Figmě je _hodně_ generický, lepší by bylo něco zacílenějšího.)

Pak můžeme postupovat dále, a implementovat dynamické texty pomocí nějakého ID předaného parametrem. Fallback bude na `true`, tzn. zobrazení statického banneru.

**Comment by martinwenisch** [comment]
Asi te nepotesim, ale necham to na tobe.

Muzu ti dat jenom radu, ze to zbytecne komplikujes a rozfazovanim neceho, co by melo byt maly task samo o sobe jenom duplikujes praci (musi se k tomu nekdo v budoucnu vracet, musi to nekdo, kdo to finalni reseni chce urgovat...).

Fallback, kde neni text (ve finalni verzi), bych nezobrazoval vubec => fallback je vzdy ignorovat ten flag uplne. Na tom jedinem bych trval.

**Comment by karmi** [comment]
V linkovaném PR #502 je základní implementace, budeme potřebovat ten finální text.

**Comment by karmi** [comment]
@martinwenisch , prosím tě, pošli sem ten finální text, ať to můžeme dokončit.

**Comment by karmi** [comment]
Closed by #502.
