### ISSUE TITLE
Datová reprezentace projektů

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#48]
[Link na Figmu](https://www.figma.com/file/fKgipGpWBMG9RDj095giPc/Cesko.Digital-Novy-web?node-id=689%3A726)

Jakým způsobem reprezentovat data, aby byly editovatelná v CMS? 

Jaké informace držíme v AirTable? 

Jaký je výhled? 

Jaká je MVP cesta? 

## EDIT - Výstupy:
- Data o projektech budou v repozitáři, budou asynchronně získávány s AirTable
- Synchronizace dat s AirTable řešena v #50

**Comment by zoul** [comment]
Tohle už mně přijde zajímavé mít v AirTable. Představuju si schéma zhruba:

* Název projektu (například _Cityvizor_)
* Tagline (například _Transparentní hospodaření pro každé město a obec_)
* Slug (například `cityvizor`)
* Anotace (krátký text)
* Stav (nevím přesně, nějaký výčet)
* Zapojení dobrovolníci (link do tabulky dobrovolníků, buď stávající Volunteers nebo nová)
* Koordinátor (totéž co Zapojení dobrovolníci)
* Slack (URL)
* Inzerát (nepovinný text)
* …

Kdy bysme chtěli tuhle tabulku začít řešit reálně? A ještě je pro mě zajímavé téma exportu těchto dat z AirTable. Jak upozornit na změny v AirTable? (Nemůže nějaký webhook přijít moc brzy, když budu mít třeba rozepsaný řetězec?) A když budem generovat web, půjdem do živé AirTable? To se mně moc nelíbí, radši bych někde kešovanou kopii v JSON, abysme nebyli na AirTable moc závislí.

**Comment by HormCodes** [comment]
Částečně řešeno v #70 

Kompletní model projektu budeme řešit později. Prozatím uzavírám, v případě potřeby můžeme kdykoliv znovu otevřít.
