### ISSUE TITLE
Chybné URL blog postů na stránce projektu

### ISSUE THREAD

**Issue by karmi** [cesko-digital/web#481]
Ve výpisu souvisejících článků z blogu např. na stránce projektu [_Učíme online_](https://cesko.digital/projects/ucime-online) máme chybu v URL odkazujícím na článek, zdá se, že se tak v případě, kdy byl článek publikován v „jednociferných“ měsících. Např. odkaz [`https://blog.cesko.digital/2021/3/rozhovor-ucime-online`](https://blog.cesko.digital/2021/03/rozhovor-ucime-online) má být správně [`https://blog.cesko.digital/2021/03/rozhovor-ucime-online`](https://blog.cesko.digital/2021/03/rozhovor-ucime-online). Reportovala @anezkamll.

**Comment by zoul** [comment]
[Chyba je tady](https://github.com/cesko-digital/blog/blob/7d59c90bf182ab95015960ad08b3d41066ce374d/api/articles.ts#L36), mrknu na to.

**Comment by zoul** [comment]
Opraveno, díky!
