### ISSUE TITLE
Datová reprezentace homepage

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#49]
[Link na Figmu](https://www.figma.com/file/fKgipGpWBMG9RDj095giPc/Cesko.Digital-Novy-web?node-id=688%3A0)

Jakým způsobem reprezentovat data, aby byly editovatelná v CMS? 

Jaké informace držíme v AirTable? 

Jaký je výhled? 

Jaká je MVP cesta? 

## EDIT - Výstupy:
- Krátké texty budou blízko v šablonách přímo nebo jako datový objekt v komponentě stránky
- V první verzi budou vše statické (dynamická počítadla, info o projektech z AirTable atd. bude implementováno v druhém běhu)
- Anglická verze bude custom stránka
- Synchronizace dat s AirTable řešena v #50

**Comment by zoul** [comment]
Co vidím jako kandidáta na nějaké dynamické zdroje dat:

* Projekty, ze kterých nám tady bude stačit název, slug a tagline. MVP statický zdroják (ta data se mění minimálně), ale IMHO bysme tady mohli docela rychle vyzkoušet to spojení na AirTable. Podrobně viz #48.
* Nabízí se nějak dynamicky dělat i to počítadlo statistik, ale s tím bych si teď vůbec nedělal hlavu, to můžem přidat kdykoliv později. MVP statický zdroják, úpravy ručně.
* Partneři v budoucnu zřejmě opět AirTable, MVP statický zdroják, úpravy ručně.

Stačí takhle?

**Comment by HormCodes** [comment]
@zoul, sepsal si toho více a dříve než já a to jsem po tobě chtěl jen AirTable - díky. 😉 

Vize používání AirTable je mít to jako centrální místo pro všechna interní data? 

Pokud ano, tak to vidím to obdobně. Ono ve výsledku CMS spíše bude o tom, co nepatří do AirTable a pro spojení dat, např. definování projektů na hlavní stránce slugem atd.

**Comment by zoul** [comment]
Pardon, psal jsem to ještě trochu nepřehledně, protože pro mě je AirTable vlastně typ CMS. Já na tom webu vidím tři typy dat:

1. Strukturovaná data, například dobrovolníci a projekty. Jasný kandidát na AirTable – a ano, AirTable se nám rýsuje jako standardní nástroj pro ukládání strukturovaných dat napříč celým Česko.Digital.
2. Delší textová data, například články na blogu. Jasný kandidát na nějaký textově orientovaný CMS ([Netlify CMS](https://www.netlifycms.org)?).
3. Kratší řetězce nespadající do předchozích dvou kategorií, například titulek webu a další drobnější textace.

S tou třetí kategorií si nevím rady. Nemám zkušenosti s CMS, ale přijde mně, že na tohle nejsou dělané, a když se budem snažit to tam nějak nacpat, tak to nebude dobrý zážitek ani ze strany vývojářů, ani ze strany uživatelů toho CMS. Osobně bych preferoval, kdybysme tyhle texty nechali prostě staticky ve zdrojáku s úpravami přes GitHub. (Leda by nějaký CMS nabízel rozhraní à la lokalizační software? Tedy že bysme ve zdrojáku nepoužívali řetězce, ale klíče, a ten CMS umožňoval upravovat řetězce podle klíčů? I tak mně to přijde monstrózně těžkopádný na naše reálné potřeby.)

Z toho plyne, že pro titulku bych vůbec CMS (mimo AirTable) neřešil. Strukturovaná data do AirTable, delší texty do nějakého textového CMS, zbytek úpravami na GitHubu.

**Comment by vpekarek** [comment]
Ahoj. K tomu třetímu bodu - nešlo by na to také použít AirTable? Jedná se vlastně jen o tabulku kód text - CZ text - SK text - ...
ve zdroji by se pak místo textů používali ty kódy, resp. ideálně nějaká funkce, která by buď natáhla text dle kódu, nebo použila nějaký default.

**Comment by zoul** [comment]
Super nápad, to mně nedošlo 👍

Základní otázka u téhle kategorie obsahu pro mě zní, jestli se nám vyplatí to takhle komplikovat – s ohledem na to, jak často se tyhle texty mění, a kolik máme ve Slacku GitHub-gramotných lidí, kteří dokážou ty změny bleskem udělat přímo ve zdrojáku.

Tak či onak je to ale věc, kterou bysme mohli rozfázovat, tj. MVP řetězce typu 3 přímo ve zdrojáku a editace přes GitHub a pokud bude velký zájem, tak v další fázi „lokalizační tabulka“ v AirTable.

**Comment by vpekarek** [comment]
Tak to bych možná šel (už kvůli možným překladům v budoucnu) do toho, že by se udělala ta fn s kódem/textem) ať se to pak nemusí upravovat, a akorát by si zatím nikam nesahala, a vracela rovnou ten text.

Obecně používáme lokalizační řešení dvojí:
- podle kódu: musí se hlídat unikátnost
- podle výchozího textu: menší pravděpodobnost použití jednoho textu na více místech webu

**Comment by zoul** [comment]
Ta souvislost s lokalizací mě taky napadla ([poptávám info ve Slacku](https://cesko-digital.slack.com/archives/CHG9NA23D/p1588754853249400)), jenže tam bysme zase museli řešit lokalizaci informací ve všech dalších datových zdrojích, například tabulce projektů nebo dobrovolníků. (Celkově je ta lokalizace složitější téma s řadou ošemetných detailů, například pluralizace.) Proto bych právě tlačil na ořezání/odložení zbytných věcí, už takhle s tím bude práce dost.

**Comment by vpekarek** [comment]
V tom případě tedy souhlas s tím to držet přímo ve zdrojáku.

**Comment by HormCodes** [comment]
**K anglické verzi webu:** 
Dohodli jsme se s Albertem, že se bude jednat o custom page. S překlady tedy zatím pracovat není třeba. 

**Ke kratším textům:**
Samozřejmě, že jsme schopni to mít přímo v šablonách, ale nebylo by opravdu lepší, aby tyto texty byl schopen editovat někdo přímo z marketingového týmu? Minimální varianta mne napadá JSON nebo MD s Frontmatter obsahující klíče-hodnoty obdobně jako je tomu u stávající verze webu.

**Comment by zoul** [comment]
Určitě to můžeme udělat a nic tím nezkazíme. Můj hlavní argument je, že to můžeme taky odložit na později, pokud se to skutečně ukáže jako potřebná věc. A pokud něco můžeme odložit na později, aniž bysme si to tím nějak zkomplikovali, tak bych to rozhodně udělal.

(Věcně si myslím, že poptávka po častých aktualizacích těchto textů je prakticky nulová, viz dosavadní provoz webu, a pokud bude něco potřeba změnit, tak současné UX „napíšu do Slacku a do pár minut to někdo udělá“ je obtížně překonatelné :–)

**Comment by HormCodes** [comment]
@zoul a @vpekarek, ještě jednou díky za reakce. Výstupy diskuse jsem přidal do popisu issue, mohu vás poprosit o kontrolu, zda jsem na nic nezapomněl?

**Comment by HormCodes** [comment]
Prozatím uzavírám, v případě potřeby můžeme kdykoliv znovu otevřít.
