### ISSUE TITLE
Přihlášení pomocí Slack identity

### ISSUE THREAD

**Issue by karmi** [cesko-digital/web#518]
Kvůli implementaci dalších funkcí potřebujeme umožnit návštěvníkovi webu přihlášení, a tím pádem navázání určitých funkcí webu na jeho identitu (autentizace) a jejich zpřístupnění (autorizace). Vzhledem k ústřední roli Slacku napříč Česko.Digital chceme přihlášení navázat na funkci [_„Sign In with Slack“_](https://api.slack.com/authentication/sign-in-with-slack). Detailní popis kontextu je udržován v příslušné [diskusi](https://github.com/cesko-digital/web/discussions/499).

Pro implementaci chceme využít knihovny [NextAuth.js](https://next-auth.js.org/), která poskytuje jak implementaci přihlašování pro [Slack](https://next-auth.js.org/providers/slack) ([zdrojový kód](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/slack.ts)), tak implementaci [úložiště pro _session_ data](https://next-auth.js.org/adapters/overview). Pro _session_ data chceme využít bezestavového úložiště, tedy pouze v _cookie_ prohlížeče, bez použití databáze. Chceme využít knihovnu [`vvo/iron-session`](https://github.com/vvo/iron-session), viz ukázkový [zdrojový kód](https://github.com/vvo/iron-session/blob/main/examples/next.js-typescript/pages/api/login.ts) a [běžící aplikace](https://iron-session-example.vercel.app). Viz též příklad na [`nextauthjs/next-auth-example`](https://github.com/nextauthjs/next-auth-example).

V rámci tohoto issue chceme pouze implementovat přihlášení a odhlášení, včetně zobrazení avataru a jména přihlášeného návštěvníka.

* [x] Integrace NextAuth.js do webu
* [x] Implementace autentizačního workflow
* [x] Zobrazení odkazu na přihlášení
* [x] Zobrazení avataru a jména přihlášeného uživatele
* [x] Uložení session data do cookie
* [x] Zobrazení odkazu na odhlášení

**Comment by zoul** [comment]
Pro zajímavost, tohle od NextAuth dostaneme jako `Account` při použití Slack providera:

```
{
  "provider": "slack",
  "type": "oauth",
  "providerAccountId": "UJJ3MNA91",
  "ok": true,
  "access_token": "<cenzuruju>",
  "token_type": "Bearer",
  "id_token": "<cenzuruju>",
  "state": "<cenzuruju>"
}
```

**Comment by karmi** [comment]
Nasazeno na https://web-git-feature-login-ui-ceskodigital.vercel.app.
