### ISSUE TITLE
Úprava profilu a nastavení služeb pro přihlášené návštěvníky

### ISSUE THREAD

**Issue by karmi** [cesko-digital/web#538]
Přihlášeným návštěvníkům webu chceme nabídnout možnost úpravy svého profilu a nastavení v rámci služeb Česko.Digital.

V rámci implementace chceme nově promyslet rozvržení tabulek v Airtable a refaktorovat synchronizační API tak, aby bylo robustnější a snadno rozšiřitelné.

### Úpravy databází

V současné chvíli udržujeme data o členech komunity Česko.Digital ve dvou Airtable tabulkách: `Registrations` a `Volunteers`.

Tabulka `Volunteers` je historicky starší, a obsahuje data získaná synchronizací z databází Slacku (viz [zdrojový kód](https://github.com/cesko-digital/volunteer-sync)). Tabulka `Registrations` obsahuje data získaná z formuláře na https://cesko.digital/join. Tabulka `Volunteers` obsahuje propojené sloupce (_„linked record field“_) na tabulku `Registrations`, např. ve sloupci _Self-reported skills_.

Navrhujeme novou strukturu tabulek tak, aby byly rozlišeny tabulky s daty získávanými automatickou synchronizací a tabulky agregující data do formátu snadno využitelného editory a dalšími uživateli.

V nové struktuře tak budou existovat dvě tabulky pro automaticky synchronizovaná data:

1. `Profiles`, která bude obsahovat data z onboardingového formuláře, a všechna nastavení pro daného člena komunity.
2. `Slack Users`, která bude obsahovat data získaná synchronizací ze Slack API.

Pro běžnou práci s daty bude vytvořena nová tabulka `Volunteers`, která bude obsahovat jak propojené sloupce z předchozích dvou tabulek, tak další, manuálně či jinak doplněná data.

Všechny tři tabulky budou obsahovat sloupec `SlackID` s identifikátorem uživatele získaným ze Slack API. Tento sloupec slouží jako _aplikační primární klíč_ pro unikátní identifikaci jednotlivých záznamů, a hlavní způsob udržení integrity dat.

### Rozšíření API pro synchronizace

V nové verzi chceme též přepracovat API pro synchronizaci dat ze Slacku. Pro novou implementaci chceme využít zpracování požadavků na pozadí (_background jobs_), namísto jejich synchronního zpracování při volání API. Zjednodušeně řečeno, namísto zpracování několika tisíc požadavků a odpovědí proti Slack API v rámci běhu skriptu v prostředí Github Actions chceme jednotlivé požadavky rozdělit na co nejmenší části, a zpracovávat je asynchronně na pozadí.

Zvažujeme nasazení jednoduchého systému pro zpracování požadavků na pozadí, https://github.com/contribsys/faktory. Systém umožňuje vkládat požadavky do „fronty”, a jednotlivě je odebírat a zpracovávat, implementace není závislá na žádném konkrétním programovacím jazyku. Systém nainstalujeme na virtuální server v prostředí Amazon Web Services (AWS) nebo Google Cloud Platform (GCP) pod účtem Česko.Digital. V první fázi ověříme technologickou proveditelnost řešení a poté provedeme rozhodnutí.

Pro efektivní monitorování a odstraňování chyb aplikace integrujeme do aplikace [Elastic APM](https://www.elastic.co/guide/en/apm/agent/nodejs/current/custom-stack.html) a [ECS Logging](https://www.elastic.co/guide/en/ecs-logging/nodejs/current/intro.html).

### API a UI pro správu profilu

Pro uložení změn požadovaných uživatelem do databáze implementujeme API, které na základě předaných parametrů upraví příslušný záznam v Airtable.

Pro autorizaci požadavků využijeme token ve formátu [JSON Web Token (JWT)](https://jwt.io), který ukládá do cookie prohlížeče knihovna [NextAuth](https://next-auth.js.org/) při přihlášení. Data (`payload`) jsou NextAuth [šifrována](https://next-auth.js.org/configuration/options#jwt), a pro uživatele nečitelná. Pro validaci tokenu a získání dešifrované hodnoty použijeme metodu [`getToken()`](https://next-auth.js.org/tutorials/securing-pages-and-api-routes#using-gettoken) poskytovanou knihovnou NextAuth.

* `GET /api/protected/profile` vrátí informace o přihlášeném uživateli z databáze „Profiles“ ve formátu JSON.
* `PUT /api/protected/profile` uloží informace o přihlášeném uživateli v databázi „Profiles“ podle hodnoty předané ve formátu JSON v těle požadavku.

Podle dat z API zobrazíme formulářové prvky, odpovídající sloupcům v Airtable, které uživatel může editovat. Provedení změny probíhá skrze API popsané výše. Některé sloupce (jméno, email) je třeba editovat přímo v rozhraní Slacku, uživateli proto zobrazíme nápovědu s odkazem na jeho profil.

Pro práci s formuláři a vykreslení formulářových prvků chceme využít knihovnu [Formik](https://formik.org) v kombinaci s knihovnou [MUI](https://mui.com) (dříve [Material-UI](https://mui.com/blog/material-ui-is-now-mui/)), viz [demo](https://github.com/mui/material-ui/tree/master/examples/nextjs). Pro úpravy seznamu dovedností apod. chceme využít komponentu [_Pill_](https://mui.com/components/chips/#chip-array) (viz [ukázka 1](https://codesandbox.io/s/go2np5?file=/demo.js), [ukázka 2](https://codesandbox.io/s/v7j58o?file=/demo.js)).

Úpravy nastavení newsletteru budeme zpracovávat v separátním issue, z důvodu komplexity (udržení konzistence data mezi Ecomail a Airtable).

* [ ] Zobrazit stránku s UI pro úpravy profilu podle dat v Airtable (např. _skills_)
* [ ] Implementovat API pro uložení upraveného profilu

**Comment by zoul** [comment]
Před mergem:

* [ ] Přidat do profilu zprávu o beta provozu, plus kontakt pro zpětnou vazbu
* [ ] Odebrat možnost změny mailu přes API
* [ ] TBD

Kolem merge:

* [ ] Avízo do #web (odkaz na ticket)
* [ ] Nasdílet do #core a #tech

Po mergi:

* [ ] TBD

**Comment by GabiChl** [comment]
ahoj Tome, ještě k tomu Otestovat celé onboardovací flow - kromě uvítacího emailu, tam máme v AT automation na check, že když se do 5ti dnů nepřihlásí na Slack, tak že mu posíláme také zprávu k zapojení - toto bude potřeba taky upravit na nové tabulky a změnit podmínku, jak jsi včera říkal, že když není confirmed do 5ti dnů, tak zkusit mailing. 
Můžeš prosím také upravit? díky g

**Comment by zoul** [comment]
Udělal jsem pro to samostatný ticket, viz #598.

**Comment by GabiChl** [comment]
Ahojte, tady odkládám k diskuzi až se asi zoul vrátí z putování :slightly_smiling_face: :
Totiž  v rámci překlopení záznamů ve Volunteers mng. jsme v nových datech ztratili informaci o tom, kdy vlastně přišli (pole createdAt jak u User Profiles, tak u Slack Users. 
**Šlo by to "navrdo" překlopit z původních dat?** 
Chtěli jsme udělat udělat statistiku zapojení do projektových týmů 1M po přihlášení do komunity za Q2, ale takto máme data až od května. 
Obecně - jak vlastně s tímto za duben pracujeme v indikátorech? - propojila se GoodData na novou strukturu? 
díky. 
<img width="913" alt="image" src="https://user-images.githubusercontent.com/97018838/175241637-7a45c224-58d1-463a-9653-8926c3242cad.png">
