### ISSUE TITLE
Lepší zobrazení filtrů pro volné pozice (mobil/tablet)

### ISSUE THREAD

**Issue by dominikpatera** [cesko-digital/web#542]
Pří řešení #358 jsem narazil na nehezké zobrazování filtrů ([tady](https://cesko.digital/opportunities)), taktéž v mobilním/tabletím zobrazení.  

Chtěl jsem to původně opravit v rámci [původního issue](https://github.com/cesko-digital/web/issues/358), ale pro přehlednost vytvářím nové issue. Opravy se ujmu. :)

**Comment by zoul** [comment]
Skvělý, díky moc! Kdyby se ti chtělo, tak podle mě by bylo z pohledu UI moc zajímavý na úzkém displeji přepnout na normální select – co myslíš? Tedy něco takového:

<img width="241" alt="8EzEC" src="https://user-images.githubusercontent.com/95329/159640349-66307672-5cbe-4f43-9f42-849531a3d8d6.png">

**Comment by dominikpatera** [comment]
Určitě, bylo by to asi nejlepší řešení a určitě se o to pokusim. :)

**Comment by zoul** [comment]
Hotovo v 5ca0825.

**Comment by dominikpatera** [comment]
Uzavírám. :)
