### ISSUE TITLE
Stránka /join nefunguje bez Airtable API klíče - chybí mock data

### ISSUE THREAD

**Issue by pionl** [cesko-digital/web#552]
👋

```Error: An API key is required to connect to Airtable```

Je někde example? Asi by stačilo vzít z testu?

Díky tomuto nelze nextjs sestavit.

```
> Build error occurred
Error: Export encountered errors on following paths:
        /join
```

**Comment by zoul** [comment]
Díky za report! Je to tak, viz #517. Mrknu na to, chodí mně kvůli tomu každý den jeden mail z nefungující automatizace :)
