### ISSUE TITLE
Opportunities: Otevřít přes Slack nefunguje pokud contactUrl není validní

### ISSUE THREAD

**Issue by pionl** [cesko-digital/web#553]
Tlačítko kontaktovat přes slack nic neudělá (na mobilu otevře stránku znova)  pokud v datech od Airtable není nastaveno contactUrl správně. 

Viz: https://cesko.digital/opportunities/rec15CAUlZLwSFoVg#ua-movapp - zde je v datech `#ua-movapp` 

Úpravu připravuji a PR pošlu. 

## Řešení

- URL nesmí být null / undefinned (toto asi nebude nutné, vypadá to, že interface vynucuje slack, v airtable lze nastavit "nic" ?
- v URL musí být "slack.com"

**Comment by zoul** [comment]
Ahoj, skvělý, díky moc za report.

Airtable bohužel nemá žádnou (!) validaci polí, takže jsme na tom takhle biti. Akorát bych to rád vyřešil jinak než v té komponentě. Bylo by dobré říct, že hodnotou toho pole `contactUrl` musí být URL, a pokud je tam něco jiného, tak odmítnout celou příležitost už během parsování, na vstupu do systému. O tohle se stará funkce `decodeOpportunity`, [viz tady](https://github.com/cesko-digital/web/blob/60d56281afc39fcfc9240c50db8d34b488a90d88/lib/portal-types.ts#L87). Takže můj návrh je, že bysme mohli implementovat funkci `decodeUrl`, která se bude o to parsování URL starat. Bude to mnohem méně invazivní změna, bude se to líp testovat (budeme mít izolovanou funkci) a hlavně se nemůže stát, že by někdo časem přidal další komponentu a narazil na stejný problém.

Co myslíš? Chtělo by se ti to udělat takhle? Můžu s tím případně pomoct. Nějaké existující dekodéry máme v souboru `decoding.ts`, takže tam se můžeš inspirovat. Vypadalo by to nějak takhle:

```typescript
// Tohle je funkce, která dostane libovolnou JavaScriptovou hodnotu
// a ujistí se, že je to řetězec obsahující URL
export const decodeUrl = (value: Pojo): string => {
  const src = string(value); // make sure this is a (non-empty) string
  return src; // TBD: make sure this is a URL
};
```

A testy dekodérů jsou v `decoding.test.ts`, tak tam můžeš testy téhle funkce přidat.

**Comment by pionl** [comment]
Ahoj,

nemám s tím problém. Můžu nechat přepis na komponentu? Přidal jsem tam test.

Mám rovnou přidat "přejmenování" názvu tlačítka pokud tam není slack.com tak by se to jmenovalo "Kontaktovat" ? Když už děláme generické kodování.

Díky

**Comment by pionl** [comment]
Původně jsem chtěl dekodovat rovnou na URL, ale problém je pak s props, kdy mě to převede z URL objektu zpět na string.

Původně jsem myslel ,že to bude local-data.ts loaderem (upravil jsem loader tak to převedlo string -> URL), ale do Page se vždy dostal json.

### Nakonec je to následovně:

- decodeUrl použije URL pro validaci.
- v OpportunityContactCard se pak string url převede zpět na URL (asi by nemuselo, šlo by to i bez toho) a zjistí se zda se jedná o Slack url, nebo mailto nebo ostatní.

###  Texty:

> components/sections/opportunity-contact-card/resolve-contact-title.ts

- Kontaktovat přes Slack

- Kontaktovat přes E-mail

- Kontaktovat  
 
Je to připravené na další "detekce".

**Na všechno jsem dal testy.**

### Example:

- Slack: http://localhost:3000/opportunities/rec8IkvvNuEzsaJ78
- Email: http://localhost:3000/opportunities/rec7nvFj05etQkgKq
