### ISSUE TITLE
Publikace poptávek ze Slack kanálu #market-place na webu

### ISSUE THREAD

**Issue by karmi** [cesko-digital/web#587]
V současné době je proces zpracování poptávek ve Slack kanálu [`#market-place`](https://cesko-digital.slack.com/archives/CLVAH28P3) administrativně náročný: vyžaduje sledovat kanál, odpovídat, vyhledávat vhodné kandidáty, atd. Chtěli bychom proces zefektivnit automatizací některých kroků a publikací poptávek na našem webu, aby byly snadněji dostupné. Následující issue popisuje technické řešení.

1. Vstupem pro celý proces automatizace je robot, který prostřednictvím [API Slacku](https://api.slack.com/events/message.channels) získává jednotlivé zprávy, a ukládá je do databáze v Airtable. Záznam se uloží ve stavu `new`, který indikuje nutnost ověření administrátorem.

2. Administrátor ověřuje nové záznamy, a v případě, že poptávka splňuje potřebná kritéria, může ji přímo přepnout do stavu `published`. Tyto záznamy se publikují na webu, na speciální stránce — nikoliv na [existující stránce příležitostí](https://cesko.digital/opportunities). Záznamy po určité době automaticky přecházejí do stavu `expired` (výchozí: 1 měsíc). Nerelevantní nebo nesmyslné záznamy se označují stavem `invalid`.

3. Po určité době (výchozí: 1 týden) pošle robot do příslušného vlákna v kanále výzvu k aktualizaci stavu: pokud byla daná poptávka úspěšně obsazena, přechází do stavu `completed`. Pokud již není relevantní, přechází do stavu `canceled`.

4. V případě, že poptávka vyžaduje pro publikaci na webu doplnit další údaje, přepne ji administrátor do stavu `needs-detail`. Robot automaticky pošle do příslušného vlákna odkaz na formulář k doplnění údajů. Formulář je přístupný pouze původnímu autorovi zprávy, tedy uživateli přihlášenému příslušnou Slack identitou.

Důležitým prvkem navrženého procesu automatizace je, že nevylučuje běžnou lidskou konverzaci ve vlákně na Slacku.

Výhodou ukládání poptávek do databáze v Airtable je zároveň to, že nám umožňuje sledovat související metriky (počet poptávek v čase, podíl úspěšně odbavených poptávek, atd.)

**Comment by zoul** [comment]
Moje technické poznámky:

* [Slack Events API](https://api.slack.com/events)
* Nás zajímá událost [message.channels](https://api.slack.com/events/message.channels) (zpráva zaslaná v rámci kanálu)
* [Message Event](https://api.slack.com/events/message)

**Comment by zoul** [comment]
K těm nabídkám bude asi dobré doplnit nějaký titulek, aby se s nimi líp pracovalo na webu, což? Je možné to udělat tak, že by titulek doplnil „editor“, až bude přepínat poptávku v Airtable do stavu `published`? (Zkusím to zatím implementovat takhle.)

**Comment by GabiChl** [comment]
ahojte, tady ještě dávám inspiraci, jak market-place služba funguje v NL , kdy mají i nějaký min. fee pro NGOs, kterým pomáhají matchovat poptávku na dobrovolníky: https://denieuwegevers.nl/
Plus tady je ještě další varianta zase zpoplatnění příchozích projektů do akcelerace a matchování na studenty dobrovolníky: https://developforgood.org/

**Comment by zoul** [comment]
Zpětná vazba ze společného konzultace s Gábi:

* [ ] Po zveřejnění poptávky editorem chceme, aby se robot ozval do vlákna a postnul URL poptávky; stačí jednou denně.
* [ ] Gábi otestuje načítání nabídek z kanálu a zveřejňování na webu.

**Comment by GabiChl** [comment]
Testing načítání poptávek na web:
	1. Když zadává někdo z kmenového týmu č.d, tak se ozvat se emailem dává soukromý email - šlo by nějak toto ošetřit a nabírat jako výchozí č.d email nebo mít možnost v rámci AT zadat aspoň ručně na jaký email odkazovat, neb to může být problém i u dobrovolníků, že je do komunity nahlášený přes soukromou adresu, ale v mp poptávce napíše pracovní email. 

	2. Když zadávám dlouhý text, tak v rámci pohledu PD, tak to pak zobrazí jen 1 mp poptávku - šlo by to auto-ořezávat? Třebas dát jen ten heading a pak prvních x znaků s možností rozkliku dál. U opportunities se také zobrazuje jen jméno pozice.

Plus šlo nějak více vizuálně oddělit jednotlivé poptávky? 

Zbytek nedokážu asi sama otestovat neb to neumím posouvat do dalšího kroku, tak jestli by šlo si to tandemově otestovat společně? Můžeme naplánovat třebas na zítra dopo? 
Jinak super, duper - fachčí to dobře :) díky g.

**Comment by zoul** [comment]
K e-mailům viz #630. Z různých důvodů vedeme u uživatelů tři adresy – jednu vyplní v našem onboardingu (`/join`), jednu v onboardingu Slacku (ideálně stejnou, ale nemůžeme zaručit) a ještě jednu sbíráme ve Slacku v nastavení profilu v rámci „custom fields“. Za sebe asi navrhuju to, co v #630, tedy používat tu adresu z profilu ve Slacku jako kontaktní a výhledově doplnit možnost její změny do uživatelského profilu na webu. Mrknu teď prioritně na to, abychom tu třetí adresu vůbec měli v databázi a mohli s ní pracovat.

Dlouhý text a obecně vizuál – současná vizuální podoba je v podstatě prototyp, počítáme s tím, že před vydáním poladíme. Jsme domluveni s Karlem, že na to mrkne.

Ohledně ladění se ozvu ve Slacku.

**Comment by GabiChl** [comment]
> K e-mailům viz #630. Z různých důvodů vedeme u uživatelů tři adresy – jednu vyplní v našem onboardingu (`/join`), jednu v onboardingu Slacku (ideálně stejnou, ale nemůžeme zaručit) a ještě jednu sbíráme ve Slacku v nastavení profilu v rámci „custom fields“. Za sebe asi navrhuju to, co v #630, tedy používat tu adresu z profilu ve Slacku jako kontaktní a výhledově doplnit možnost její změny do uživatelského profilu na webu. Mrknu teď prioritně na to, abychom tu třetí adresu vůbec měli v databázi a mohli s ní pracovat.
> 
> Dlouhý text a obecně vizuál – současná vizuální podoba je v podstatě prototyp, počítáme s tím, že před vydáním poladíme. Jsme domluveni s Karlem, že na to mrkne.
> 
> Ohledně ladění se ozvu ve Slacku.

Prima, díky moc. 

Ještě k tomu vizuálu - pro @karmi  - asi mi tam chybí nějaký titulek, který by se pak mohl zjednodušeně ukazovat v přehledu PD (navíc by se na něj nezapomínalo při publikaci v textu - protože spoustu nových poptávek na slacku začíná ahoj :) ).  A na dashboardu PD chybí v rámci m-p poptávek oddělení těch jednotlivých poptávek - viz obr.
<img width="904" alt="image" src="https://user-images.githubusercontent.com/97018838/189070367-58d2573f-8068-442b-b808-b1812af8c1f8.png">

**Comment by zoul** [comment]
Odbavil jsem dneska #630, takže nám v databázi přibyl e-mail ze slackového profilu a pokud je vyplněný, dáme mu při zobrazování nabídek z market-place přednost. Kdyby tedy někdo reklamoval, že se mu u nabídky zobrazuje soukromý mail, může si v profilu Slacku nastavit libovolný jiný.

**Comment by GabiChl** [comment]
> Odbavil jsem dneska #630, takže nám v databázi přibyl e-mail ze slackového profilu a pokud je vyplněný, dáme mu při zobrazování nabídek z market-place přednost. Kdyby tedy někdo reklamoval, že se mu u nabídky zobrazuje soukromý mail, může si v profilu Slacku nastavit libovolný jiný.

Pecka, díky za úpravu.

**Comment by GabiChl** [comment]
@zoul Ahoj Tome, ještě k tomuto jedna drobnost. Hodilo by se mi mít v té auto-message od Bazaar Bota svůj tag, abych viděla, že je tam případně nějaká další reakce a pro organizace mít možnost komu se ozvat. Totiž takto mám tendenci ty vlákna ignorovat. :) 
stačilo by tam doplnit větičku "Pokud je něco potřeba ozvěte se prosím @xxx." / jen ten uživatel je teda úzké místo, že to není generické no, že? nevím, ale hodilo by se to tam mít teda. Co ty na to? Napadá tě, jak toto pořešit? díky
