### ISSUE TITLE
Vylepšení publikovaných informací o projektech na webu

### ISSUE THREAD

**Issue by karmi** [cesko-digital/web#590]
V rámci zefektivnění "program managementu" bychom chtěli většinu informací, které o projektech udržujeme, převést do databáze „Web“, abychom je mohli využít pro zobrazení na našem webu a zároveň zabránili duplicitnímu zadávání informací do různých databází a tabulek.

Chceme proto naprostou většinu informací udržovat v tabulkách databáze „Web“ — oproti současnému stavu tedy přidat úplné informace o projektovém týmu, externích zdrojích, atd. Informace týkající se projektového řízení v užším slova smyslu — milníky, úkoly, apod. — budeme nadále udržovat v externích nástrojích (Jira, GitHub). Průběžné hodnocení projektů koordinátory budeme udržovat v separátní databázi.

Pro udržování informací o projektových týmech vytvoříme v databázi „Web“ tabulku `Teams`, která bude propojena s tabulkou `Profiles 2.0` (jméno, e-mail, Slack ID). Tabulka bude obsahovat následující sloupce:

* Název projektu (propojení do tabulky `Projects`)
* Role v projektu (scrum master, tech lead, developer, ...)
* Typ zapojení (dobrovolník, zadavatel, koordinátor, ...)
* Začátek a konec zapojení
* Publikovat záznam na webu (true/false)
* Publikovat e-mail na webu (true/false)
* Publikovat Slack username (true/false)

**Comment by GabiChl** [comment]
díky moc za sepsání, karmi. [Do spreadsheetu, tab Project fields](https://docs.google.com/spreadsheets/d/1AX4YiZc29v-0Fgy9dOj1Q2RC8xMdBWd2ns7EMEa9JT4/edit#gid=190029807) jsem zadala pole, které budeme potřebovat přesunout či je na zvážení, jak s nimi naložíme. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/97018838/167366680-1407993a-1943-46d2-9c36-b4b302733577.png">

**Comment by zoul** [comment]
Pustil jsem se do toho. Máme v Airtable [tabulku _Teams (legacy)_ s původními daty](https://airtable.com/appkn1DkvgVI5jpME/tbldIp90y4ZGUmjr0/viwGkbFZImPrnHVXF?blocks=hide) (předpokládám od Gábi) a já jsem založil [novou tabulku _Teams_](https://airtable.com/appkn1DkvgVI5jpME/tblszIbIBAluUHvH0/viwPVXezEWX7wTTH5?blocks=hide) s aktualizovaným schématem. Poznámky:

* Roli na projektu jsem z Multiple Select změnil na obyčejný text, stejně v tom původním výčtu byly věci dvojmo
* V původních datech bylo pár lidí, které nemáme v komunitě (v nové tabulce zatím reprezentováno prázdným polem `user`). Tohle aktuálně nejsme schopni reprezentovat (potřebujeme odkaz na záznam v tabulce User Profiles), navrhuju vypustit. Pokud vypustit nemůžeme, je potřeba založit nějaký „virtuální profil“, ale vždycky nás to pak někde dožene.
* Máme velký nesoulad v projektech :) Což je OK, proto to taky děláme. V původní databázi byla hromada projektů, které na webu nejsou. Zčásti to jsou interní věci (Produkce č.d, Obsah č.d, …), zčásti jsou to projekty, které jsme vůbec nedali na web (6 hodin), zčásti nevím (Vzdělávání ukrajinských dětí). Vhodné řešení asi nejlíp probrat synchronně?
* Data o uživatelích bereme ze [synchronizovaného pohledu](https://airtable.com/appkn1DkvgVI5jpME/tbl3QK2aTskyu2rNQ/viwBjs18OCSLYoCCV?blocks=hide) User Profiles. Trochu blbé je, že tím pádem neexistuje viditelná vazba v hlavní tabulce uživatelských profilů – při pohledu do hlavní tabulky [User Profiles](https://airtable.com/apppZX1QC3fl1RTBM/tblUmjkniqR4PUu5R/viwBaBrZ24v09QOpt?blocks=hide) nejsme schopni jednoduše říct, kde všude se uživatel zapojil. Není to fatální.
* U hromady lidí nám chybí role v organizaci (dobrovolník / placený člověk / …). Má smysl brát jako výchozí hodnotu Dobrovolník?
* Ta „práva“ à la „publikovat zapojení na webu“ a podobně by bylo dobré domyslet. Kde ty hodnoty vezmeme? Nabízí se to integrovat do uživatelského profilu na webu, buď globálně (_Ano, moje zapojení do projektů může být veřejně viditelné_), anebo per-projekt (_Ano, toto moje zapojení do projektu může být veřejně viditelné_). Taky asi dobré doprobrat synchronně.

Ještě si trochu pohraju s konverzí těch dat na nové schéma (tj. přenos z tabulky _Teams (legacy)_ do tabulky _Teams_), ale pak bych potřeboval ty věci probrat s vámi, abych mohl pokračovat. Případně to samozřejmě můžete probrat beze mě a dát mi vědět.

**Comment by GabiChl** [comment]
> Pustil jsem se do toho. Máme v Airtable [tabulku _Teams (legacy)_ s původními daty](https://airtable.com/appkn1DkvgVI5jpME/tbldIp90y4ZGUmjr0/viwGkbFZImPrnHVXF?blocks=hide) (předpokládám od Gábi) a já jsem založil [novou tabulku _Teams_](https://airtable.com/appkn1DkvgVI5jpME/tblszIbIBAluUHvH0/viwPVXezEWX7wTTH5?blocks=hide) s aktualizovaným schématem. Poznámky:
> 
> * Roli na projektu jsem z Multiple Select změnil na obyčejný text, stejně v tom původním výčtu byly věci dvojmo
> * V původních datech bylo pár lidí, které nemáme v komunitě (v nové tabulce zatím reprezentováno prázdným polem `user`). Tohle aktuálně nejsme schopni reprezentovat (potřebujeme odkaz na záznam v tabulce User Profiles), navrhuju vypustit. Pokud vypustit nemůžeme, je potřeba založit nějaký „virtuální profil“, ale vždycky nás to pak někde dožene, nedělal bych to.
> * Máme velký nesoulad v projektech :) Což je OK, proto to taky děláme. V původní databázi byla hromada projektů, které na webu nejsou. Zčásti to jsou interní věci (Produkce č.d, Obsah č.d, …), zčásti jsou to projekty, které jsme vůbec nedali na web (6 hodin), zčásti nevím (Vzdělávání ukrajinských dětí). Vhodné řešení asi nejlíp probrat synchronně?
> * Data o uživatelích bereme ze [synchronizovaného pohledu](https://airtable.com/appkn1DkvgVI5jpME/tbl3QK2aTskyu2rNQ/viwBjs18OCSLYoCCV?blocks=hide) User Profiles. Trochu blbé je, že tím pádem neexistuje viditelná vazba v hlavní tabulce uživatelských profilů – při pohledu do hlavní tabulky [User Profiles](https://airtable.com/apppZX1QC3fl1RTBM/tblUmjkniqR4PUu5R/viwBaBrZ24v09QOpt?blocks=hide) nejsme schopni jednoduše říct, kde všude se uživatel zapojil. Není to fatální.
> * U hromady lidí nám chybí role v organizaci (dobrovolník / placený člověk / …). Má smysl brát jako výchozí hodnotu Dobrovolník?
> * V poslední době prakticky nevyplňujeme data zapojení. Má smysl tedy tohle stěhovat, nebo jsme na takhle podrobná data rezignovali?
> * Ta „práva“ à la „publikovat zapojení na webu“ a podobně by bylo dobré domyslet. Kde ty hodnoty vezmeme? Nabízí se to integrovat do uživatelského profilu na webu, buď globálně (_Ano, moje zapojení do projektů může být veřejně viditelné_), anebo per-projekt (_Ano, toto moje zapojení do projektu může být veřejně viditelné_). Preferuju to jednodušší globální řešení; taky asi dobré doprobrat synchronně. (Opt-in vs. opt-out?)
> 
> Ještě si trochu pohraju s konverzí těch dat na nové schéma (tj. přenos z tabulky _Teams (legacy)_ do tabulky _Teams_), ale pak bych potřeboval ty věci probrat s vámi, abych mohl pokračovat. Případně to samozřejmě můžete probrat beze mě a dát mi vědět.

ahojte, ještě k těm Teams a pole Datum ukončení - čím více o tom přemýšlím, tak je to toto pole potřeba, protože potřebujeme mít na wiki aktuální tým, tzn. když někdo z týmu vypadne, tak jej chceme odfiltrovat pryč. 
plus když budeme dělat v budoucnu kolik je aktuálně aktivních dobrovoníků na projektech, tak budeme brát ty bez data ukončení a pro neuzavřené projekty. takže lobuju za to tam toto pole opravdu mít. díky :)

**Comment by zoul** [comment]
Já to právě nevidím jako „aktuální tým“, ale „k vývoji tohoto projektu přispěli“.

**Comment by GabiChl** [comment]
> Já to právě nevidím jako „aktuální tým“, ale „k vývoji tohoto projektu přispěli“.

z pohledu webu ano, ale z pohledu použití jako projektové info, tak ano. což?

**Comment by zoul** [comment]
Já ani nemyslel na vizuální reprezentaci, spíš se obecně snažím pojmenovat tu věc tak, aby dávala smysl a *hlavně* abysme pro ni měli data. Protože v tom je podle mě hlavní zádrhel. Já si nedovedu představit, že budu klečet projektových koordinátorech, aby mně dodávali aktuální data o členech týmu. Proto nám taky to datum ukončení teď prakticky všude chybí. Má smysl dělat něco, o čem už teď víme, že to nevyplňujeme? (Proberte prosím s @karmi a dejte sem vědět výsledek, díky.)

**Comment by zoul** [comment]
Další krok je přehodit koordinátory projektu z tabulky Volunteers na novou tabulku Teams. V tabulce Projects tahle vazba už je, takže je potřeba přehodit kód a smazat původní vazbu. Přehození kódu není technicky triviální, protože zatím to máme udělané tak, že během buildu vždycky načítáme seznam _všech_ uživatelů z tabulky Volunteers, ze kterého si pak vybíráme ručně ty koordinátory:

```typescript
  const coordinators = project.coordinatorIds.map((id) => users.find((user) => user.id === id)!)
```

Analogickou věc děláme u eventů a příležitostí. V rámci přehození na tabulku Teams je potřeba tohle nějak revidovat, protože v té tabulce je všech _x_ tisíc členů komunity, což je jednak hodně dat, jednak nechceme tahle data dávat jen tak z ruky třeba přes API.

Asi to nejjednodušší, co teď můžeme udělat, je přestat načítat uživatele jako kompletní seznam, přestat je vystavovat přes API a přidat query funkce, které vrátí omezený seznam uživatelů relevantní pro danou stránku – koordinátory projektu (+ časem tým projektu), vlastníka eventu, vlastníka příležitosti, etc.

Což ovšem nesedí do našeho současného zjednodušeného modelu práce s daty, kdy předpokládáme, že máme všechna data načtená dopředu a jednotlivé stránky webu si z nich během buildu jen vytahají to, co potřebují. Tohle je žádoucí nesoulad a žádoucí posun, chceme ten datový model mít dynamičtější – mimo jiné se tím výrazně zrychlí obrátky při lokálním vývoji webu. Jen je potřeba přijít na řešení, které zachová možnost vývoje nad lokálními „dummy“ daty, už jen kvůli testům a nižšímu prahu pro přispěvatele (nechceme dojít do stavu, kdy si přispěvatel bez klíčů od databáze neškrtne).

Ještě podumám a napíšu.

**Comment by zoul** [comment]
PS: Píšu tady o uživatelích, ale zatímco v legacy tabulce Volunteers jsou fakt konkrétní lidi, v tabulce Teams (která by se měla jmenovat spíš _Team Engagements_) jsou _zapojení_ lidí na projektech, tedy jeden člověk tam může být mockrát. Zbytek úvahy to ale nemění.

**Comment by zoul** [comment]
Úvahy o datové vrstvě jsem oddělil do #663, myslím, že už vím, jak to udělat.
