### ISSUE TITLE
Přidat H1 mezi partnery

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#592]
@MartinaHabova posílala logo, které je potřeba přidat. Marti, máme těch partnerských sekcí víc, kam přesně to logo patří? A nemáme verzi ve vyšším rozlišení? To, cos posílala (přikládám), je hodně malé. Kam má vést proklik?

![logo](https://user-images.githubusercontent.com/95329/167617329-887d5d28-7a24-4aa9-8afe-5ececafd2097.png)

**Comment by MartinaHabova** [comment]
@zoul nemám, takhle mne to poslali.

**Comment by zoul** [comment]
OK, a do které sekce tedy logo patří a kam má vést proklik? Díky!

**Comment by MartinaHabova** [comment]
pujde do partnerské stránky pod expertní partnery a odkaz půjde na https://www.h1.cz/

**Comment by zoul** [comment]
Je to tam 🎉

**Comment by MartinaHabova** [comment]
oooo, já myslela, že to budu sama nahazovat přes airtable tabulku a deployovat - tenhle all inclusive se mi líbíííí, děkuju moc
