### ISSUE TITLE
Přidání stužky "Vítěz ceny SDGs" s odkazem na příslušný článek

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#60]
Přidat na stávající web stuhu s informací o tom, že jsme [dostali cenu Sustainable Development Goals](https://cesko-digital.slack.com/archives/CG07ST9ME/p1600409349015100). Stužka by měla být klikatelná a odkazovat [sem](https://www.spolecenskaodpovednost.cz/cesko-zna-nejlepsi-projekty-udrzitelnosti-pro-rok-2020-oceneny-byly-v-cenach-sdgs/).

Představa layoutu v přiložených souborech - je možné, že bude nutné ladit velikost stuhy. Potřebné soubory přiloženy též. 

![layout](https://user-images.githubusercontent.com/10332399/94584765-60056300-027f-11eb-8a54-613238229767.png)
![Vitez_web_A](https://user-images.githubusercontent.com/10332399/94584779-63005380-027f-11eb-9e8b-347c30507ee4.png)
![Vitez_web_B](https://user-images.githubusercontent.com/10332399/94584780-6398ea00-027f-11eb-8138-ed711f4ea01f.png)

**Comment by fidelman** [comment]
A co mobilní verze?

**Comment by radkoa** [comment]
Mobilní verzi bych neřešil jako součást této issue, tam to zřejmě potřebuje více vyladit a připravit. @zoul, @HormCodes souhlas?

**Comment by pavelsuraba** [comment]
Vezmu si to v týdnu ale pokud má zájem i někdo jiný ozvěte se na slacku je to dobré "first issue".
