### ISSUE TITLE
Dočasně přidat na join.cesko.digital změnu textace pro možnost testování prototypu

### ISSUE THREAD

**Issue by GabiChl** [cesko-digital/web#636]
Do části webu https://cesko.digital/join
Přidat text dle návrhu [zde](https://www.figma.com/file/KagtaZEZL7lwIUaFsLdwuE/%3EC.D-%2F-Join?node-id=4425%3A44156).
Ideálně přidat prosím od začátku července (aby aspoň 2 týdny do testování 18.-19.6.)
**po 19.6.** prosím vrátit text zpátky do původní podoby.

Těmto testovaným uživatelům doplníme informace přes join z naší strany. 
díky gábina

**Comment by karmi** [comment]
Preview změn na https://web-git-join-survey-ceskodigital.vercel.app/join.
