### ISSUE TITLE
Stránka „O nás“

### ISSUE THREAD

**Issue by karmi** [cesko-digital/web#638]
Na našem webu schází obvyklá stránka _„O nás“_, která by představila organizaci jako celek, její historii, jednotlivé členy kmenového týmu, a celkově usnadnila orientaci v kontaktech a klíčových dokumentech. Pro kontext viz [diskusi na Slacku](https://cesko-digital.slack.com/archives/CHG9NA23D/p1653916708239589).

Stránka by tak:

1. sjednotila důležité informace o organizaci na jednu stránku
2. představila kmenový tým Česko.Digital.

Přehled obsahu stránky:

* Představení Česko.Digital
* Kmenový tým
* Výroční zprávy
* Kontakt pro média
* Informační panel pro partnerství
* Informační panel pro dárcovství

### Představení Česko.Digital

Stručná informace o zaměření a předmětu činnosti organizace, popis její historie a důležitých milníků.

### Kmenový tým

Seznam členů kmenového týmu ve formátu:

* Jméno a příjmení
* Role v organizaci
* Kontaktní email
* Přezdívka na Slacku
* Fotografie
* Krátký profesní životopis
* Popis role/zodpovědností

Základní informace o členech kmenového týmu jsou dostupné na [wiki](https://cesko-digital.atlassian.net/wiki/spaces/CD/pages/817725673/Kmenov+t+m+esko.Digital).

### Výroční zprávy

Seznam výročních zpráv organizace ke stažení/náhledu. Aktuální výroční zpráva je zvýrazněná.

### Kontakt pro média

Kontaktní osoba a email pro média (v současnosti pr@cesko.digital, navrhuji změnit na press@cesko.digital). Odkaz na [logo organizace](https://znacka.cesko.digital) a další materiály (fotografie, ...) ke stažení.

### Informační panel pro partnerství

Stručné informace pro potenciální partnery organizace, kontaktní osoba a email. Odkaz na stránku [_Partneři_](https://cesko.digital/partners).

### Informační panel pro dárcovství

Výzva k finanční podpoře organizace a odkaz na platformu [Darujme.cz](https://www.darujme.cz/projekt/1203553).

TODO:

* [x] Sekce Kmenový tým
* [x] Sekce Správní rada
* [x] Sekce Expertní dobrovolníci
* [x] #763
* [ ] Přidat na stránku o týmu odkazy na LinkedIn
* [ ] Přidat na stránku o týmu e-mailové adresy
* [ ] Přidat stránku o týmu někam do navigace

**Comment by MartinaHabova** [comment]
Na podstránce pracuje dobrovolnice Markéta Hájková. Wireframe vzniká ve figmě.

**Comment by MartinaHabova** [comment]
Wireframe je připravený zde https://www.figma.com/file/KagtaZEZL7lwIUaFsLdwuE/%3EC.D-%2F-Join?node-id=5088%3A40477

**Comment by MartinaHabova** [comment]
Ve středu jsme schopni dodat link na google disk, kde jsou všechny fotografie.
Pak si musím s týmem odsouhlasit popisky/texty, které budou mít u svého jména.
Následně můžeme do produkce.

**Comment by MartinaHabova** [comment]
Fotky týmu jsou k nalezení zde:
https://drive.google.com/drive/folders/1m9yFbdl7uzGWTksOPJZg9U0M9PNt9zvZ

**Comment by zoul** [comment]
Ne-e, jak budou data pro ně, tak je tam hned šoupnu.
