### ISSUE TITLE
Tvrdá mezera v textu ve footeru na home page

### ISSUE THREAD

**Issue by jindrich-oukropec** [cesko-digital/web#642]
<img width="628" alt="obrazek" src="https://user-images.githubusercontent.com/69157075/182336400-134123c2-329c-40ab-8288-da3087d4f097.png">

Kosmetická úprava, která vytvoří úsměv všem bohemistům!
V textu ve footeru na home page máme na konci řádku "co se v". Prosím dát "v" na druhý řádek.

PS: Jde na to udělat nějaké pravidlo? Koukám, že nám samostatná písmenka na konci řádků skákají u textu k hodnotám při zmenšení obrazovky na mobile verzi. Ručně to dělat asi není udržitelné obzlášť když se texty mohou měnit.

Moc děkuji!

**Comment by zoul** [comment]
Text možno změnit v souboru [content/strings.json](https://github.com/cesko-digital/web/blob/master/content/strings.json), stačí tam vložit tu nedělitelnou mezeru. Chceš s tou změnou pomoct?

Šlo by to vyřešit i automaticky, tedy tím „pravidlem“, jak píšeš, ale realisticky viděno máme tolik důležitějších věcí, že se k tomu nedostaneme a navrhuju to tedy ve výraznějších případech řešit takhle, úpravou podkladů.
