### ISSUE TITLE
Spojazdnenie URL cist.digital

### ISSUE THREAD

**Issue by Teryii** [cesko-digital/web#644]
Ahoj, už dávnejšie sme sa dohodli, že znova spojazdníme URL cist.digital.

Tvorí sa z toho všade webová adresa, keď to niekam píšem, tak by to bolo super nalákanie ľudí na ten obsah. 😊

Neskôr tam môžeme nalinkovať zoznam už odoslaných newsletterov. Poprípade prihlasovací formulár.

Je to teda možné? Díky!

**Comment by zoul** [comment]
Hotovo, pardon za zpoždění.
