### ISSUE TITLE
Chybné Datum vytvoření pro historické záznamy v rámci Slack User a User Profiles -

### ISSUE THREAD

**Issue by GabiChl** [cesko-digital/web#646]
ahoj, 
po přesunu historických záznamů do nové datové struktury ukazuje na historických záznamech v poli CreatedAt datum přesunu a vytvoření nového záznamu. 
Pro možné metriky ale budeme potřebovat, aby Datum vytvoření ukazovalo skutečné datum, kdy byl záznam vytvořen - šlo by převést dle původního záznamu? 
Probráno se @zoul, že bude asi potřeba: 
- změnit automatizované pole na ručně vytvářené 
- namigrovat správné datum 
- mít funkci, která toto pole bude automaticky plnit pro nové záznamy. 

díky

**Comment by zoul** [comment]
Jak si to představuju:

* Vytvořím pole `reallyCreatedAt` typu timestamp.
* Pomocí skriptu projdu tabulku User Profiles a přes Slack ID najdu původní záznam v tabulce Volunteers.
* Pokud tento záznam existuje, zkopíruju hodnotu z pole `Datum vzniku` do pole `reallyCreatedAt`.
* Pokud záznam neexistuje, zkopíruju do pole `reallyCreatedAt` hodnotu z pole `createdAt`.
* Zahodím sloupec `createdAt` a přejmenuju `reallyCreatedAt` na `createdAt`.

Poznámky:

* Co automatizace? Nechceme rozposílat hromadu mailů. Jednak by bylo dobré je během změny vypnout, jednak je bude třeba přehodit na nový sloupec.
* Časy z původní tabulky Volunteers nejsou reprezentativní / správné, odpovídají nočnímu běhu synchronizačního skriptu. Data plus mínus sedí – až na pár výjimek, kdy synchronizační skript nějakou pár dní neběžel.

**Comment by GabiChl** [comment]
> 

Super, díky za podrobný rozpis. Ještě by bylo dobré před změnou dát info na Slack, že se toto děje, neb tam mohou mít ostatní synchronizace do jiných AT bází.  
Což mi připomíná, že User Profile máme synch do web AT, kde na CreatedAt filtruji nějaké temp pohledy, takže pak bude potřeba re-synch a předělat na nové pole.

**Comment by zoul** [comment]
Ještě jsem ten plán upravoval, mrkneš prosím na současnou verzi? Udělám to nakonec nad existujícím polem, takže podle mě nebude kromě dočasného vypnutí automatizací potřeba nic extra – prostě se ta hodnota u některých záznamů změní.

**Comment by GabiChl** [comment]
Jo, super, takto je to ještě lepší varianta. díky za to :)

**Comment by zoul** [comment]
Skript proběhl, můžeš prosím mrknout na data, jestli to za tebe vypadá OK? Za mě jo. Pokud za tebe taky, můžeme zavřít.

**Comment by GabiChl** [comment]
ahoj zoule, pecka, díky za super rychlost. data vypadají ok - teď je tam za 04/22 -108 záznamů a ze slack analytics jsme ten měsíc psali, že je 113 nově příchozích (ale tam to záleží, za jaké dny se to ručně přesně nabíralo, někdy to o 1-2dny uskočí), takže plus mínus počty sedí :)  a můžeme uzavřít teda.
