### ISSUE TITLE
Implementace tlačítek v rámci design systému

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#65]
**Technologie:** React, TypeScript, Gatsby

V rámci #64 

Vytvořit stateless komponentu pro tlačítko podle vizuálního stylu >Č.D. Rozhraní komponenty je otevřené, ale představuji si mít něco jako: 

```
<Button>
   type={ButtonTypes.Normal}
   size={...}
   disabled={false}
   onClick={() => console.log('Hello!')}
<Button>
   Click Here!
</Button>
```

**Na co nezapomenout:** 

- Komponenta by neměla mít žádný stav
- Přidat dokumentaci (story) do Storybooku
- Odklonit se od větve `rework`

**Figma:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=16%3A72)

V případě nejasností nebojte se na mne obrátit. 🙂 

![buttons](https://user-images.githubusercontent.com/10332399/96347114-b2c48480-109f-11eb-8aff-ca87340c3428.png)

**Comment by fidelman** [comment]
muzu to vzit

**Comment by HormCodes** [comment]
Super! ❤️  ... Přiradil jsem tě k issue.

**Comment by fidelman** [comment]
po prozkoumání styleguidu a několika dokončených stránkách jsem nenašel žádný vzor, kde použít Link a kde jen Button. Takže si myslím, že Link i Button budou mít stejné možnosti stylu:

|size/type        | primary \(default for Button\) | secondary | link \(default for Link\) |
|--------|--------------------------------|-----------|---------------------------|
| normal |     <img width="159" alt="Screenshot 2020-10-28 at 10 45 26" src="https://user-images.githubusercontent.com/15198653/97420612-d099b100-190b-11eb-867d-f2eab5e29213.png">             | <img width="198" alt="Screenshot 2020-10-28 at 10 45 29" src="https://user-images.githubusercontent.com/15198653/97420631-dbecdc80-190b-11eb-9ecf-0e5220f112ca.png">          |       <img width="123" alt="Screenshot 2020-10-28 at 10 45 32" src="https://user-images.githubusercontent.com/15198653/97420520-b2cc4c00-190b-11eb-9ea2-14ee64efdf35.png">  |
| small  |                  Like small secondary but inverted              |    <img width="96" alt="Screenshot 2020-10-28 at 10 45 35" src="https://user-images.githubusercontent.com/15198653/97420423-992b0480-190b-11eb-8f94-5dc065ab12b7.png">       |  <img width="80" alt="Screenshot 2020-10-28 at 10 45 37" src="https://user-images.githubusercontent.com/15198653/97420552-beb80e00-190b-11eb-9e71-1a69de38dc5e.png">                         |

**Comment by fidelman** [comment]
> po prozkoumání styleguidu a několika dokončených stránkách jsem nenašel žádný vzor, kde použít Link a kde jen Button. Takže si myslím, že Link i Button budou mít stejné možnosti stylu:
> 
> size/type	primary (default for Button)	secondary	link (default for Link)
> normal	<img alt="Screenshot 2020-10-28 at 10 45 26" width="159" src="https://user-images.githubusercontent.com/15198653/97420612-d099b100-190b-11eb-867d-f2eab5e29213.png">	<img alt="Screenshot 2020-10-28 at 10 45 29" width="198" src="https://user-images.githubusercontent.com/15198653/97420631-dbecdc80-190b-11eb-9ecf-0e5220f112ca.png">	<img alt="Screenshot 2020-10-28 at 10 45 32" width="123" src="https://user-images.githubusercontent.com/15198653/97420520-b2cc4c00-190b-11eb-9ea2-14ee64efdf35.png">
> small	Like small secondary but inverted	<img alt="Screenshot 2020-10-28 at 10 45 35" width="96" src="https://user-images.githubusercontent.com/15198653/97420423-992b0480-190b-11eb-8f94-5dc065ab12b7.png">	<img alt="Screenshot 2020-10-28 at 10 45 37" width="80" src="https://user-images.githubusercontent.com/15198653/97420552-beb80e00-190b-11eb-9e71-1a69de38dc5e.png">

ok, po nějaké době kódování jsem si uvědomil, že rozhraní komponent je docela jednoduché, ale implementace stylu roste exponenciálně u každé výjimky stylu. Důvodem je, že toto jednoduché rozhraní nás přimělo implementovat polymorfní způsob, jak aplikovat styly. Rozhodně se mi to nelíbí a další řešení, které mi přijde na mysl, je oddělit Button a Odkazy sémanticky a podle stylu. Bude to tedy 4 komponenty:
- Link
- Button
- ButtonAsLink
- LinkAsButton

uvidime

**Comment by Erbenos** [comment]
Na kód jsem nekoukal, ale šachovat se 4 komponentami mi přijde nepříliš šťastné. Nemůže to být jedna komponenta, v tomto duchu?

```ts
interface ButtonCommonProps {
  size?: 'small' | 'base' | 'md' | 'lg' // base default
  variant?: 'primary' | 'secondary' | 'text' | 'cta' // 'primary' default, 'text' default when button has asLink
}

interface ButtonButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement>, ButtonCommonProps {
  asLink?: never
}

interface ButtonLinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement>, ButtonCommonProps {
  asLink: true
}

type ButtonProps = ButtonButtonProps | ButtonLinkProps
```

Použití:

```tsx
// Tlačítko se sémantikou odkazu (takže <a> tag)
<Button asLink href="https://github.com/"></Button>
// Tlačítko se sémantikou odkazu, vypadající jako tlačítko
<Button asLink type="primary" href="https://github.com/"></Button>
// Obyčejné tlačítko, takže <button>
<Button></Button>
````
