### ISSUE TITLE
Nová stránka Merchandising

### ISSUE THREAD

**Issue by jindrich-oukropec** [cesko-digital/web#668]
**Co**: Chceme komukoliv umožnit podpořit komunitu prodejem merche. Jsme domluveni s Czechdesign a Beclalel a tyto dva odkazy dát někam na web, dává mi smysl to dát k "Přispět".

**Proč**: Ne každý má miliony aby se stal finančním partnerem nebo prostor se teď zapojit do komunity. I tak může pomoci tím, že si koupí merch - u každého produktu bude uvedeno, kolik přesně posílá peněz do komunity.

**Jak**: V menu se změní "Přispět" na "Podpořit" a bude odkazovat na novou stránku "Podpořit". Stránka logicky nabídne 3 možnosti podpory - darujme, merch a batoh. S tím, že do budoucna můžeme přidat sekci k partnerům. Pokud nestihenem do 4/12 nasadit, lze změnit link "Přispět" na [linktr.ee/ceskodigital](linktr.ee/ceskodigital). 

Fot
**Kdy**: Nyní se vyrábí mikiny i batohy, budou tak za 2-3 týdny, kdy budeme produkty fotit. 
**Kdo**: Může to asi udělat kdokoliv v komunitě, kdo ví, jak na náš web, ale zhledem k času asi nestihneme najít a onboardovat dobrovolníka, ale rád pomůžu s vypsáním role a jejím obsazením kdyby náhodou...

Odkazy:
https://www.darujme.cz/projekt/1203553
https://shop.czechdesign.cz/ceskodigital/
http://www.becalel.cz/e-shop/batoh-digital/
https://airtable.com/shrTLixl0XVbyDm8G

Fotky Merche:
https://drive.google.com/drive/folders/1-Gjitk31HdS4iKUSyr12NsnDxKm08k7j

Fotky batohu:
 https://drive.google.com/drive/u/0/folders/1okq0surdEdGgM5-rZlEYXSRvN5db5sEB

**Comment by karmi** [comment]
To rozbalovací menu bych primárně nedělal — není to tak jinde v menu, jsou to běžné odkazy. Spíše by bylo lepší to uchopit více „od podlahy“, a místo odkazu _Darovat_, který vede rovnou na Darujme.cz, změnit tuto položku na něco jako _Podpořte nás_. Tento odkaz by pak mohl vést na nějakou souhrnnou stránku, která by obsahovala jak odkaz na Darujme (nebo widget), tak odkaz na stránku se seznamem partnerů, tak odkaz na tuto novou stránku s merchandising? Jak by to vyhovovalo takto?

**Comment by jindrich-oukropec** [comment]
@karmi super point, můžeme přetextovat "Přispět" na "Podpořit" a přesměrovat na stránku "podpořte nás", která bude jako merch (viz můj návrh) jen nahoře bude "pruh" s odkazem na darujme.cz? :-)

**Comment by jindrich-oukropec** [comment]
@zoul do zadání jsem doplnil linky (i na složku fotek na discu), ve [Figmě](https://www.figma.com/file/KagtaZEZL7lwIUaFsLdwuE/%3EC.D-%2F-Join?node-id=1%3A2&t=L0NOwNBOoxolq6Ft-1) jsou final texty i fotky. kdybys cokoliv potřeboval, dej vědtě. Moc děkuji!

**Comment by zoul** [comment]
Hotovo 🎉
