### ISSUE TITLE
Překlad celého webu do angličtiny přes Weglot

### ISSUE THREAD

**Issue by MartinaHabova** [cesko-digital/web#669]
Toto issue navazuje na PR https://github.com/cesko-digital/web/pull/666 od @martinwenisch.

Další kroky:

- [x] Najít editora (rodilého mluvčího) a korektora, aby zkontrolovali texty
- [x] Schválit překlady textů
- [x] Zkontrolovat celý web na preview
- [x] Nasadit do produkce
- [ ] Odladit technickou implementaci

**Comment by MartinaHabova** [comment]
- [ ] najít editora native speakra, aby projel texty
- [ ] najít korektora native speakra, aby zkontroloval texty
- [ ] schválení textů
- [ ] nasazení do produkce

**Comment by MartinaHabova** [comment]
Kopíruju z konverzace ze slacku:

se bude navyšovat ta verze skrz vysoký počet slov a v budoucnu přibývající obsah – máme teda ty nadbytečné překlady označovat jako zkontrolované namísto mazání? Aby se nám tak při synchronizaci neobjevily znovu?


M: Asi jo, udelejte to prosim takhle. Dekuju
-----
Na druhou stranu když ty názvy projektů přeložíme, může to být matoucí, když si o nich někdo bude třeba chtít dohledat víc informací a na Googlu jim to vyhodí nerelevantní odkazy... Protože ten projekt prostě bude existovat jen pod českým jménem. Tak vlastně nevím.


M: A kdyz je dame do zavorky v čj? - domluveno

**Comment by zoul** [comment]
Moje poznámky, budu průběžně aktualizovat:

* Martin přidával integraci Weglotu v ef89ea8d750ce90a2ae365828dbba0935fc2cb9a (základ) a 92963ade562f1b43684a0559b8527352b5636e5e (přepínač).

TODO:

* [ ] Zprovoznit anglickou verzi webu na en.cesko.digital
* [ ] Zahodit původní anglickou jednostránku
* [ ] Přidat přepínač mezi jazykovými verzemi
* [ ] Zkontrolovat, jestli nám lokalizace něco nerozbila, zejména na dynamičtější části webu (Portál dobrovolníka)
* [ ] Přidat banner o automatickém překladu?
