### ISSUE TITLE
Implementace responzivní kostry webu

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#67]
**Technologie:** React, TypeScript, Gatsby

V rámci #64 

Vytvořit stateless komponentu pro základní responzivní layout. Na větších rozlišeních by se obsah stránky měl vycentrovat, na nižších naopak získat co nejvíce prostoru. 

**Co je nutné vyřešit:**

- Kostra by měla sloužit pro obsah, hlavičku i patičku. Tyto sekce (i sekce obashu) mohou mít rozdílné barvy pozadí.
- Navrhnou vhodné rozhraní pro komponentu a její použití. (Dají se očekávat komponenty typu `pages/{main,projects}`, `{header,footer,content}`, `seo` atd.)

**Na co nezapomenout:** 

- Komponenta by neměla mít žádný stav
- Přidat dokumentaci (story) do Storybooku
- Odklonit se od větve `rework`

**Figma pro představu rozdílných barevných pozadí:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=16%3A72)

**Comment by pavelsuraba** [comment]
Beru to. 🙂
