### ISSUE TITLE
Nový formulář pro onboarding

### ISSUE THREAD

**Issue by karmi** [cesko-digital/web#673]
Součástí nových stránek pro zapojení se do komunity ("join") je i přepracovaný registrační formulář; grafický návrh [zde](https://www.figma.com/file/KagtaZEZL7lwIUaFsLdwuE/%3EC.D-%2F-Join?node-id=5165%3A44519).

Jednotlivá pole v první části formuláře nejsou ještě 100% odsouhlasena, ale to by implementaci nemělo bránit. Chceme téměř jistě odkaz na "web nebo profesní profil", a chceme přidat i geografickou lokaci (prozatím volný text).

Nejnáročnější součástí je zcela přepracovaný formulář pro uvádění dovedností. V nové podobě je tří-úrovňový:

1. Kategorie (_Vývoj_, _Marketing_, ...)
2. Dovednost (_React_, _Zpracování zvuku a videa_, ...)
3. Dosažená úroveň (_senior_, _junior_, ...)

To má za následek změnu databázového schématu. V současné chvíli preferujeme ukládat data v serializované podobě jako text, tedy např. `Vývoj / React (senior)`. Při zpětném načítání do formuláře (např. na stránce profilu) zajistí de-serializaci na jednotlivá pole samotná aplikace, včetně zpětné serializace. Pro práci v databázi lze využít fulltextové vyhledávání v příslušném poli.

Uživatel musí zvolit alespoň jednu kategorii. Při volbě kategorie se zobrazí seznam příslušných dovedností, z nichž může uživatel nepovinně vybírat. Při volbě určité dovednosti se zobrazí zaškrtávací pole pro dosaženou úroveň, kterou může uživatel nepovinně vybrat. Uživatel může vybrat více kategorií, v nich jednu a více dovedností, v nich jednu úroveň.

Formulář obsahuje volbu _Jiné_, kde může uživatel uvést libovolnou dovednost (prostý text).

Related: #660

**Comment by zoul** [comment]
Začínám si s tím hrát, budu si sem průběžně odkládat poznámky.

## Migrace dat

Jakmile stanovíme nový formát pro ukládání kompetencí (viz níže), bude potřeba migrovat data (tabulka [User Profiles](https://airtable.com/apppZX1QC3fl1RTBM/tblUmjkniqR4PUu5R/viwAHmRmBxdpyjixq?blocks=hide), sloupec `skills`). Součástí migrace musí být i úprava kódu, který se stará o změny kompetencí, což je kromě onboardingu ještě profil uživatele na https://cesko.digital/profile. (Současné UI v uživatelském profilu není kompatibilní s tím novým modelem kompetencí.) Zatím mě docela láká udělat tohle v samostatném PR jako první krok.

Co uděláme s tabulkou [Skills](https://airtable.com/apppZX1QC3fl1RTBM/tblUxJDLzJZkVI4pL/viwLkzurS4ZpSs3lm?blocks=hide)? Je tam hromada vazeb, já bych ji samozřejmě rád smazal, ale chtělo by to aspoň rychlou konzultaci na Slacku.

## Nový formát ukládání kompetencí

Příklady kompetencí, zatím bez závazné syntaxe, čistě brainstorming:

* `Vývoj`
* `Vývoj / Flutter`
* `Vývoj / Flutter / senior`
* `Vývoj; Marketing`
* `Vývoj; Marketing / copywriting`

Kritéria pro vhodnou syntaxi – jednoznačnost parsování, snadnost dotazování vzorci v Airtable, co dál? (WIP)

**Comment by zoul** [comment]
Podrobněji k migraci dat: V tabulce Skills jsem založil sloupec _Import As_, kde je řečeno, jak se má daný skill ze staršího systému importovat do nového (viz pohled [Data Migration](https://airtable.com/apppZX1QC3fl1RTBM/tblUxJDLzJZkVI4pL/viw6n5Ym6jRoTEddS?blocks=hide)). Pokud je daný skill uživatele v téhle konverzní tabulce, převede se podle ní. Pokud tam není, převede se aspoň hlavní kategorie, a to podle následující tabulky:

* Analýza → Vývoj
* Architektura → Vývoj
* Business → Projektové řízení
* Design zůstává
* Finance → Projektové řízení
* Lidské zdroje → Personalistika
* Management → Projektové řízení
* Marketing zůstává
* Vývoj zůstává

@karmi, můžeš se prosím podívat na tu [konverzní tabulku](https://airtable.com/apppZX1QC3fl1RTBM/tblUxJDLzJZkVI4pL/viw6n5Ym6jRoTEddS?blocks=hide), jestli ti tam dává všecko smysl?
