### ISSUE TITLE
Definice systému překladových klíčů a vybrání řešení pro Gatsby aplikaci

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#68]
**Technologie:** React, TypeScript, Gatsby

V rámci #64 

Web od začátku bude mít všechny texty v AirTable a bude pracovat s překlady. V rámci tohoto issue je nutné navrhnout systém překladů v AirTable (jedna nebo více tabulek), výsledné struktuře pro web (JSON) a systém použití v komponentách (využití Gatsby nástrojů, vlastní nástroj?). 

Datová služba pro zisk dat bude volána před samotným buildem a bude převádět AirTable data do JSON. Zatím není jasná podoba, ale lze si představit package.json script `generate:data` a `build`, který pak bude spouštěn manuálně pomocí GitHub Action. 

Řešením by ideálně měla být dokumentace pomocí Storybooku/README a použití překladu v nějaké komponentě (datový script, pokud neexistuje, může vytvořit jednoduchý JSON v ignorované složce). 

**Figma pro vizuální představu:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=16%3A72)

V případě nejasností nebojte se na mne obrátit. 🙂

**Comment by junekpavel** [comment]
Mohl bych se tohoto tasku klidně ujmout, případně i společně s #71. Přijde mi, že se tasky budou dost překrývat.

Napadá mě několik způsobů, jak tohle řešit. Záleží na tom, jak by měly jednotlivé jazykové mutace webu fungovat.

**Varianta 1** - buildění webu přímo v daném jazyku
Tato varianta by byla vhodná, pokud by každá mutace běžela na vlastní doméně (např. example.com, example.net, ... nebo example.com, en.example.com, ...). Web by se buildil pro každý jazyk zvlášť, všechny stránky by byly stejné. Při buildu by se zvolil jazyk, který se má použít.

**Varianta 2** - buildění pro všechny jazyky najednou
Před buildem by se z AirTable vytáhly všechny jazyky a pro každý by se vybuildilo HTML (např do podadresářů podle názvu jazyka). Jde vlastně o více zautomatizovanou první variantu.

**Varianta 3** - manuální překlady
Každá stránka by byla manuálně založena pro každý jazyk zvlášť. Pokud by se měly jednotlivé mutace více či méně lišit, jiná cesta asi nebude. Nevýhoda je, že při přidání nového jazyka by se muselo zasahovat do kódu (vytvořit stránku pro daný jazyk).

Možná se mi jeví poslední varianta jako nejjednodušší, vzhledem k velikosti projektu (2-3 stránky?). Navíc nepředpokládám, že by měly přibývat nové jazykové mutace nějak ve velkém (jestli vůbec).


Jinak co se struktury AirTable týče, asi se mi víc líbí varianta jenom s jednou tabulkou - první sloupec klíč, další sloupce jazyky. Bylo by to jednodušeji spravovatelné oproti více tabulkám, kde by se musela nějak validovat správnost klíčů.

**Comment by HormCodes** [comment]
Pavle, díky moc za prvotní research! 👍 

Variantu 1 bych vyřadil. Pokud jde o samotný routing, tak i s prefixem budeme muset počítat s anglickým slugem. Např. `/cs/projekty` a `/en/projects`, takže spíše otázka zní jaká je pravděpodobnost, že vznikne stejný slug pro obojí.

Spíše jako více důležité je nalezení způsobu, jakým způsobem bude probíhat build a vykreslování v jednotlivých komponentách.
