### ISSUE TITLE
Sundat inzerát v Marketplace při neaktivitě zadavatele

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#682]
Po nasazení bota na Marketplace je teď vidět, že někteří poptávající berou službu Marketplace spíš jako pasivní nástěnku, kam hodí nějaký inzerát a dál už se o něj nestarají, tj. nereagují včas/vůbec na doplňující dotazy od bota ve vlákně a dokonce třeba ani na nabídky dobrovolníků ve vlákně (!), [viz třeba tady](https://cesko-digital.slack.com/archives/CLVAH28P3/p1665412870059979).

To nejmenší, co bychom mohli udělat, je automaticky sundat poptávku s tím, že už není relevantní. Teď tam ve vlákně visí nezodpovězený dotaz od bota:

<img width="364" alt="bot" src="https://user-images.githubusercontent.com/95329/197474567-7c7f4b5f-c596-45bd-91c5-e2396b74e953.png">

Měli bysme to udělat tak, že pokud autor _x_ dní neodpoví, poptávka se nějak automaticky uzavře (ať už jako `expired`, nebo jako `cancelled`).

V obecnější rovině by pak bylo dobrý postující upozornit, aby reagovali ve Slacku a nebrali to jen jako jednosměrný komunikační kanál?

CC @GabiChl

**Comment by GabiChl** [comment]
Jojo, to je super bod a souhlasím určitě. díky za to Tome. g.

**Comment by zoul** [comment]
BTW když na to koukám, možná autoři původního postu neví, že se robot ptá jich. Takže první, nejjednodušší krok by mohlo být aspoň upravit textaci, aby tohle bylo zjevnější.

**Comment by GabiChl** [comment]
Tome a šlo by tam rovnou tagovat toho poptávajícího? (asi také může být problém, že ti, co se nahlásí do Slacku si nezapnou notifikace, takže to pak kontrolují po delší době). navrhuji změnit textaci třebas takto: 
_Ahoj @zoul , jak jste na tom? Podařilo se ti poptávku už obsadit, je ještě relevantní? Můžeš prosím zvolit odpovídající? Díky za update._ 
Nebo něco podobného? díky g

**Comment by zoul** [comment]
Tohle už nebude relevantní vzhledem k #946.
