### ISSUE TITLE
Poptávky z Marketplace se občas do databáze vkládají dvakrát

### ISSUE THREAD

**Issue by GabiChl** [cesko-digital/web#683]
ahoj @zoul 
začaly se nám zdrojovat zápisy - zatím ok, budu to mazat, ale chtělo by to asi opečovat. díky. 

<img width="843" alt="image" src="https://user-images.githubusercontent.com/97018838/197735525-80269cbd-6e08-4399-97ea-44013f00491e.png">
edit: tak to jsou nakonec 2 validní zápisy :) , tak uzavírám.

**Comment by zoul** [comment]
Tohle byl zrovna falešný poplach, ale jinak se fakt občas stane, že se tam něco vloží dvojmo, tak to znova otevřu a nechám ve hře.

**Comment by zoul** [comment]
Ještě máme teorii, že to dvojí vložení může být ve skutečnosti v pořádku – pokud se například stane, že někdo napíše do kanálu, všimne si chyby, příspěvek smaže a vloží znova. (Víme určitě, že tohle lidi občas ve Slacku dělají.) Bylo by například řešení, kdyby bot reagoval na smazání příspěvku?

**Comment by zoul** [comment]
Tohle už nebude relevantní vzhledem k #946.
