### ISSUE TITLE
Zobrazení členů týmu v rámci stránky projektu

### ISSUE THREAD

**Issue by GabiChl** [cesko-digital/web#687]
Bylo by fajn mít možnost zobrazit všechny členy týmu, kteří v průběhu času na projektu pracovali z tabulky Teams z AT web na podstránce pro konkrétní projekt. 
Souvisí s issue #638 Nová stránka O nás, kde by také byl stejným způsobem vylistován kmenový tým č.d.

**Comment by zoul** [comment]
S tímhle určitě počítáme a dlouhodobě k tomu směřujeme, nejprve novou tabulkou uživatelských profilů a následně tabulkou projektových týmů. Jedna s výhod bude v tom, že ta data budou konečně na očích, takže bude větší tlak na údržbu aktuálních dat. Technicky je to docela snadné a prototyp by mohl být klidně za hodinu – je ovšem potřeba dořešit soukromí uživatelů, přinejmenším jim dát možnost opt-outu. Už jsme řešili v #590, tohle je vlastně pokračování.

**Comment by anezkamll** [comment]
Na tohle téma jsme teď několikrát narazili s dobrovolníky a POs. Takže bych to určitě znovu ráda dostala do popředí zájmu.
Zkusím to otevřít, až se @zoul vrátí z dovolené.

**Comment by zoul** [comment]
Tohle teď budu programovat, zatím dva dodatečné postřehy:

* Ne u všech projektů máme rozumná data, takže by ten „boxík“ se zapojenými lidmi měl být opt-in, nejspíš nějakým příznakem v tabulce projektů.
* Až to bude hotové, ještě před mergem bychom to mohli/měli ukázat koordinátorům dotyčných projektů, aby nám řekli, jestli tam nejsou nějaké zásadní kiksy v datech. Přece jenom to bude poprvé, co s těmi daty takhle veřejně začneme pracovat.

**Comment by GabiChl** [comment]
> * Až to bude hotové, ještě před mergem bychom to mohli/měli ukázat koordinátorům dotyčných projektů, aby nám řekli, jestli tam nejsou nějaké zásadní kiksy v datech. Přece jenom to bude poprvé, co s těmi daty takhle veřejně začneme pracovat.
- tady by se hodilo mí možnost člena týmu vyřadit z publikace na web (tzn. SM nejen zkontroluje, zda je tým kompletní, ale prověří/odsouhlasí si s týmem, že chtějí být pod projektem na webu uvedeni). díky

**Comment by zoul** [comment]
Tenhle opt-out máme na straně uživatele, viz výše zmínku o ticketu #949. Klidně můžem udělat i tu možnost zapnout/vypnout zveřejnění u samotného týmového zapojení, ale dělal bych to pouze v případě, že po tom bude jasná poptávka, ať to nekomplikujeme zbytečně.

**Comment by anezkamll** [comment]
Dík, žes to našel, byla jsem si jistá, že to existuje. 
Možná už můžeme nějak začít kontrolovat ta data minimálně u živých projektů, co @GabiChl?

**Comment by zoul** [comment]
Podle mě vám můžu už zítra nahodit nějakou pracovní verzi, ve které půjde líp klikat než v Airtable.

**Comment by anezkamll** [comment]
Je to asi jedno, oni jsou zvyklí s tím pracovat. Máme tam ty public seznamy, takže by to mělo být v pohodě čitelné. Nepřidělávej si prácu.

**Comment by zoul** [comment]
O to nejde, bude to první věc, kterou udělám během implementace. Už je to k vidění, viz #951. První poznámky, když na to koukám:

* U [Ambasadorů](https://app-git-topic-display-teams-ceskodigital.vercel.app/projects/ambasadori-digital) ta týmová zapojení nějak nesedí, ne? Čekal bych tam Jindru jako koordinátora a pár dalších lidí jako ambasadory.
* Občas jsou tam těch lidí fakt mraky, třeba u [Inkluze](https://app-git-topic-display-teams-ceskodigital.vercel.app/projects/digitalni-inkluze), tak je otázka, jak pracovat s tou grafickou podobou, aby to nebylo zbytečně roztahané. Lze řešit i ex post, přijde mně, že se to designérům:kám líp dělá podle reálných dat.
