### ISSUE TITLE
Implementace komponenty pro kartu projektu

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#69]
**Technologie:** React, TypeScript, Gatsby

Vytvořit stateless komponentu pro kartu projektu pro stránku přehled projektů (#64). Komponenta by měla využít tlačítko z #65.  

Předpokládaný vstup: 

- Název projektu
- Popis
- Cover
- Logo
- Odkaz na detail
- Tagy (zatím pouze jako text)

**Na co nezapomenout:** 

- Komponenta by neměla mít žádný stav
- Přidat dokumentaci (story) do Storybooku
- Odklonit se od větve `rework`

**Figma:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=40%3A6058)

V případě nejasností nebojte se na mne obrátit. 🙂 

<img width="421" alt="Screenshot 2020-10-19 at 21 15 57" src="https://user-images.githubusercontent.com/10332399/96501223-5fddff00-1250-11eb-878e-37d9f3389dab.png">

**Comment by Haaxor1689** [comment]
Toto si rad zoberiem :)
