### ISSUE TITLE
Postupné odesílání uvítacích zpráv na Slacku v rámci onboardingu

### ISSUE THREAD

**Issue by GabiChl** [cesko-digital/web#691]
Jakmile se nový uživatel přihlásí do Slacku, tak mu jde nyní automatizovaná zpráva [odtud](https://github.com/cesko-digital/web/blob/56baf02e1267fd2cfde8e1b23eea24cd3200d98c/content/welcome.txt). 

Nově budeme potřebovat odesílat postupně takto několik zpráv v rámci onboardingu (plánují se cca 3 GeetBot zprávy a poté ještě další SlackBot Series (tipy ke komunitě či k práci na Slacku). 

Nově navržené texty a časovou posloupnost dodá @Teryii 

Díky moc, Gábina

**Comment by zoul** [comment]
[Dokument s texty je tady](https://docs.google.com/document/d/13-Qj6ZhrFC2KkXOhh_5Bvtt_sNkStQg-0fWCWZiWcro/edit?usp=sharing), ale ještě je potřeba počkat, až budou texty hotové.

**Comment by GabiChl** [comment]
> [Dokument s texty je tady](https://docs.google.com/document/d/13-Qj6ZhrFC2KkXOhh_5Bvtt_sNkStQg-0fWCWZiWcro/edit?usp=sharing), ale ještě je potřeba počkat, až budou texty hotové.

@zoul takže GreetBot texty nachystány a revidovány, pardón, že to tak trvalo. 
Sekvence odesílání Greetbotů je dle Gabrielina rozvoje 0,3,6,9, 14 a 20 :)
Kdyby se ti něco nezdálo, tak se prosím ozvi. díky moc

**Comment by GabiChl** [comment]
> Dáme tam podmínku, že musí jít o účty založené až po nasazení téhle funkce? Aby ti uživatelé dostali celou posloupnost od začátku. Nebo nám nevadí, že někdo, kdo si účet založil třeba před týdnem, uvidí jen zprávy pro den 14 a 20?

ahojda, jo to je dobrý nápad, díky za to - určitě není dobré, aby  jim chodila jen část Greetbotích zpráv. 
A chceme ještě nějak posunout tu sekvenci - greets ve Slacku je na začátku po 3dnech, ale od welcome emailingu 2. a 3. se to liší jen o 1 den, tak jestli tam dává smysl mít mezi emailingem a botíma zprávama větší rozestup?
