### ISSUE TITLE
Statistiky návštěvnosti příležitostí

### ISSUE THREAD

**Issue by MartinaHabova** [cesko-digital/web#716]
poptáváme lepší integraci analytiky (Plausible) a databáze, abychom třeba uměli snáz říct, jaký byl zájem o kterou inzerovanou pozici. 

Píše:
…jak o tom teď přemýšlím, tak bych potřebovala mít každý měsíc přehled:
všechny otevřené pozice z portálu +
kolik návštěvníků každá z nich měla +
asi by byl zajímavý i bounce rate +
top 3 source - odkud přišlo nejvíce návštěvníků
Já jsem nad něčím podobným [už přemýšlel] - (https://github.com/cesko-digital/web/discussions/493). 

Technicky to nevypadá složitě (jednou za čas se pustí bot, který vytahá data z API Plausible a nacpe je do databáze), takže jde hlavně o to zadání.

**Comment by zoul** [comment]
Potřebujeme ještě probrat to zadání – technicky je víc možností, záleží na našich byznysových potřebách. [Řešíme ve Slacku](https://cesko-digital.slack.com/archives/CHG9NA23D/p1674641779723349), pak se sem vrátím s výsledkem.

**Comment by zoul** [comment]
Domluvili jsme se, že nepotřebujeme ani tak nutně statistiky v databázi, jako spíš report návštěvnosti příležitostí a zdrojů návštěvnosti pro jednotlivé příležitosti. Takže jsem udělal endpoint, kde jsou ty statistiky návštěvnosti (https://cesko.digital/api/stats/opportunities), a z něj se data načítají do Datawrapperu (https://www.datawrapper.de/_/YTQQr/). Ještě se později vrátím k těm zdrojům návštěvnosti.

**Comment by zoul** [comment]
Dneska jsem přidal [zdroje návštěvnosti](https://www.datawrapper.de/_/5SpWg/) a beru to za hotové, ještě počkám na zpětnou vazbu ve Slacku a můžeme zavřít?
