### ISSUE TITLE
Rozesílání notifikací na nově otevřené role na projektech

### ISSUE THREAD

**Issue by anezkamll** [cesko-digital/web#721]
**Cíl:** Dostat informace o nově otevřených rolích co nejefektivnější cestou k dobrovolníkům 
Rozpracovává jednu z položek #688 

Jak by to mohlo ideálně vypadat: 
https://miro.com/app/board/uXjVPxeYSuk=/
V profilu dobrovolníka by přibyla záložka Notifikace, kde by bylo možné si zatrhnout, jaké notifikace chci odstávat - o nově vypsaných rolích, o nových akcích, o nových příchozích projektech,...
Zároveň bych měla krom dovedností možnost si v profilu vyplnit témata, která mne zajímají.
Na PD někdo přidá novou roli. Počítáme s tím, že by ji ještě nějaký čas vypěkňoval.
Po dvou (čas na vypěknění) dnech sepne automatický mechanismus rozesílání rolí - v případě, že by nově vypsaná role splňovala kritéria, na základě kterých chci dostávat notifikace, odeslal by se automaticky mail s upozorněním na nově vypsanou roli.

**Jak by mohl vypadat pilot:**
- na PD přibude nová role
- po 2 dnech od zveřejnění (automatický čas na pimping role) odejde notifikace s upozorněním na novou roli všem dobrovolníkům v databázi
- součástí textu je opt-out pro tento typ notifikací

Co je potřeba vymyslet:
- skladbu/formátování notifikace (text, odkazy)
- jak udělat opt-out
- jak sbírat zpětnou vazbu, zda maily nechodí moc často

Jak by mohl vypadat druhý krok po pilotu:
- segmentace notifikací dle top level skills (bude třeba provázání dovedností v profilu a tagů u rolí)

TODO:

Menší věci můžeme odškrtávat rovnou tady, větší věci můžeme převést na samostatný ticket a odkázat na něj tady v seznamu. MVP verze:

* [x] Správa odběru v uživatelském profilu
* [x] Samotné rozesílání mailů
* [x] Vyřešit opt-out

Později:

* #749
* #750
* #751
* #752

**Comment by zoul** [comment]
Chvíli jsem nad tím přemýšlel a odložím si sem své „produktové“ poznámky:

* Můžeme lidem jen tak posílat maily, o které si explicitně neřekli? Jak ten opt-in případně zařídit? Říct všem, že si to můžou zapnout v profilu, bude mít relativně bídnou konverzi. (Ale IMO je to lepší varianta než posílat nevyžádané maily.) Asi si dovedu představit i nějaký odkaz pro instantní opt-in, který bychom mohli rozeslat například v rámci měsíčního newsletteru? (Nejsem si tím stopro jist technicky, ale asi by to šlo.)
* Na později: Pokud pro tohle uděláme nějaké UI v uživatelském profilu na webu, chtěli bychom to přidat i do onboardingu? A pokud jsem přihlášený, nechtěli bychom nějakou stručnou variantu toho UI i na [přehledu příležitostí](https://cesko.digital/opportunities)?
* Instantní opt-out pomocí odkazu by měl jít. Přinejmenším prostě kliknu a dostanu se na stránku, která mně řekne, že jsem úspěšně odhlášený. V lepším případě tam bude undo/redo a v ještě lepším případě to pozná, pokud jsem přihlášený k našemu webu, a nechá mě to nastavení spravovat rovnou tam v profilu.
* Občas někdo nasype do databáze několik pozic najednou, nepřijde mně vhodné posílat několik mailů (nejspíš ani v MVP verzi). Asi abychom tedy počítali s tím, že těch pozic může být v mailu víc?

**Comment by anezkamll** [comment]
opt-in vs opt-out
- u opt-in píšeš "Říct všem, že si to můžou zapnout v profilu", i tuhle informaci bys ale k těm "všem" musel nějak dostat, nevidím tam už rozdíl v opt-out - poslat takhle notifikaci na první pozici s infem Spouštíme novou funkcionalitu, notifikace o otevřených rolích. Svoje preference můžete upravit v PD" a odkaz
- pokud to jen hodíme na Slack, nebude to mít o nic větší efekt, než když tam zveřejňujeme samotné role, takže se mineme účinkem, který by notifikace měly mít
- nejčistší cestou je v tomto NL, ale tam by to muselo být jako hot news hnes na začátku, aby si to lidi přečetli

UI v uživatelském profilu na webu
- určitě bych přidala do onboardingu ("chci dostávat notifikace o nových příležitostech v projektech" nebo tak něco)
- napadlo mě jít ještě o kus dál - bavili jsme se nad mým rozkresem o tom, že bych chtěla mít notifikace napojené na top level skills, ale i tohle by mohl být volitelný aspekt - chci dostávat notifikace o nových rolích plošně / jen pro moji odbornost
- dát to i na přehlde příležitostí se mi líbí
- side note, na kterou vytvořím separátní issue - přidala bych odkaz na přehled příležitostí na stránku o projektech hned do úvodu

několik pozic najednou
- asi víc odkazů v notifikaci, víc mailů mi taky nepřijde OK, je pak otázka, zda budeme dále pracovat s top levelem a jak by to měnilo situaci a komplikovalo celou exekuci

**Comment by zoul** [comment]
Tu debatu o opt-in/out jsem [přehodil do Slacku](https://cesko-digital.slack.com/archives/CHG9NA23D/p1675154298628859), můžeme to tam pořádně probrat a vrátit se sem s výstupem, OK?

Jinak jsem do úvodního popisu ticketu přidal seznam věcí, které je potřeba udělat. V rámci tohoto ticketu navrhuju vyřešit nějakou MVP verzi, tedy opt-in, opt-out, správa v uživatelském profilu a samotné rozesílání; následně pak můžeme samostatně prioritizovat a vyřešit ty další věci – nastavení notifikací během onboardingu, správa notifikací v přehledu příležitostí, možnost filtrování podle kompetencí, cokoliv dalšího. OK?
