### ISSUE TITLE
Proklik na Příležitosti k zapojení ze stránky Projekty

### ISSUE THREAD

**Issue by anezkamll** [cesko-digital/web#724]
V rámci úvah nad lepším obsazováním rolí na projektech jsme s Romanou a Jindřichem Krásným došli k tomu, že nám chybí na stránce https://cesko.digital/projects očividná informace sdělující příchozímu, že do projektů se lze zapojit. 
Prokliky na obsazované role jsou na podstránkách jednotlivých projektů, ale přišlo by nám dobré, kdyby hned v úvodním textu byl proklik na Příležitosti k zapojení (https://cesko.digital/opportunities).
Šlo by přidat čistě textově, ale možná by bylo hezké i tlačítko? tlačítko :grin: 

Moje představa: 
Na text "Díky expertnímu dobrovolnictví dokážeme dosáhnout velkých věcí a měnit život v Česku k lepšímu. Podívejte se, jak to děláme." by navazovala další věta ve smyslu "Chcete pomáhat s námi? Podívejte se na aktuální příležitosti." Buď s proklikem z textu, nebo s tlačítkem :woman_shrugging:

**Comment by zoul** [comment]
Přidal jsem pull request, nějak takto?
