### ISSUE TITLE
Statická patička na blogu pro tag "newsletter"

### ISSUE THREAD

**Issue by lukasnavesnik** [cesko-digital/web#728]
Terka Gagnon řešila partnerská loga i v newsletteru na blogu. Což nebude problém. Řeším formu:

Buď to tam budu každý měsíc cpát manuálně a nebo mám otázku, jestli je realizovatelné mít předpřipravenou patičku, která se k tomu hodí automaticky, pokud to bude mít tag "newsletter". 

Nechám si poradit možnosti. Jak bys to viděl, @zoul? Díky!

**Comment by zoul** [comment]
Nachystat nějakou standardizovanou patičku není problém.

Dejme tomu, že bys jen někam vložil předchystaný tag:

```
{% partner_footer /%}
```

…a on by měl vygenerovat ta loga, což dává nejlepší smysl z pohledu UX. Která loga kdy vybere? Protože ti partneři se v čase mění. Je OK mít všude jen ty aktuální, třeba i u historických textů? Anebo bychom chtěli mít u každého textu poděkování právě těm partnerům, které jsme měli v době jeho vydání?

A konkrétní dotaz zní, jak to budeš řešit v Ecomailu. My jsme chtěli ten newsletter co nejvíc generovat automaticky (viz ten editor na https://newsletter.cesko.dev), aby šly právě takovéhle věci jako patička vygenerovat strojem a nestrávils u toho mládí ruční prací. Nepřeváděli jste vy ale ten newsletter zpátky na ruční sazbu v Ecomailu?

**Comment by lukasnavesnik** [comment]
Super, díky za reakci! 

Co se týče přístupu k relevantním logům partnerů - to je otázka na @MartinaHabova. Asi by mi dávalo smysl mít tam loga, která byla aktuální v době vydání toho newsletteru, tím by jsme se ale připravili o tu možnost používat ten předchystaný tag, pokud by to nešlo pošéfit třeba nějakým "verzováním" - {% partner22_footer /%} /  {% partner23_footer /%}, atd. 

Ecomail se přesunul zpátky z jednoduchého generování přes editor na "mravenčí" práci v šabloně. Za účelem "zbeautifulizování" po vizuální stránce jsme se holt rozhodli, že bude šablona, kam já hodím texty. Takže od ledna už blogová verze ≠ mailová verze. Tudíž není potřeba řešit :)

**Comment by zoul** [comment]
Asi to bude ještě na pár komentářů tam a zpátky, než si ujasníme zadání, tak jsem přehodil debatu [do Slacku](https://cesko-digital.slack.com/archives/CHG9NA23D/p1675950653757579) a sem se vrátíme, až bude jasnější zadání.

**Comment by zoul** [comment]
Pokračujeme tady: https://github.com/cesko-digital/blog/issues/467.
