### ISSUE TITLE
Implementace komponenty karty "Jsem dobrovolník"

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#73]
**Technologie:** React, TypeScript, Gatsby

V rámci #64 

Vytvořit stateless komponentu dle designu s předpokládaným vstupem: 

- Název
- Popis
- Cover
- Odkaz na Slack

Komponenta by měla využít komponentu tlačítka z #65. 

**Na co nezapomenout:** 

- Komponenta by neměla mít žádný stav
- Přidat dokumentaci (story) do Storybooku
- Odklonit se od větve `rework`

**Figma:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=40%3A6058)

V případě nejasností nebojte se na mne obrátit. 🙂 

<img width="250" alt="Screenshot 2020-10-22 at 20 35 55" src="https://user-images.githubusercontent.com/10332399/96915688-d96f2a80-14a6-11eb-8173-35b9918d479d.png">

**Comment by mzadrazi** [comment]
Měla bych zájem o tenhle task. S Reactem zkušenosti mám, akorát si budu muset doplnit znalost TypeScriptu a Gatsby, takže mi to možná zabere o něco víc času než ostřílenému matadorovi ;). Pokud to není na překážku, ráda se toho ujmu.

**Comment by mzadrazi** [comment]
**Pro info**
- work in progress tady: https://github.com/mzadrazi/web/tree/feature/rework/pane-volunteer

Čekám na tyto pull requesty:
- [#77 - tlačítka](https://github.com/cesko-digital/web/pull/77)
- [#86 - nastavení relativních cest](https://github.com/cesko-digital/web/pull/86)
- [#88 - oprava linteru](https://github.com/cesko-digital/web/pull/88)
