### ISSUE TITLE
Lepší prokliky v sekci Zapoj se na stránce projektu

### ISSUE THREAD

**Issue by GabiChl** [cesko-digital/web#732]
V rámci jednotlivých stránek projektů (př. https://cesko.digital/projects/volebni-kalkulacka) je sekce Zapoj se, která by se mohla chovat podle stavu přihlášení – přihlášené uživatele by to mělo poslat do hlavního kanálu projektu a nepřihlášeným by to mělo nabídnout join/from  a v rámci toho doprovodného textu upravit odkaz "jak fungujeme" na join. 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/97018838/218032224-2f5128d0-717b-4a77-8a16-3df41c8b8183.png">

**Comment by zoul** [comment]
V 9e48e5366dd2bfde7610aa274d62b6a24aca6d75 jsme tenhle celý boxík nahradili jiným. Beru jako hotové, kdybychom se chtěli vrátit k tomu konceptu prokliku na projektový kanál, tak se ozvi, Gábi. Díky.
