### ISSUE TITLE
Implementace komponenty pro kartu "Mám nápad na projekt"

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#74]
**Technologie:** React, TypeScript, Gatsby

V rámci #64 

Vytvořit stateless komponentu dle designu s předpokládaným vstupem: 

- Název
- Popis
- Ikona
- Odkaz na Slack

Komponenta by měla využít komponentu tlačítka z #65. 

**Na co nezapomenout:** 

- Komponenta by neměla mít žádný stav
- Přidat dokumentaci (story) do Storybooku
- Odklonit se od větve `rework`

**Figma:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=40%3A6058)

V případě nejasností nebojte se na mne obrátit. 🙂 

<img width="208" alt="Screenshot 2020-10-22 at 20 43 10" src="https://user-images.githubusercontent.com/10332399/96916008-3d91ee80-14a7-11eb-9e42-2279fa30506d.png">

**Comment by patrikbraborec** [comment]
Ahojte, rád bych zkusil udělat tento task. S reactem i typescriptem mám zkušenosti. S gatsby jsem zatím nedělal, ale myslím, že to nebude problém. :) Díky!
