### ISSUE TITLE
Změna věty na join kvůli GDPR

### ISSUE THREAD

**Issue by jindrich-oukropec** [cesko-digital/web#744]
Ahoj na základě rady právníků je třeba změnit text na join u dvou zaškrtávacích checkboxů: 

Byl jsem informován, jak bude Česko.Digital při vzájemné spolupráci a pro zajištění transparentnosti zpracovávat mé [osobní údaje](https://docs.google.com/document/d/11rDJov4KYtX05zuHgGvq58y1ar6yK7V1cbF-xZ7F-TQ/edit).

[Zásady přístupu k datům](https://docs.google.com/document/d/17rMYagWWIP_OIy4c9XfklkyamegLHkXR/edit) mám přečtené a zavazuji se k jejich dodržování.

**Comment by zoul** [comment]
My na webu používáme ty zkrácené odkazy https://cesko.digital/go/privacy (zpracování osobních údajů) a https://cesko.digital/go/gdpr (GDPR). Vedou na správné dokumenty? Pokud ne, měli bychom ty zkratky aktualizovat. Díky!

**Comment by jindrich-oukropec** [comment]
Ahoj, díky moc za info. Mělo by to být následovně (koukám, že jsem tam dal špatný odkaz, pardon), napravuji:

Byl jsem informován, jak bude Česko.Digital při vzájemné spolupráci a pro zajištění transparentnosti zpracovávat mé [osobní údaje](https://cesko.digital/go/privacy).

[Zásady přístupu k datům](https://cesko.digital/go/gdpr) mám přečtené a zavazuji se k jejich dodržování.

Takže:
odkaz https://cesko.digital/go/privacy funguje dobře!
a https://cesko.digital/go/gdpr je třeba přesměrovat na toto: https://docs.google.com/document/d/17rMYagWWIP_OIy4c9XfklkyamegLHkXR/

moc děkuji za pomoco!

**Comment by zoul** [comment]
Texty jsem aktualizoval ([mrkni](https://cesko.digital/join/form)), ale ten nový odkaz pro GDPR není volně dostupný, takže jsem zatím nechal ten starý. Pokud ho mám aktualizovat, dej mně prosím nějaké veřejné dostupné URL. Díky!

**Comment by jindrich-oukropec** [comment]
@zoul moc se omlouvám, dokument je nově věeřejný, prosím o jeho zanesení:
URL:
https://docs.google.com/document/d/17rMYagWWIP_OIy4c9XfklkyamegLHkXR/edit
Kam ho zanést:
https://cesko.digital/go/gdpr

**Comment by zoul** [comment]
Hotovo!

**Comment by jindrich-oukropec** [comment]
@zoul zabiješ mě? V rámci diskuse o názvu rolí se mi nelíbí to "byl jsem informován", co holky?!
Šlo bý tam prosím místo toho dát jen "Vím, ..."
Finální text by byl tedy: Vím, jak bude Česko.Digital při vzájemné spolupráci a pro zajištění transparentnosti zpracovávat mé [osobní údaje](https://cesko.digital/go/privacy).*

Omlouvám se za změny!

**Comment by jindrich-oukropec** [comment]
Děkuj moc!
