### ISSUE TITLE
Vytvoření dalšího end pointu pro reporting v Datawraperu/ Newcomers endpoint

### ISSUE THREAD

**Issue by GabiChl** [cesko-digital/web#745]
ahoj Martine, 
takže tady zkouším sepsat zadání, snad to bude srozumitelné :) 

Newcomers endpoint: 
**Zadání:** Chceme sledovat trend počtu nově příchozích, kdy můžeme pak lépe sledovat trend vůči aktivitám, které č.d v daném čase provádí a také obecně vysledovat “sezónnost” příchozích. V dalším kroku by bylo fajn mít vztáhnuté k příležitostem a eventům, které č.d registruje také v Airtable. 
**Datový zdroj:** v Airtable bázi "Volunteer management", vzít záznamy z tabulky "User Profiles", kde state = "confirmed" - ty si zasumovat za jednotlivé roky a měsíce a výstup pak odeslat.
 (pozor Datawrapper neumí sumovat nenumerickou hodnotu, takže je potřeba nachystat ten výstup tak, aby už přišly hodnoty sesumované)
**Zobrazení datového výstupu:** příklad najdeš [tady](https://www.datawrapper.de/_/kzPvN/) , ale nebráním se jakémukoli vylepšení či jinému grafickému zobrazení :). Jak jsem říkala, nejsem v té analytice tak kovaná. 

Příklad toho, jak to psal @zoul  najdeš tady: 
Pro lepší představu [tady](https://github.com/cesko-digital/web/tree/master/pages/api/stats) máme nějaké stávající statistické endpointy vyvinuté a [tady](https://www.datawrapper.de/_/fDpOz/) je příklad grafu, který se z takového endpointu generuje.

Domlouvali jsme se, že termínově by bylo ideální to zkusit připravit během 14ti dní (jen teda ten týden od 13. budu na horách, tak nebudu k dispozici)

Díky, díky a kdyby bylo potřeba, tak se neváhej zeptat , Gábina

**Comment by pionl** [comment]
@GabiChl omlouvám se za pozdní reakci, vše je jasné, měl jsem to teď divoké 👍

Připravil jsem API endpoint, který pomocí "query" parametrů můžete konfigurovat. Ve výchozím režimu vrací všechny roky od měsíce/roku, ve kterém je 1 reg. uživatel do měsíce/roku kde je poslední uživatel. Automaticky se doplňují měsíce, kde není žádný uživatel registrován.

- Pokud chci tedy zobrazit graf od ledna do prosince, stačí poslat `?fill=true` parametr.
- Pokud chci zobrazit pouze konkrétní rok tak stačí poslat `?year=2022`.
- Pokud chci zobrazit pouze tento rok tak stačí poslat `?year=now`.
- Pokud chci zobrazit pouze tento předchozí rok tak stačí poslat `?year=previous`.
- Pokud chci zobrazit od daného roku tak stačí poslat `?from=2022`
- Pokud chci zobrazit do daného roku tak stačí poslat `?to=2023`
- Parametry `from/to` podporují `now/previous` hodnoty

**Příklady:**

- `/api/stats/trends/new-comers` - Vrátí všechny roky podle měsíce.
- `/api/stats/trends/new-comers?fill=true`  - Vrátí všechny roky podle měsíce od ledna / do prosince.
- `/api/stats/trends/new-comers?year=2023`  - Vrátí měsíce roku 2023 (aktuálně zobrazí leden až březen)
- `/api/stats/trends/new-comers?year=2023&fill=true`  - Vrátí měsíce roku 2023 (zobrazí leden až prosinec, kdy od dubna budou 0)
- `/api/stats/trends/new-comers?from=2022&to=2023`  - Nyní vrací leden 2022 až březen 2023
- `/api/stats/trends/new-comers?from=2022&to=2023&fill=true`  - Nyní vrací leden 2022 až prosinec 2023 (kdy od dubna 23 budou 0)
- `/api/stats/trends/new-comers?year=now` - Vrací pohled aktuální rok - není potřeba každý rok upravovat graf
- `/api/stats/trends/new-comers?from=previous&to=now` - Vrací pohled předchozí / aktuální rok - není potřeba každý rok upravovat graf

Připravil jsem to tak, že nebude zásadní problém možnost udělat sumarizaci dle "roků" / "měsíců" (to teď máme) / "dnů". Například můžeme pak udělat "pohledy" (posledních 30 dnů, poslední X dnů apod). Staří říct a rozšíříme to.

Výsledné data jsem zatím manuálně dal do tohoto [grafu](https://app.datawrapper.de/chart/M1Dm2/visualize#refine). Až bude povolený deploy tak to nasadím :)

---

Graf s propojením eventů: 

zde bych potřeboval vědět odkud to brát a jak "to" budete chtít napojit (a jaké sloupce přidat apod).

--- 

@zoul 

- můžeš povolit deploy at to můžeme napojit a vyzkoušet v datawrapperu?
- Připravil jsem kód tak, aby se "trend" statistiky dal generovat i pro jiné zdroje
- Nepoužil jsem stejný způsob zpracování dat (chainování filter/map/filter) jak již máte v code base, je tam dost řádků takže jsem šel z mého pohledu čitelnějším a rychlejším řešení (1 foreach s early "continue") :)
- Napsal jsem testy až na ten trend "writer" - tady počkám až schválíš kód a rád je dopíšu
- Všiml jsem si, že ostatní stats API nevrací kódování 
- Připravil jsem metody na zapisování CSV stats, jestli chceš můžu upravit existující API aby je použila (zamezí dupl. kódu).

**Comment by pionl** [comment]
API je funkční zde: https://web-6powkhv9c-ceskodigital.vercel.app/api/stats/trends/new-comers?year=2022&fill=true

Graf jsem na toto napojil :)

**Comment by pionl** [comment]
Jasně 💪

**Comment by pionl** [comment]
Produkce bude vypadat takto: https://cesko.digital/stats/trends/new-comers?year=2022&fill=true

**Comment by zoul** [comment]
Tohle je hotové, můžeme zavřít? Díky!
