### ISSUE TITLE
Implementace patičky webu

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#75]
**Technologie:** React, TypeScript, Gatsby

V rámci #64 

Vytvořit komponentu dle designu. Komponenta nemusí mít žádný vstup, ale je nutné počítat s překlady (#68).

Komponenta by měla využít komponentu tlačítka z #65. 

**Figma:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=40%3A6058)

V případě nejasností nebojte se na mne obrátit. 🙂 

<img width="1120" alt="Screenshot 2020-10-22 at 20 45 17" src="https://user-images.githubusercontent.com/10332399/96916379-c741bc00-14a7-11eb-8611-4b88d2e1ed11.png">

**Comment by Erbenos** [comment]
Já si to vezmu.

**Comment by Erbenos** [comment]
@HormCodes Prosím tě, kam mám odesílat ten e-mail, co uživatelé zadjí přes vstup? Mám si to pamatovat třeba pro danou session a neukazovat jej znovu, jestliže jej uživatel již zadal?

**Comment by Erbenos** [comment]
Blokují mě jen ta akce na submit a #65 , texty můžu zatím hodit staticky do nějakého slovníku, než se vymyslí mechanismus překladů.

**Comment by HormCodes** [comment]
@zoul, měl bys info ohledně přihlašování do newsletteru pro @Erbenos? Sám nevím, co používáme a jakým způsobem dle toho by měla vypadat integrace.

**Comment by zoul** [comment]
Používáme Ecomail, [mají podrobný návod na integraci](https://intercom.help/ecomail/cs/articles/66568-pouziti-a-nastaveni-vlastniho-formulare). Pro integraci je potřeba název účtu, což je `ceskodigital`, ID seznamu kontaktů, což je `2`, a ID účtu, což je `2bb287d15897fe2f9d89c882af9a3a8b`. Takže celé URL pro POST by mělo být:

```
https://ceskodigital.ecomailapp.cz/public/subscribe/2/2bb287d15897fe2f9d89c882af9a3a8b
```

Kdyby bylo ještě něco potřeba, například kvůli testování, tak jsem k dispozici.

**Comment by Erbenos** [comment]
Super, tlačítka už se mergla, tak to přes víkend pořeším.

**Comment by Erbenos** [comment]
#98
