### ISSUE TITLE
Implementace hlavičky webu

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#76]
**Technologie:** React, TypeScript, Gatsby

V rámci #64 

Vytvořit komponentu dle designu. Komponenta nemusí mít žádný vstup, ale je nutné počítat s překlady (#68), tj. zatím lze texty odkazů extrahovat do JSON (viz [patička](https://github.com/cesko-digital/web/pull/98/files#diff-faef2b618b72c2281b1172f24b85fe1883fc23bc61dd32ddfad8a8ecf3fe53c0R23)).

Komponenta by měla využít existující komponenty tlačítka (#65) a layoutu (#67). 

**Figma:** [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=40%3A6058)

V případě nejasností nebojte se na mne obrátit. 🙂 

<img width="905" alt="Screenshot 2020-11-18 at 18 16 47" src="https://user-images.githubusercontent.com/10332399/99564072-443e5380-29ca-11eb-8c85-6861f879e4a7.png">

<img width="373" alt="Screenshot 2020-12-02 at 17 48 58" src="https://user-images.githubusercontent.com/10332399/100903908-b92f8400-34c6-11eb-9732-1ab7e4ed0533.png">

**Comment by Tchomasek** [comment]
Beru si to
