### ISSUE TITLE
Přidat podporu HTTPS pro trackovací doménu Ecomailu

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#776]
Ecomail přesměrovává odkazy v našich newsletterech přes takzvanou „trackovací doménu“ mailtrack.cesko.digital, aby mohl sledovat proklikovost odkazů. Bohužel je ta doména momentálně jen na HTTP, nikoliv na HTTPS, takže některé prohlížeče při tom přesměrování zobrazí zlé varování; velmi pravděpodobně na tom ztrácíme nějaké konverze. Ecomail na té doméně naštěstí nějak umí zařídit HTTPS, [tady je návod](https://support.sparkpost.com/docs/tech-resources/enabling-https-engagement-tracking-on-sparkpost), ještě jsem na to nekoukal.

**Comment by zoul** [comment]
Luke, kdy půjde další velký newletter, prosím?

**Comment by lukasnavesnik** [comment]
@zoul Dneska půjde na komunitu pozvánka na narozeniny, ale tam bude proklik jen na Airtable, to by snad nemělo vadit? 

Další newsletter pak půjde 12/5.

**Comment by zoul** [comment]
Ono to bude zlobit u všech odkazů bez rozdílu. Doménu jsem nastavil (klik.cist.digital), ale ještě řeším, jak Ecomailu vysvětlit, že má s ní používat HTTPS. A pak bude potřeba na ni přepnout ([tady](https://ceskodigital.ecomailapp.cz/account/domains)) a především to otestovat.

**Comment by lukasnavesnik** [comment]
Už jsem so toho kliku všiml :D Když si pošlu testovací mail, tak to totiž udělá tohle a nevím, jestli když to odešlu, tak to bude fungovat nebo ne. 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/89539759/233336574-f3d1d390-a83c-4437-91b1-8cf5efc68ad8.png">

**Comment by zoul** [comment]
Narazil jsem na totéž, zatím tomu nerozumím.

**Comment by lukasnavesnik** [comment]
Hm, tak to nefunguje 😬 Poslal jsem zkoušku na testovací seznam, kde jsem jen já. A hodí to stejnou chybu.

**Comment by zoul** [comment]
Supr, díky za test. Dořeším, mezitím můžeme zůstat u té staré domény.

**Comment by lukasnavesnik** [comment]
A já budu kontrolovat, zda má odkaz https 😄 Díky!

**Comment by zoul** [comment]
Je to tam 🚀
