### ISSUE TITLE
V profilu na PD nemám aktivní výběr možností v záložce Newslettery

### ISSUE THREAD

**Issue by anezkamll** [cesko-digital/web#777]
V rámci záložky Newslettery mi nefunguje zaškrtávátko možností - i boxy jsou zašedlé, jako by vůbec nebyl výběr aktivní.
Nepomohl refresh, nepomohlo odhlášení/přihlášení.
Prohlížeč: Firefox 111.0.1
Přikládám screenthoty všech tří záložek s možnosti zakliknutí volby, aby byl vidět rozdíl v barvě.

![Screenshot from 2023-04-21 11-23-18](https://user-images.githubusercontent.com/6068291/233600023-b8c65e46-ae5b-4b03-bf27-a933fa4c2059.png)
![Screenshot from 2023-04-21 11-22-58](https://user-images.githubusercontent.com/6068291/233600051-0e21af90-e304-4399-8fd9-0bc7f5d76227.png)
![Screenshot from 2023-04-21 11-23-47](https://user-images.githubusercontent.com/6068291/233600074-3e392881-63b4-4c28-9c70-8ee5ed0edb9e.png)

**Comment by anezkamll** [comment]
2) jsem zkušela, než jsem ti psala poprvé
1) jsem taky chtěla zkusit, ale vůbec se mi na první dobrou nepodařilo přihlásit, vyzkouším

**Comment by anezkamll** [comment]
Potrvzuju, že problém trvá i v Chrome

**Comment by zoul** [comment]
Můžeš prosím zkusit teď?

**Comment by anezkamll** [comment]
už funguje :heart: 
![Screenshot from 2023-04-26 13-22-47](https://user-images.githubusercontent.com/6068291/234560501-c8e74aa7-ad08-4f50-9f64-df27ca14b716.png)

**Comment by zoul** [comment]
Supr. Chyba souvisela s přejmenováním preferenční skupiny v Ecomailu, server nám posílal název preferenční skupiny, který jsme nečekali. Upravil jsem kód tak, aby tu neznámou skupinu ignoroval. Opraveno v 1878132258eae8da830477798c1963ca619d9a8b.
