### ISSUE TITLE
Přejmenovat Portál dobrovolníka

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#875]
Narazili jsme na to mockrát, [kontext například tady](https://cesko-digital.slack.com/archives/CHG9NA23D/p1689234880156289).

**Comment by anezkamll** [comment]
Seznam míst, kde je třeba změnit ASAP, jakmile se změní na webu:

* [ ] onboarding e-mails
* [ ] onboarding slack bot
* [ ] checklist dobrovolníka https://cesko-digital.atlassian.net/l/cp/VgCbfk5H 
* [ ] role dobrovolníka https://cesko-digital.atlassian.net/l/cp/11LLdQnF

**Comment by anezkamll** [comment]
Pokračuju postupně s úpravami na wiki.
