### ISSUE TITLE
Oslovení zadavatele market-place přes button na stránce

### ISSUE THREAD

**Issue by romiinna** [cesko-digital/web#889]
Ve chvíli, kdy chci oslovit zadavatele poptávky z market-place (na webu https://cesko.digital/marketplace) vyberu možnost "ozvat se mailem". 

V té chvíli se může stát několik věcí dle mých dig. schopností: 
1. otevře se mi mailový klient 
2. otevře se mi nový mail v prohlížeči (pokud mám správně nastaveno viz postup zde: https://www.indeed.com/career-advice/career-development/how-to-get-email-links-to-open-in-chrome) 
3. objeví se mi v levém dolním rohu mailto:franta@vomacka.cz

je možné odpovědět na poptávku více user friendly cestou? 

PS: dle doporučení Anežky jsem si nainstalovala postup dle bodu 2, jinak jsem byla v bodu 3.

**Comment by zoul** [comment]
Tohle už nebude relevantní vzhledem k #946.
