### ISSUE TITLE
Implementace komponenty pro URL navigaci pro podstránky

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#93]
**Technologie:** React, TypeScript, Gatsby

V rámci #64

Implementovat navigaci pro podstránky. Nutné vymyslet způsob zisku cesty z konkrétní URL včetně názvy stránek.  Výsledkem by měla být univerzální komponenta, která se použije v `Layout` komponentě nebo samostatně. 

Je nutné počítat s překlady (#68). Komponenta by měla využít existující komponenty tlačítka (#65). 

**Figma**: [link](https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=276%3A294)

V případě nejasností nebojte se na mne obrátit. 🙂

<img width="153" alt="Screenshot 2020-11-18 at 18 25 24" src="https://user-images.githubusercontent.com/10332399/99565005-71d7cc80-29cb-11eb-97bd-696f08c2a80d.png">

**Comment by maral** [comment]
Zkusím si to vzít. Mám pár otázek:
- Ze zadání se mi zdá, že se to má celé vygenerovat automaticky podle URL. Je to tak?
- Pokud to má fungovat automaticky z URL, bude třeba mít někde definici všech cest (v podobě stromu), včetně klíčů k překladům titulku stránky. A jestli bude i URL lokalizovaná, tak i mít všechny ty lokalizované cesty stažené.
- Jiná možnost je využít k URL jmennou konvenci tj. např. /projekty/dame-rousky vrátí překladové klíče page.projekty a page.projekty.dame_rousky nebo tak něco. Ale to pořád nebude fungovat s lokalizovanými URL.
- Jako o dost jednodušší řešení se nabízí, že by se přes prop předala cesta, např.:

```
<Breadcrumb path=[ 
    { translationKey: 'page.projects', path: '/projects' },
    { translationKey: 'page.projects.dame_rousky' },
  ]
/>
```

Případně by se to zakomponovalo přímo do Layout a ten parametr by se předával rovnou do něj, pro každou stránku zvlášť.

Pro tu automatickou tvorbu navigace z URL by se dal použít plugin [gatsby-plugin-breadcrumb](https://www.gatsbyjs.com/plugins/gatsby-plugin-breadcrumb/), případně lze se inspirovat v jeho [kódu, kde k parsování dochází](https://github.com/sbardian/gatsby-plugin-breadcrumb/blob/develop/src/gatsby-node.js). Ale jak jsem psal, možná je to zbytečně komplikované, obzvlášť s těmi překlady rout.

**Comment by HormCodes** [comment]
@maral, díky moc za research. 

Ano, původně jsem issue specifikoval tak, že by to mělo být generované. S tvým inputem (jsem rád, že jsi nejdříve prozkoumal možnosti) však myslím, že bychom se měli vydat cestou jednoduchécho řešení . Tedy cestou definice cesty pro každou stránku. Ze začátku budeme mít 2 až 3 stránky a nebude nám nic bránit toto jednoduché řešení rozšířit. 

Navrhované rozhraní komponenty vypadá dobře, za mne jen bych `translationKey` nahradil za `label` a překlad provedl na úrovni komponenty pro stránku. 

Komponenta klidně ve výsledku může být součastí komponenty `Layout`, pokud se to ukáže jako užitečné.

**Comment by maral** [comment]
Super :) Už mám většinu hotovou. A k `label` místo `translationKey` jsem dospěl taky.
