### ISSUE TITLE
Přehodit službu Tržiště na Discourse

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#946]
Plánujeme vytáhnout službu Market-place ze Slacku na Discourse. Co to technicky obnáší:

* [x] Předělat načítání dat z databáze na Discourse
* [x] Zahodit integraci se Slackem
* [x] Zahodit databázi v Airtable

CC @GabiChl

**Comment by zoul** [comment]
Seznam témat v konkrétní kategorii jde získat přes API, [viz dokumentaci](https://docs.discourse.org/#tag/Categories/operation/listCategoryTopics). V reálu je to prostě JSON na známé adrese, pro Tržiště konkrétně na [/c/trziste/5.json](https://diskutuj.digital/c/trziste/5.json). Odsud už dostaneme přehled témat a nejspíš i seznam diskutujících, ale pokud budeme chtít tělo příspěvu, asi to bude chtít extra volání API.

**Comment by GabiChl** [comment]
@zoul ahoj Tome, dotaz, jestli už je toto live? Dnes bych ráda postla na Slack do market-place info. o přesunu a v neděli to půjde do komunity obecně a další dny ven, tak jen check, že už je to teda přesunuto? díky

**Comment by zoul** [comment]
Je to hotové, [viz Slack](https://cesko-digital.slack.com/archives/CHG9NA23D/p1705936033228709).

**Comment by GabiChl** [comment]
díky a omluva, že jsem to neudržela v hlavě. :)
