### ISSUE TITLE
Lepší mobilní UI pro tab bar

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#948]
Nový tab bar (který je vidět například v uživatelském profilu) se nezobrazuje hezky na úzkých displejích:

![narrow](https://github.com/cesko-digital/web/assets/95329/f6729604-6b11-4681-8c4f-5eefca2f0da7)

Jedna z možných lepších variant je schovat ty přetékající položky pod tlačítko, a la GitHub:

![GitHub](https://github.com/cesko-digital/web/assets/95329/88eacaa0-e752-4eb9-90fc-eebadf96b095)

Další možnost je přehodit zobrazení těch tabů na drop down, klidně i standardní `<select>` bez (velkého) stylování. A ještě třetí možnost, co mě napadá, je nechat současné zobrazení, ale nechat ho scrollovat do boku.

Nechce se na to podívat @drahoja9? Příslušná komponenta je v `components/TabBar.tsx`. Uživatelský profil je AFAIK zatím jediné místo, kde ten tab bar máme.

**Comment by drahoja9** [comment]
Rád na to kouknu, do konce týdne na to snad čas najdu. 🙂

Horizontální scrollování (do stran) mi přijde v tomhle případě asi jako nejlepší poměr cena/efektivita.
