### ISSUE TITLE
Nastavit deployment a hostování pro Storybook

### ISSUE THREAD

**Issue by HormCodes** [cesko-digital/web#95]
[Storybook](https://storybook.js.org/) využíváme pro dokumentaci komponent. Bylo by užitečné mít Storybook někde nasazený. 

Zkusit prozkoumat, zda se nedá využít [Vercel](https://vercel.com/), který využíváme už pro hostování webu. Nastavení subdomény `vhodny-nazev.cesko.digital` zatím není potřeba.

**Comment by HormCodes** [comment]
@radkoa, mohu poprosit o [nastavení production branch](https://vercel.com/ceskodigital/web-storybook/settings/git) na `rework`?

**Comment by radkoa** [comment]
Ahoj @HormCodes, nastaveno.
