### ISSUE TITLE
Přidat do tab baru možnost routování na konkrétní záložku přes #kotvy

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#955]
Máme komponentu `TabBar` se záložkami, ale zvenčí nejde odkázat na konkrétní záložku. Časem se nám to určitě bude hodit, takže by bylo dobré, kdyby tab bar uměl automaticky začít na záložce podle `#kotvy` v URL. Hlavní zádrhel je v čtení té kotvy, je to logicky trochu komplikované kvůli rozdílu server vs. klient a kvůli client-side navigaci. Něco podobného už na webu máme a došel jsem tam k tomuhle hooku:

```typescript
/**
 * Return the hash part of the current page URL
 *
 * https://github.com/vercel/next.js/discussions/49465#discussioncomment-6966993
 */
const useHash = () => {
  const [hash, setHash] = useState(getHash());
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    const handleHashChange = () => {
      setHash(getHash());
    };
    setHash(getHash());
    window.addEventListener("hashchange", handleHashChange);
    return () => {
      window.removeEventListener("hashchange", handleHashChange);
    };
  }, []);

  return isClient ? hash : undefined;
};

const getHash = () =>
  typeof window !== "undefined"
    ? decodeURIComponent(window.location.hash.replace("#", ""))
    : undefined;
```

Je to trochu bizár, ale funguje to 🤷‍♂️ 

@drahoja9, nechceš na tohle mrknout? :)

**Comment by drahoja9** [comment]
Zkusim na to kouknout. 🙂

**Comment by zoul** [comment]
Super, díky! Dal jsem ti práva na repo, ať si můžeš udělat větev přímo tady, mělo by to zjednodušit nasazování náhledů na Vercelu.
