### ISSUE TITLE
Měření unikátních uživatelů v app.cesko.digital

### ISSUE THREAD

**Issue by anezkamll** [cesko-digital/web#977]
Přidat do datového dashboardu měření, kolik unikátních uživatelů se přihlašuje do app.cesko.digital

**Comment by zoul** [comment]
Přidal jsem, viz https://app.cesko.digital/stats. Pokud nemáme chybu v měření, je to zatím do deseti lidí měsíčně, což dává bezvadný smysl a… je co zlepšovat :)
